ipspace/netlab

ansible/config/arcos.yml, collect-configs.ansible, config.ansible, docs/install.md, templates/initial/arcos.j2, templates/vagrant/libvirt/arcos-domain.j2, topology-defaults.yml, vendor_specific_tasks/arcos/collect_config.yml
Few Notes:
I have followed all the steps on your https://netsim-tools.readthedocs.io/en/latest/platforms.html#contributing-new-devices page.  Thanks for making it straight forward to add a new device type.  This PR passes the tests you laid out in that document.
A customer wishing to use ArcOS nodes in these topologies will need to reach out to their Arrcus Rep for access to both the Vagrant Box file and Ansible collection for ArcOS.   I added a note to that in the install.md file
Since ArcOS doesn't support a gather_facts module, I wrote a quick playbook so the collect configs would still be supported.  Not sure where you wanted to store that so I added a new directory called `vendor_specific_tasks`.  Now that I type that its sort of a terrible name,  so if you need that renamed let me …
=> Adding Support for ArcOS

templates/ospf/arcos.j2, templates/provider/virtualbox/arcos-domain.j2
Added:
- OSPF config template for OSPF in ArcOS
- VB template for ArcOS VMDK
Currently, no support for unnumbered interfaces in ArcOS.  But I will add when/if that comes.
=> adding support for OSPF in ArcOS

docs/install.md, install.libvirt
=> Create a Ansible playbook for libvirt installation

netsim/providers/__init__.py, netsim/templates/provider/libvirt/vsrx-domain.j2
Optionally add in `domain.cpu_mode = "custom"` in the `vm.provider` section of the Vagrantfile for vSRX VMs. This forces the cpu mode to `qemu64` which seems to work for running vSRXs, although the performance is quite bad.
I'ved used the transform method of the Provider class for this because it seemed a right use case for it. I can move it elsewhere if you want.
Fixes #9
=> Fix running vSRX under AMD CPUs.

templates/initial/junos.j2
My vSRX VMs came up without LLDP enabled. I'm not well versed enough in Junos to know is this is generally applicable so a sanity check there would be great.
=> Fix LLDP configuration for Junos

install.libvirt, requirements.yml
Re #14:
> At least the "legacy" NXOS and Junos modules should be in Ansible distro, so I'm wondering why you don't have them.
Doesn't that have something to do with the introductions of collections in Ansible 2.9? I thought they moved everything but the ansible-base to Ansible galaxy.
> In any case, the change makes perfect sense (and is along the lines of what Ansible team is preaching), but if we do install network device collections, we should do it for all supported devices (+ IOS, EOS).
Fixed. Providing a [requirements.yml](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#install-multiple-collections-with-a-requirements-file) for Ansible collections.
> Also, it looks like the "changed when" test would report no changes when one collection is installed but another one is …
=> Expand install libvirt to install Ansible collections

docs/install.md
The `wget` command downloaded the HTML page rather than the raw script. I've updated that and included the `requirements.yml` file in the download because otherwise the command would fail.
=> Fix Ansible install docs

docs/labs/libvirt.md, docs/platforms.md, netsim/ansible/tasks/deploy-config/routeros.yml, netsim/ansible/tasks/fetch-config/routeros.yml, netsim/ansible/templates/bgp/routeros.j2, netsim/ansible/templates/initial/routeros.j2, netsim/ansible/templates/ospf/routeros.j2, netsim/templates/provider/libvirt/routeros-domain.j2, netsim/topology-defaults.yml, tests/integration/routeros-ospf-multiarea.yml, tests/integration/routeros.yml
Support for Mikrotik CHR RouterOS device type, with initial configuration, config check,
bgp and ospf modules. Docs are updated as well.
Vagrant box build instructions by Stefano Sasso has been set as a list
(instead of a single reference).
=> Add support for Mikrotik CHR RouterOS

netsim/ansible/templates/initial/ios.j2
`no ip domain-lookup` command is not available on newer Cisco IOS-XE versions.
The updated command is `no ip domain lookup`, which is available also on older versions.
Tested on:
* 03.15.00.S.155
* 17.03.03
=> Fix: IOS-XE syntax for domain lookup

netsim/templates/provider/libvirt/fortios-domain.j2, netsim/topology-defaults.yml
Allow fortios VMs to be spun up via libvirt provider. Note ansible support not in this PR.
=> Fortinet support for libvirt

docs/links.md, netsim/addressing.py, tests/topology/expected/link-without-prefix.yml, tests/topology/input/link-without-prefix.yml
In certain cases it might be required to have links configured without IP addresses
(and without all the "ip unnumbered" stuff)
With this patch, it should be possible to specify **prefix** as _false_ on the link attributes. With this, the _ipv4_ or _ipv6_ keys will not be present on the link augmented attributes, hence skipping all the IP address configuration part of the templates.
This would be useful i.e. when testing VLANs, or M(c)LAG peer link or - in general - when you want a link but you would like to configure every IP parameter on your own.
=> WIP: Support link without IP configuration

netsim/cli/external_commands.py
In my case: netlab wasn't in the PATH
=> Print exception to stdout such that user can understand what went wrong

netsim/cli/up.py, netsim/providers/__init__.py, netsim/providers/libvirt.py, netsim/templates/provider/libvirt/routeros-domain.j2
Updated code to run pre_start and post_start hooks on **netlab up**.
This is required to have also a check on the libvirt management network bridge (pre_start)
and creating it if not already present. This is required starting from vagrant-libvirt
0.7.0, which destroys the bridge at every vagrant destroy.
Additionally: the *vm.guest* type :other is not usable anymore on newer Vagrant versions. This has been removed from the routeros template.
This PR replaces https://github.com/ipspace/netsim-tools/pull/74 .
=> Pre and Post start hooks for libvirt LAB UP

netsim/ansible/templates/bfd/sros.gnmi.j2, netsim/ansible/templates/initial/sros.gnmi.j2, netsim/ansible/templates/isis/srlinux.j2, netsim/ansible/templates/isis/sros.gnmi.j2, netsim/ansible/templates/ospf/srlinux.j2, netsim/ansible/templates/ospf/sros.gnmi.j2, tests/integration/sros-srlinux.yml
* Change to always use 'system' interface as loopback, needed for unnumbered support
* Also includes annotated config for SR Linux explaining why interfaces are excluded from IGP
=> Support new unnumbered style on sros

netsim/ansible/tasks/deploy-config/srlinux.yml, netsim/ansible/tasks/deploy-config/sros.yml, netsim/topology-defaults.yml, tests/topology/expected/device-global-attr.yml, tests/topology/expected/isis-bfd-test.yml
- Change default ansible connection sros and srlinux, grpc only used for very specific tasks; Ansible sometimes uses the underlying connection at times when it's least expected
=> Cleanup topology defaults for sros and srlinux

netsim/ansible/templates/isis/junos.j2, netsim/ansible/templates/ospf/junos.j2
Trying to address #109 for OSPF and IS-IS at protocol level (It seems that BFD on Junos is configurable only on a per-protocol basis / protocol->interface).
Not updating documentation to avoid conflicts with #130.
=> Initial support for JunOS BFD for OSPF and ISIS

docs/labs/clab.md, netsim/providers/clab.py, netsim/templates/provider/clab/clab.j2, netsim/topology-defaults.yml
Also modifies the Linux bridges to forward LLDP, LACP, 802.1X and other multicast protocols
Use case for OVS: OSPF over multi-access, for some reason the Linux bridge does not forward Hello packets
Default to Linux standard bridges, OVS requires separate package
=> clab add OVS bridge support

docs/caveats.md, netsim/ansible/tasks/fortinet.fortios.fortios/initial.yml, netsim/ansible/tasks/fortinet.fortios.fortios/ospf.yml
Bug fix for Fortinet OSPF:
- Removed caveat from caveats.md
- Corrected fortinet ansible templates to use `interfaces` instead of `links`
- Uncommented fortinet ansible task _Configure OSPF network statement_ now that it's got correct syntax and works
Tested this on the example topology called fortinet.yml
=> Bug fix: fortinet ospf area id now correctly set

netsim/ansible/templates/initial/cumulus.j2, netsim/topology-defaults.yml, tests/topology/expected/unnumbered.yml, tests/topology/input/unnumbered.yml
Platforms: Add support for IP unnumbered interfaces on Cumulus
- Mod `initial/cumulus.j2` to set unnumbered interfaces to have loopback IP address
- Reference: https://support.cumulusnetworks.com/hc/en-us/articles/202796476-RETIRED-OSPF-Unnumbered-Sample-Configurations
- Mod `topology-defaults.yml` to allow ip unnumbered and ospf unnumbered
- Add cumulus box to `tests` @ipspace please verify these two changes, as I can't test since I don't have all the images mentioned
=> Platforms: Cumulus ip unnumbered support

.gitignore, netsim/ansible/templates/bgp/cumulus.j2, netsim/modules/bgp.py, tests/topology/expected/bgp-unnumbered.yml, tests/topology/input/bgp-unnumbered.yml
Platforms: Add initial support for ebgp unnumbered on Cumulus
* mod `netsim/ansible/templates/bgp/cumulus.j2` to change logic:
* if bgp neighbor is unnumbered, don't bother with BGP AFs since unnumbered can't distinguish them
* else add per-AF peer info 
* mod `netsim/modules/bgp.py to support ebgp unnumbered:
* Sorry about the python formatting changes! See issue filed so I don't ever do this again, or I can resubmit
* Lines 58-62: Set unnumbered interface ip to `True` and capture local interface name
* Line 235: pass local interface to function via `extra_data`
=> Platforms: Cumulus eBGP unnumbered support

netsim/ansible/templates/bgp/srlinux.cli.j2, netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/bgp/sros.md-cli.j2, netsim/ansible/templates/bgp/sros.openconfig.j2, netsim/ansible/templates/ospf/srlinux.j2, netsim/ansible/templates/ospf/sros.gnmi.j2, netsim/ansible/templates/ospf/sros.md-cli.j2
Implements https://github.com/ipspace/netsim-tools/issues/148
I noticed the other templates check for a valid ipv4 address, assuming that is unnecessary
Note that IS-IS also needs a router-id (per protocol instance)
=> Use router_id for sros and srlinux

netsim/ansible/tasks/deploy-config/srlinux.yml, netsim/ansible/tasks/deploy-config/sros.yml
* Also extend waiting time from 120 to 150 seconds
* Don't try OpenConfig on ixr-ec
Addresses https://github.com/ipspace/netsim-tools/issues/168
=> Add a check for the required gNMI plugin, including how to install it if missing

docs/module/srv6.md, netsim/ansible/tasks/deploy-config/sros.yml, netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/initial/sros.gnmi.j2, netsim/ansible/templates/srv6/sros.gnmi.j2, netsim/modules/srv6.py, netsim/topology-defaults.yml, tests/topology/expected/addressing-ipv6-only.yml, tests/topology/expected/bgp-anycast.yml, tests/topology/expected/bgp-autogroup.yml, tests/topology/expected/bgp-community.yml, tests/topology/expected/bgp-ibgp.yml, tests/topology/expected/bgp-members.yml, tests/topology/expected/bgp-unnumbered.yml, tests/topology/expected/bgp.yml, tests/topology/expected/groups-node-data.yml, tests/topology/expected/module-node-global-params.yml, tests/topology/expected/module-node-global.yml, tests/topology/expected/module-node-only.yml, tests/topology/expected/module-node-params.yml, tests/topology/expected/module-reorder.yml, tests/topology/expected/unroll.yml
I've tried to minimize the deltas required to implement this, this PR proposes to add an 'address_families' knob for bgp to provide more control over the enabled protocols (to be extended to include evpn in the near future)
=> Add srv6 module (with initial support on sros)

netsim/ansible/tasks/fortinet.fortios.fortios/ospf.yml, netsim/ansible/templates/bgp/cumulus_nvue.j2, netsim/ansible/templates/ospf/cumulus_nvue.j2
Fixes for https://github.com/ipspace/netsim-tools/issues/148
Platforms:
- Cumulus NVUE:
- Fixed ospf template to use router_id
- Fixed bgp template to use router_id
- Fortinet:
- Fixed ospf template to use router_id
=> switch to router_id for ospf & bgp

netsim/ansible/templates/bgp/junos.j2, netsim/ansible/templates/bgp/srlinux.cli.j2, netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/bgp/sros.openconfig.j2, netsim/modules/bgp.py, tests/topology/expected/bgp-autogroup.yml, tests/topology/expected/bgp-ibgp.yml, tests/topology/expected/bgp-members.yml, tests/topology/expected/bgp.yml
See https://datatracker.ietf.org/doc/html/rfc4456#section-7 - a cluster of iBGP route reflectors should be configured with the same cluster-id as a loop prevention measure.
This patch calculates abgp.rr_cluster_id using the lowest id of the rr nodes
=> Determine same iBGP RR cluster-id for redundant clusters

netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/initial/sros.gnmi.j2, netsim/ansible/templates/ospf/sros.gnmi.j2, netsim/topology-defaults.yml
See https://github.com/ipspace/netsim-tools/issues/171
Note that the maximum supported L2 MTU on SR OS is 9800, any larger values are currently ignored without warning.
We may want to add a sanity check and min/max supported values per device in topology-defaults.yml
=> SR OS and SR Linux set custom port mtu

netsim/ansible/templates/bgp/cumulus.j2, netsim/ansible/templates/bgp/eos.j2, netsim/ansible/templates/bgp/frr.j2, netsim/ansible/templates/bgp/ios.j2, netsim/ansible/templates/bgp/junos.j2, netsim/ansible/templates/bgp/nxos.j2, netsim/ansible/templates/bgp/srlinux.cli.j2, netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/bgp/sros.openconfig.j2, netsim/topology-defaults.yml
We might not want to enforce bgp.rr_cluster_id in all situations. Setting bgp.rr_cluster_id to False in node data does that, but that possibility has to be recognized in configuration templates.
There are two types of device configuration templates in regards to BGP RR cluster-id attribute:
* Devices that configure RR-clients on BGP sessions (IOS, EOS, NXOS, Cumulus...) -- on those devices we simply don't configure **cluster-id** if bgp.rr is not True or bgp.rr_cluster_id is not set.
* Devices that use **cluster-id** to change a BGP speaker into a route reflector -- on those devices we have to use **bgp.rr_cluster_id** or **bgp.router_id** as the cluster ID.
@jbemmel: Please check whether I made correct changes to SR Linux and SR OS templates. Thank you!
=> Make BGP cluster ID optional

netsim/augment/links.py, netsim/augment/nodes.py
Fixes https://github.com/ipspace/netsim-tools/issues/213
There are 92 cases of interfaces|default([]) in the templates that could be simplified
=> Always define node.interfaces

netsim/topology-defaults.yml
Hi,
on some flavours, the python binary cannot be found in `/usr/local/bin/`
I experienced the same issue with some containers (for linux hosts) as well, which breaks Ansible at the task "template":
`Failed to get information on remote file (/tmp/config.sh): /bin/sh: 1: /usr/local/bin/python3: not found`
Even though, this is a packaging issue and not really a netsim issue, I wonder if we could proactively avoid some Ansible drama by using another $PATH with more better to succeed (or maybe implement a smart routine to check different $PATH).
Not sure this patch makes sense, but anyway, maybe someone will get a smarter solution :)
Julien
=> Change python path to avoid Ansible issue

netsim/ansible/tasks/deploy-config/cumulus_nvue.yml, netsim/topology-defaults.yml
Hi everyone,
it looks like the support of NVUE for CL 5.0.1 and containerlab is missing, so this patch enables the (small) missing part.
Unless I missed something, that works, `run-tests` looks good as well:
`Success: no issues found in 53 source files`
Let me know if something is needed for that part :)
Julien
=> Enable Cumulus 5.0.1 NVUE for Clab

netsim/ansible/templates/initial/linux.j2
It seems on the Vagrant box for ubuntu 20.04, DNS Servers are hardcoded as 4.2.2.1 & Co.
This is annoying on a network with filtered DNS.
DNSMasq server used for giving out DHCP addresses on the management network is able to act as a DNS Server.
Let's use that.
=> Fix: Ubuntu Vagrant Box DNS stuff

netsim/ansible/templates/initial/routeros.j2
Mikrotik: add comment on IP Addresses, for better troubleshooting.
Works only on IPv4, for now. On IPv6 there seems to be match problems in the *find/where* statement.
=> Mikrotik: add comment on IP Addresses

docs/outputs/graphite.md, docs/outputs/index.md, netsim/outputs/graphite.py, netsim/topology-defaults.yml
Why use Graphite (https://github.com/netreplica/graphite) only with ContainerLab? :-)
With this output module it would be possible to export a topology file to be used within Graphite.
Graphite container can be launched with:
```
docker run -d \
-v "$(pwd)/graphite-default.json":/var/www/localhost/htdocs/default/default.json \
-p 8080:80 \
--name graphite \
netreplica/graphite:webssh2
```
Result example: 
Additionally, with the *graphite:webssh2*, SSH can be launched from the browser as well ;)
=> Support output in Graphite JSON format

docs/labs/dellos10.md, docs/labs/dellos10.txt, docs/labs/libvirt.md, docs/module/bfd.md, docs/module/ospf.md, docs/module/vrf.md, docs/platforms.md, netsim/ansible/tasks/deploy-config/dellos10.yml, netsim/ansible/tasks/fetch-config/dellos10.yml, netsim/ansible/templates/bgp/dellos10.j2, netsim/ansible/templates/bgp/dellos10.macro.j2, netsim/ansible/templates/initial/dellos10.j2, netsim/ansible/templates/initial/dellos10.vrf.j2, netsim/ansible/templates/ospf/dellos10.j2, netsim/ansible/templates/ospf/dellos10.ospfv2.j2, netsim/ansible/templates/ospf/dellos10.ospfv3.j2, netsim/ansible/templates/vrf/dellos10.bgp-macro.j2, netsim/ansible/templates/vrf/dellos10.bgp.j2, netsim/ansible/templates/vrf/dellos10.j2, netsim/ansible/templates/vrf/dellos10.ospfv2-vrf.j2, netsim/install/libvirt/dellos10.txt, netsim/templates/provider/libvirt/dellos10-domain.j2, netsim/topology-defaults.yml, tests/integration/dellos10.yml
**Support for Dell OS10 NOS**, with:
- initial config
- config fetch
- BGP (ipv4/ipv6)
- OSPF (v2/v3)
- VRF (VRF-Lite)
- Libvirt install documentation
- Integration testing topology
=> Support for Dell OS10

docs/module/mpls.md, netsim/ansible/templates/mpls/vyos.j2, netsim/ansible/templates/mpls/vyos.ldp.j2, netsim/ansible/templates/mpls/vyos.mplsvpn.j2, netsim/topology-defaults.yml
@ipspace **WARNING**: 
I had to add to the **vrf** module the following (otherwise frr on vyos does not correctly handle the service label):
```
config_after: [ ospf, isis, bgp, mpls ]
```
It seems to me that also *logically* this ordering is fine.
A did a quick test of a L3VPN topology with *vyos* (of course ;) ), *csr*, *eos*, *chr*, and everything looked good.
Do you see any other issue with that change?
=> VyOS: Support for MPLS (and MPLS L3VPN)

netsim/ansible/templates/initial/linux.j2
Hi,
with clab/docker as provider, Linux hosts are using the image `python:3.9-alpine` but that triggers some issues due to the absence of `netplan` and `systemd`.
This is a quick-and-dirty fix to keep things working with Alpine, but maybe we should implement a routine to deal with the flavor of images pulled (alpine/debian/ubuntu/rh). Replacing `python:3.9-alpine` with an official ubuntu images required the install of python.
Julien
=> Update linux.j2 - fix for Alpine

netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/ansible/templates/vrf/cumulus_nvue.j2, netsim/topology-defaults.yml
Hi,
I couldn't finish the full implementation for VRF, but this commit enable VRF-lite for CL5 (nvue).
```
provider: clab
name: toto
vrfs:
RED:
blue:
nodes:
spine01:
device: cumulus_nvue
leaf01:
device: cumulus_nvue
module: [ vrf ]
links:
- leaf01: { vrf: RED }
spine01:
```
```
root@leaf01:/# nv config show
- set:
system:
hostname: leaf01
vrf:
RED:
table: auto
[...]
swp1:
description: leaf01 -> spine01
ip:
address:
10.1.0.1/30: {}
vrf: RED
```
```
ubuntu@oob-mgmt-server:~$ docker exec -it clab-toto-spine01 ping -c2 10.1.0.1
PING 10.1.0.1 (10.1.0.1) 56(84) bytes of data.
64 bytes from 10.1.0.1: icmp_seq=1 ttl=64 time=0.118 ms
64 bytes from 10.1.0.1: icmp_seq=2 ttl=64 time=0.064 ms
```
=> Preliminary work for VRF and Cumulus NVUE

netsim/install/ansible.sh, netsim/install/containerlab.sh, netsim/install/libvirt.sh, netsim/install/ubuntu.sh
Summary of changes:
- Corrected all scripts to accept an empty response as Y
- Added Debian/Ubuntu distribution detection in containerlab.sh to add the correct docker repository
- Re-referenced Docker APT GPG key and APT source definition in containerlab.sh to use the APT trusted.gpg.d directory
- Removed deprecated use of "apt-key add" and "add-apt-repository" in libvirt.sh and replaced it with current mechanism
- Added curl to missing packages in ubuntu.sh as this is not installed by default in Debian
To-do:
Deal with the fact that sudo is not installed by default on Debian. Scripts test successfully on Debian 10/11 as long as sudo is installed and configured or if run as root. Scripts test successfully on Ubuntu 20/21.
=> Debian compatibility and general cleanup

netsim/ansible/tasks/deploy-config/cumulus_nvue.yml
At least on my deployment with libvirt, the task "Start NVUE daemon" brutally dies with the following:
```
fatal: [s1]: FAILED! => changed=true
cmd:
- systemctl
- start
- nvued
delta: '0:00:00.014788'
end: '2022-04-21 10:49:43.656199'
msg: non-zero return code
rc: 4
start: '2022-04-21 10:49:43.641411'
stderr: |-
Failed to start nvued.service: Access denied
See system logs and 'systemctl status nvued.service' for details.
stderr_lines: <omitted>
stdout: ''
stdout_lines: <omitted>
```
this seems due to the fact that, on the libvirt image, the ansible login is done with the vagrant/cumulus ssh user.
Using *sudo* shall work for both the libvirt and container use case.
(I tested the patch both with libvirt and CLAB, but please @barajus give it a check as well, thanks!)
=> [Fix] Cumulus NVUE daemon start error on libvirt

docs/labs/dellos10.md, docs/platforms.md, netsim/topology-defaults.yml
Updated doc on image creation.
Dell seems to provide the virtual image for every single release now, so the workaround for version upgrade is no longer needed.
=> OS10: fixes on documentation and updated image creation

docs/nodes.md, docs/platforms.md, netsim/templates/provider/libvirt/Vagrantfile.j2, netsim/topology-defaults.yml
It would be useful to support libvirt nic_model override at node level.
Use case example:
VyOS, but Linux in general, has problems in creating a *LACP LAG* with the *virtio* driver. For that reason, in that case the use of *e1000* is adviced.
On the other hand, *e1000* has problems with IPSec/GRE encapsulation...
So it would be useful to override that based on the specific test use case.
(@ipspace I might have been messing up the *topology-defaults* and *platforms.md* files between this and my previous PR. Sorry for this, but I prefer starting from the *dev* branch.)
=> libvirt Vagrantfile support for node-level nic_model

docs/outputs/graphite.md
**Graphite** *webssh2* has been merged into main branch:
(https://github.com/netreplica/graphite/pull/19)
=> Doc update: Graphite container to use latest image tag

docs/platforms.md, docs/topology-overview.md, netsim/augment/links.py, netsim/augment/nodes.py, netsim/providers/external.py, netsim/templates/provider/external/external.j2, netsim/topology-defaults.yml
(reordered #269)
There might be some situations where you want to use a Network Topology external to the netsim-tools VM (i.e., a physical lab, a cloud deployment, ...)... but you want to use netsim-tools to create and push the configuration using the "standard" methodology.
This PR wants to try to address that use case.
The external provider does the following:
- allows to use a different interface name as link->node attribute
- allows to specify the management IP address of the external device
- creates a TXT file with the physical cabling required for the Lab
- it asks for confirmation of the physical configuration before starting ansible
Example *topology.yaml* file for using this provider:
```
---
provider: external
defaults:
device: routeros
nodes:
r1:
mgmt.ipv4: 10.20.30.50 …
```
=> Support for External Topology provider

netsim/ansible/initial-config.ansible
Signed-off-by: Dinesh Dutt <dd.ps4u@gmail.com>
=> split should be used as .split for wider compat with Ansible

docs/module/vrf.md, netsim/ansible/templates/initial/dellos10.j2, netsim/ansible/templates/initial/vyos.j2, netsim/ansible/templates/vrf/dellos10.bgp.j2, netsim/ansible/templates/vrf/eos.bgp.j2, netsim/ansible/templates/vrf/ios.bgp.j2, netsim/ansible/templates/vrf/vyos.bgp.j2, netsim/modules/vrf.py, netsim/topology-defaults.yml
It could be useful to have additional Loopback interfaces on the VRF scopes.
The feature uses the same tecnique of the VLAN module to define *virtual_interface* names/kind (i.e. LoopbackX), creating additional virtual links (type: *loopback*) - thus allowing "transparent" interface creation.
A new default address pool has been created for these interfaces.
Additionally, these loopback addresses are defined as *network* in the BGP sections.
A loopback interface creation was already addressed for VRF->OSPF part, so nothing was changed on OSPFv2 handling.
(In any case *redistribute connected* was already present both for BGP and OSPF - but for BGP I feel more "elegant" to announce the loopback with "network").
=> Support for additional loopback interfaces for VRF

docs/links.md, netsim/augment/links.py
Many hardware platforms support different types of ports, with different speeds. For example, a Nokia 7220 IXR-D2 device (running SR Linux) has 48 25G ports and 8 100G ports.
The 100G ports are referenced as ethernet-1/49..56, and typical designs would use ports 1-48 for servers and 49-56 for spine links.
By default, netsim-tools would use ports 1, 2, 3, etc. This PR allows the user to pick port 48 for a spine facing link instead, by adding a custom 'ifindex' to override the auto-generated value
=> Optional user specified custom ifindex per link node

docs/module/vxlan.md, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/vlan/srlinux.j2, netsim/ansible/templates/vxlan/srlinux.j2, netsim/modules/__init__.py, netsim/modules/vxlan.py, netsim/topology-defaults.yml
Addresses https://github.com/ipspace/netsim-tools/issues/324
On SR Linux, VXLAN requires EVPN; it might be more elegant to allow a per-platform override of the 'requires' attribute for a module, but for now I've added a 'requires_evpn' flag which is set to True on SR Linux
=> Add L2 vxlan for SR Linux; requires evpn

docs/module/evpn.md, netsim/ansible/templates/vxlan/srlinux.j2, netsim/modules/evpn.py, netsim/topology-defaults.yml
The EVPN instance is a 16-bit identifier used in EVPN services. This PR allows the user to define an explicit value, or leave it as default ( = vlan id )
=> Model evpn.evi attribute in evpn module

netsim/ansible/templates/bgp/vyos.j2, netsim/ansible/templates/vrf/vyos.bgp.j2
Fix #334
Tested with VyOS 1.4-rolling-202208100217
Please @ipspace consider adding the following to the next release changelog:
`This is required for working with VyOS 1.4 rolling > 20220801 (built after August, 1st 2022)`
=> Fix VyOS new syntax for BGP System AS number

docs/module/evpn.md, netsim/ansible/templates/evpn/vyos.j2, netsim/ansible/templates/vxlan/vyos.j2, netsim/topology-defaults.yml
VyOS: EVPN VXLAN initial implementation
Support for VLAN-based service only.
=> VyOS: EVPN VXLAN initial implementation

docs/caveats.md, docs/labs/libvirt.md, docs/platforms.md, netsim/topology-defaults.yml
Updated VyOS documentation for using latest image from vagrant hub, and add platform caveats based on the fact this is a rolling release.
=> VyOS: Updated image info and caveats

docs/module/evpn.md, docs/module/vxlan.md, netsim/ansible/templates/evpn/vyos.j2, netsim/ansible/templates/vxlan/vyos.j2, netsim/modules/vxlan.py, netsim/topology-defaults.yml, tests/integration/vxlan/vxlan-bridging-v6only-vyos.yml
Updates on VXLAN IPv6 transport support & EVPN IPv6 for signaling.
Additioanlly, a patch to allow the use of IPv6 for VTEPs has been produced (_vxlan_ module).
=> VyOS: updates on VXLAN+EVPN IPv6

docs/module/evpn.md, netsim/ansible/templates/bgp/vyos.macro.j2, netsim/ansible/templates/evpn/vyos.j2, tests/integration/evpn/vxlan-bridging-ibgp-over-ebgp.yml
VyOS: add support for EVPN iBGP-over-eBGP, using the plugin **ebgp-local_as** by @jbemmel
=> VyOS: add support for EVPN iBGP-over-eBGP

docs/labs/libvirt.md
Vagran cannot automatically upgrade already downloaded box... but I think we should recommend it, at least for `vyos/current`.
=> Updated docs on vagran box update, especially for VyOS

netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/ospf/srlinux.macro.j2, netsim/ansible/templates/vlan/srlinux.j2, netsim/modules/vlan.py, netsim/topology-defaults.yml, tests/integration/vlan/vlan-irb-trunk.yml, tests/integration/vlan/vlan-routed-trunk.yml
Finally went through all the integration test cases under tests/integration/vlan and fixed all various corner cases.
Couple of notes:
* the vlan.mode attribute wasn't being propagated, this complicated the template logic
* consider not creating SVI interfaces for l2-only VLANs (could filter them out in each template, but easier to do once globally)
* trunk parent interfaces are detected when l.subif_index is defined, perhaps a type='trunk' (instead of p2p) would simplify things
=> SR Linux vlan fixes

docs/plugins/ebgp.utils.md, netsim/extra/ebgp.utils/eos.j2, netsim/extra/ebgp.utils/ios.j2, netsim/extra/ebgp.utils/plugin.py, netsim/extra/ebgp.utils/vyos.j2
Implement BGP *default-originate [always]* in `ebgp.utils` module.
Implements #354
Please @ipspace can you test the Cisco IOS part?
=> Support for BGP default-originate

netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/augment/links.py, netsim/extra/ebgp-local_as.py, tests/integration/vlan/vlan-vrf-route-leaking.yaml, tests/topology/expected/bgp-community.yml, tests/topology/expected/vrf-igp.yml, tests/topology/expected/vrf.yml
This example is pushing the limits of what one might setup in a test topology, I wanted to see if I could do EBGP peering locally to leak routes between VRFs.
To make this work, I had to extend neighbor lists with module specific interface attributes ( bgp.underlay_as in this case )
=> Ebgp unnumbered enhancements

netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/evpn/srlinux.j2, netsim/ansible/templates/initial/srlinux.j2, netsim/topology-defaults.yml, tests/topology/expected/device-module-defaults.yml
New features:
* bgp.local_as
* bgp.activate_af
* bgp.local_as_ibgp
* bgp.vrf_local_as
=> Srlinux template updates

netsim/ansible/templates/bgp/srlinux.macro.j2
Sample config:
```
bgp:
as: 64999
sessions: # Transport sessions to use
ipv4: [ ibgp ] # IBGP-v4 over EBGP-v6
ipv6: [ ebgp ]
activate: # Address families to activate
ipv4: [ ibgp, ebgp ] # Only activate ipv4
```
This results in an ipv6 lla neighbor with bgp.activate.ipv6 = False (and ipv4 not set). Since at least 1 address family must be activated, the template selects ipv4 for this case
=> Support ipv4-over-ipv6 for srlinux devices

netsim/install/containerlab.sh
Hi,
I faced an error during installation test phase, when running "netlab test clab"
```
Step 1: Checking virtualization provider installation
============================================================
Error executing containerlab version:
[Errno 2] No such file or directory: 'containerlab'
Fatal error in netlab: containerlab version failed, aborting
```
I figured out that the current url called in installation script is not resolving anymore.
```
~$ dig get-clab.srlinux.dev +answer +noall
~$
```
Containerlab website points to a new location now: https://get.containerlab.dev
Source: https://containerlab.dev/install/
=> Changed containerlab download url in install script

docs/module/bgp.md, netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/initial/srlinux.j2
* Also fixes learning of ipv6 unnumbered neighbors
* Update docs
For loopback prefixes, the export policy accepts all /32 addresses in the loopback range. This is not entirely correct - spines should advertise leaf loopbacks, but leaves should advertise only their own loopback. Not sure how to capture/model this properly
=> srlinux: Implement bgp route policies to export only specific prefixes

netsim/ansible/templates/bgp/srlinux.macro.j2
While considering https://github.com/ipspace/netlab/issues/393 I realized that all bgp prefixes need to be propagated
=> srlinux: Refactor ebgp policies to propagate all bgp prefixes by default

docs/dev/config/vlan.md, docs/module/evpn.md, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/ospf/srlinux.macro.j2, netsim/ansible/templates/vlan/srlinux.j2, netsim/ansible/templates/vrf/srlinux.j2, netsim/ansible/templates/vxlan/srlinux.j2, netsim/modules/evpn.py, netsim/topology-defaults.yml
* Add l3 vxlan support using vrf module; configure vxlan after vrf
* Add support for loopbacks in vrfs
* Refactored templates: Move vlan handling to vlan module
Removed evpn.transit_evi, now using vrfidx as suggested. May change to use reserved vlan id in the future
=> srlinux refactor templates and add vxlan l3 vrf support

netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/vlan/srlinux.j2, netsim/ansible/templates/vxlan/srlinux.j2
* Configure RT/RD explicitly
* Set ip-vrf type in case it does not exist yet
* Check for both bridged and routed interfaces, only add l2 to mac-vrf and set IPs on non-bridged
* Convert stub interface with /32 address into loopback
* Generate single host prefix for interface ip that is advertised
=> srlinux various fixes

netsim/modules/vlan.py
* Not too early, when traversing global topology
* Fill it in when creating per-node vlan dict (if not set)
Fixes https://github.com/ipspace/netlab/issues/418
Note that the pattern of getting a parameter from node / if not from topology / if not default value seems generic, could add a helper method in data
=> Fix routed trunk vlan mode

netsim/ansible/templates/bfd/sros.gnmi.j2, netsim/ansible/templates/initial/sros.gnmi.j2
Instead check purely for ipv4=True / ipv6=True
Context: https://github.com/ipspace/netlab/discussions/433
=> Remove dependency on 'unnumbered' flag in SROS templates

netsim/addressing.py, netsim/augment/links.py, netsim/augment/nodes.py, tests/topology/expected/addressing-lan.yml, tests/topology/expected/addressing-p2p.yml, tests/topology/expected/bgp-ibgp.yml, tests/topology/expected/bgp-unnumbered.yml, tests/topology/expected/igp-af.yml, tests/topology/expected/isis-feature-test.yml, tests/topology/expected/unnumbered.yml
* Add check for loopback pool, disallow 'True' there
Context: https://github.com/ipspace/netlab/discussions/433
=> Remove 'unnumbered' flag from output, not referenced by any device templates

netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/vlan/srlinux.j2, netsim/ansible/templates/vrf/srlinux.j2
- add 'lan' interfaces to mac-vrf too
- move communities to vrf module
- check correct .af attribute when exporting routes
- use bgp.as not vrf.as
Note that BGP import/export policies for more advanced topologies may still require custom manual configs
=> srlinux template fixes

netsim/templates/provider/clab/clab.j2
Adhere to the management network settings provided by Netlab, instead of using Containerlab defaults
Specifically, the Netlab default is ipv4-only while Containerlab provides ipv4+ipv6 by default.
=> Fix clab mgmt network

docs/module/bgp.md, netsim/ansible/tasks/deploy-config/vyos.yml, netsim/ansible/templates/bgp/dellos10.j2, netsim/ansible/templates/bgp/dellos10.macro.j2, netsim/ansible/templates/bgp/vyos.j2, netsim/ansible/templates/bgp/vyos.macro.j2, netsim/ansible/templates/initial/dellos10.j2, netsim/topology-defaults.yml
Tested with a modified version of `integration/evpn/vxlan-routing-ibgp-over-ebgp-unnumbered.yml`
=> VyOS and Dell OS10: Support for Unnumbered eBGP

netsim/ansible/templates/bgp/frr.bgp-config.j2, netsim/ansible/templates/initial/frr.j2
* Disable ipv6 ND when ipv6 is not configured (frr bug prevents this from getting applied)
* Don't enable ipv6 forwarding when ipv6 is disabled
* Explicitly disable ipv6 on interfaces without ipv6 enabled, under Linux
=> frr ipv6 disabled fixes

netsim/modules/vrf.py, tests/topology/expected/bgp-vrf-local-as.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vlan-vrf-lite.yml, tests/topology/expected/vrf.yml
As illustrated [here](https://github.com/ipspace/netlab/blob/dev/tests/integration/evpn/vxlan-asymmetric-irb.yml#L32) there are cases where vlans get pulled into a node without being referenced from an interface.
Currently, any vrf associated with such a vlan does not get pulled in - while I believe it should
This may be another case of some underlying issue that is better fixed elsewhere - just submitting the case and a straightforward fix to start with
This PR also ensures there is a deterministic order in which local vrfidx values get assigned, by sorting the vrfs on their global id. This avoids a dependency on the order in which vlans (with associated vrfs) appear in the file
=> Pull in vrfs associated with vlans

netsim/ansible/templates/evpn/frr.evpn-config.j2
Potentially more common than hierarchical route reflectors, but still quite rare.  If people want to try this, at least it won't fail because of the tooling
=> Fix corner case of evpn to ipv6 lla peers

netsim/ansible/tasks/deploy-config/srlinux.yml, netsim/ansible/templates/evpn/srlinux.j2, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/vlan/srlinux.j2, netsim/ansible/templates/vxlan/srlinux.j2, tests/integration/evpn/vxlan-symmetric-irb-leaf-pairs.yml
As illustrated by the included integration test case, in inter-subnet forwarding scenarios we need to explicitly enable advertisement of RT5 prefixes for hosts. This causes ARP ND entries to be advertised using the l3 transit VNI for the vrf
Also includes some minor fixes/enhancements
* Add verbosity setting for debug messages
* Add retries:2 for increased robustness against GRPC connection failures (at the expense of missing error messages in case of invalid configurations)
* Set lower default RA intervals to avoid long waits during boot
* Enable EVPN fast withdrawal
* Leave RD as auto-generated (Netlab provided RD value for IP-VPN scenarios breaks ecmp forwarding for evpn)
* Remove debug info
Related to https://github.com/ipspace/netlab/discussions/490
=> Critical fix: srlinux RT5 announcement of host routes for symmetric IRB inter-subnet forwarding

netsim/ansible/templates/bgp/srlinux.macro.j2
* Put ebgp policy at top level of vrf, easier to replace with custom configs
* Warn against using evpn with bgp unnumbered peers (could be a device feature flag, but isn't currently)
* Fix 'large' communities to be implied by 'standard', allow user to disable all communities by using []
=> SR Linux bgp fixes

docs/module/evpn.md, netsim/data/__init__.py, netsim/modules/evpn.py, tests/topology/expected/evpn-hub-spoke.yml, tests/topology/input/evpn-hub-spoke.yml
This is an alternate solution to #502. Instead of turning off uniqueness checks, allow a VRF evpn.transit_vni to refer to another VRF.
=> Use foreign VRF name as evpn.transit_vni to implement complex topologies

docs/module/evpn.md, netsim/ansible/templates/vxlan/srlinux.j2, netsim/modules/evpn.py, netsim/topology-defaults.yml, tests/integration/evpn/vxlan-vlan-bundle.yml
Supersedes https://github.com/ipspace/netlab/pull/503
SR Linux treats a VLAN bundle as a set of EVPN services, one per VNI. A unique RD is assigned per service, auto-generated based on the (locally assigned) EVI (== vlan ID) and the node's router ID.
The RD's assigned by Netlab may require further thought/testing, e.g. in case of multi-homed VLAN bundles with ECMP
Note the minor fixes in case user provided evpn: is ```None```
=> srlinux vlan bundle service take2

netsim/ansible/templates/initial/linux/vanilla.j2
None of the Linux hosts come up in my topology with unnumbered ipv4/ipv6
=> Critical: Filter out the case of ipv4: True in pools

netsim/modules/_dataplane.py, netsim/modules/vlan.py, netsim/modules/vrf.py
Dataplane ID-allocation code has been moved from VLAN module into new _dataplane module. VLAN IDs and VNIs are now allocated using that code, as are the VRF IDs and RDs.
As the next step, the VNI allocation code will be moved in the VXLAN module, and the EVPN module will register static VNIs with the VNI set.
=> Refactor dataplane ID-allocation code (preparing for #509)

netsim/modules/__init__.py
When running with --debug, the reference to l.name sets l.name = {} which is not a string
=> Avoid adding name: {} to links in debug mode

netsim/extra/proxy-arp/plugin.py, netsim/extra/proxy-arp/srlinux.j2, netsim/extra/proxy-arp/sros.j2, tests/integration/evpn/vxlan-symmetric-irb-proxy-arp.yml
Users can set ```proxy_arp: True``` for each VRF where proxy ARP is required
Platforms supported: srlinux, sros
=> Adds a plugin that enables proxy ARP on all interfaces in selected VRFs

netsim/ansible/templates/isis/srlinux.j2
Copy interface naming logic from ospf
=> Fix ISIS template (broken after vlan updates, interface naming logic)

netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/bgp/sros.gnmi.macro.j2
1. If both ipv4 and ipv6 peering addresses are given, activate ipv4 for v4 and ipv6 for v6 (not both for both)
2. If only ipv6 is given, allow ipv4 to be activated too (if enabled by Netlab flag)
The data model only provides
```
activate:
ipv4: True/False
ipv6: True/False
```
and does not specify which one(s) apply to which peering session
=> srlinux/sros: Cleanup address families enabled for BGP sessions:

netsim/ansible/templates/bgp/srlinux.macro.j2
Need to leave next hops unchanged. On SR Linux, next-hop-self also affects reflected routes
=> srlinux: Don't configure next-hop-self when acting as RR

netsim/ansible/templates/bgp/sros.gnmi.macro.j2, netsim/ansible/templates/bgp/sros.j2, netsim/ansible/templates/evpn/sros.j2
Similar to EOS https://github.com/ipspace/netlab/issues/491, on SR OS ```next-hop-self``` affects all routes - including reflected ones
This PR adds a policy to enable next-hop-self on export, but only for EBGP routes.
Note: the 'next-hop-unchanged' config for evpn is probably not strictly needed when using the ebgp-only policy, but it shouldn't hurt
=> sros: Add policy to set next-hop-self for eBGP routes only

netsim/ansible/templates/bgp/srlinux.macro.j2
Ansible doesn't like unquoted strings that contain ':' characters...
=> srlinux: fix static routes with ipv6 prefixes

netsim/modules/evpn.py
Due to register_static_transit_vni being called by module_pre_transform, the transit VNIs are already in the vni list. Any duplication should now be detected when the l2 vni is added (with a little help from my second commit)
=> (dev-1.4) Move check for duplicate L2 VNI to register_static_transit_vni

netsim/modules/vlan.py, netsim/topology-defaults.yml, tests/topology/expected/bgp-vrf-local-as.yml, tests/topology/expected/group-data-vlan.yml, tests/topology/expected/rt-vlan-native-routed.yml, tests/topology/expected/rt-vlan-no-gateway.yml, tests/topology/expected/rt-vlan-role-unnumbered.yml, tests/topology/expected/vlan-access-neighbors.yml, tests/topology/expected/vlan-access-node.yml, tests/topology/expected/vlan-access-single.yml, tests/topology/expected/vlan-bridge-trunk-router.yml, tests/topology/expected/vlan-coverage.yml, tests/topology/expected/vlan-native-routed.yml, tests/topology/expected/vlan-routed-access.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vlan-routed.yml, tests/topology/expected/vlan-router-stick.yml, tests/topology/expected/vlan-trunk-native.yml, tests/topology/expected/vlan-vrf-lite.yml, tests/topology/expected/vrf-leaking-loop.yml, tests/topology/expected/vxlan-static.yml
Fix requires adding 'mode' to no_propagate list, else the global vlan.mode default 'irb' gets copied into every node.
None of the templates reference vlan.mode in the output data, so this should not affect generated device configurations
=> Fix vlan mode precedence to match documentation

docs/labs/clab.md, netsim/templates/provider/clab/clab.j2, netsim/topology-defaults.yml, tests/topology/expected/device-node-defaults.yml
Context: https://github.com/ipspace/netlab/issues/586
Configuration did support multiple runtimes, but feature was undocumented and directly under the node while being a Containerlab specific setting
* Move node.runtime -> node.clab.runtime
* Add defaults.providers.clab.runtime = docker, always set 'runtime' config in clab.yml
* Add documentation
=> Change node.runtime to node.clab.runtime, add documentation

docs/labs/ceos.md, docs/labs/eos.md
Closes issue #580
Adds eos-downloaded to vEOS and cEOS documentation.
Thanks to @titom73 for making the package!
=> add eos-downloader info to docs

netsim/ansible/templates/vxlan/sros.j2
=> Critical: sros - put 'routes' under bgp-evpn context

docs/groups.md, docs/release/1.4.md, netsim/augment/groups.py, netsim/cli/__init__.py, netsim/modules/__init__.py, netsim/topology-defaults.yml, tests/errors/group-invalid-config.yml, tests/topology/expected/groups-hierarchy.yml, tests/topology/input/bgp-autogroup.yml, tests/topology/input/group-data-vlan.yml, tests/topology/input/group-data-vrf.yml, tests/topology/input/groups-hierarchy.yml
Also:
* Allow node attributes in group definitions (node_data is optional)
* Cleanup the remains of 'check_module_parameters' code (no longer needed, all validation is done elsewhere)
Note:
* 'node_data' is still used internally
=> Validate groups and node_data with the new validation routines

docs/dev/transform.md, docs/groups.md, docs/release/1.4.md, netsim/augment/groups.py, netsim/augment/main.py, netsim/data/validate.py, netsim/modules/__init__.py, netsim/modules/bgp.py, netsim/modules/vlan.py, tests/topology/expected/groups-hierarchy.yml, tests/topology/expected/groups-node-data.yml, tests/topology/input/groups-node-data.yml
* Process **bgp.as_list** as part of group initialization
* Create BGP auto-groups as part of group initialization
* Do a two-pass copy of group data into node data -- first for static group members, then for BGP auto-groups
* Simplify merging of group data into node data -- use Box merge and replace node data in topology.nodes
Also:
* Allow 'id' and 'vni' parameters in node 'vlans' as long as they match global values
(needed for static id/vni values for vlans defined in groups)
* Introduce 'crash' parameter to validation routines to trigger an exception
(needed when a validation error should result in a different action in the calling routine)
* Update 'breaking changes' and 'data transformation' documentation
* Add common 'list_of_module' function into 'modules'
(will eventually fix …
=> Resolve circular dependency between groups and BGP module

netsim/ansible/templates/evpn/srlinux.j2
evpn.vlans contains the names of vlans, not their attributes
=> srlinux: Fix iteration over vlans

netsim/extra/proxy-arp/plugin.py
Now that attribute checks have become more strict, we need to play along
=> Explicitly enable 'proxy_arp' attribute for vrfs

netsim/topology-defaults.yml, tests/topology/expected/evpn-hub-spoke.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vxlan-router-stick.yml
Tested using ```netlab up -d frr -p clab tests/integration/evpn/vxlan-routing-ibgp-over-ebgp-unnumbered.yml```
=> Default to new frr 8.4.0

docs/module/isis.md, netsim/quirks/asav.py
I have added a quirk as suggested in #635.
Furthermore while testing I have discovered that `type: lan` on those links has no impact on the generation of the `isis.network_type` Variable.
As far as I can see the code which adds the problematic attribute only looks for the number of neighbors but not for the link type: https://github.com/ipspace/netlab/blob/dev/netsim/modules/_routing.py#L77
Therefore I have removed the hint in the documentation.
=> Add Cisco ASA quirk

docs/module/evpn.md, netsim/modules/evpn.py, netsim/topology-defaults.yml, tests/integration/evpn/vxlan-vlan-bundle.yml, tests/topology/expected/evpn-asymmetric-irb-ospf.yml, tests/topology/input/evpn-asymmetric-irb-ospf.yml
* Add 'evpn.bundle' VRF parameter
* Validate 'evpn.bundle' value against evpn.attributes.bundle list
* Check 'evpn.bundle' value against device.features.evpn.bundle list
* Refactor VLAN bundle code in EVPN configuration module
* Fix EVPN VLAN bundle integration test case
* Add 'evpn.bundle' to EVPN asymmetric IRB test case
* Update the documentation
Implements #636
=> Add support for all EVPN bundle services

.github/workflows/tests.yml, requirements.txt, setup.py
Upgrade to minimum supported 3.8 version because 3.7 requires typing-extensions for typing.Final and refactoring of imports, could be supported if needed but to me a range of 4 supported Python versions is pretty good
(if anybody was using Python 3.7, Netlab wasn't working for them anyway - so merely documenting and verifying what was already the case)
=> Check full range of Python versions 3.8 through 3.11.0, in parallel (upgrade minimum Python version to 3.8)

netsim/install/ansible.sh
After hours of debugging I figured out that paramiko causes authentication problems with Cisco IOSv and ASAv devices.
According to the IOS log, the username in the authentication request is empty.
Therefore I would recommend installing ansible-pylibssh which works fine with these devices.
=> install ansible-pylibssh to fix connection issues with Cisco IOS and ASA

docs/caveats.md, docs/platforms.md, netsim/ansible/collect-configs.ansible, netsim/ansible/config.ansible, netsim/ansible/create-config.ansible, netsim/ansible/initial-config.ansible, netsim/ansible/tasks/create-config.yml, netsim/ansible/tasks/create-custom-config.yml, netsim/ansible/tasks/deploy-custom-config.yml, netsim/ansible/tasks/deploy-module.yml, netsim/ansible/tasks/vmx/initial.yml, netsim/outputs/ansible.py, netsim/topology-defaults.yml, tests/integration/platform/vmx-clab.yml
As per #668 
Specific device types "children" of a vendor can be supported (in this case, vmx is configurable using junos templates and tasks, apart from the initial stuff) - but this can be generic, of course.
=> Initial support for Juniper vMX plus "specific" device types

netsim/augment/links.py, netsim/modules/vlan.py, netsim/topology-defaults.yml, tests/topology/expected/anycast-gateway.yml, tests/topology/expected/rt-vlan-anycast.yml, tests/topology/input/rt-vlan-anycast.yml
The 'gateway' and 'vlan' modules incorrectly assumed that L3 switches connected to a VLAN consistently use the 'gateway' module. When that's not the case, the host default gateway is set to a switch IP address, not to the FHRP IP address.
This commit:
* Copies gateway data from links to interfaces of switches using the 'gateway' module
* Survives 'gateway: True' on links where no attached nodes are using the 'gateway' module
* Prefers 'gateway.ipv4' on a VLAN over a switch IPv4 address when fixing VLAN first-hop gateways
=> Set correct first-hop gateway on VLANs with partial FHRP support (fix #671)

netsim/install/libvirt.sh, netsim/templates/provider/libvirt/nxos-domain.j2
* Replace the plugin version in installation script and remove the workaround
* Tweak NXOS template until Nexus 9300v boots
=> Use vagrant-libvirt plugin version 0.11.2 (fixes #667)

netsim/modules/bfd.py, netsim/modules/eigrp.py, netsim/modules/isis.py, netsim/modules/ospf.py, tests/topology/expected/isis-bfd-test.yml, tests/topology/expected/ospf-bfd-test.yml, tests/topology/input/isis-bfd-test.yml, tests/topology/input/ospf-bfd-test.yml
The sequence of operations used in IGP modules resulted in igp.bfd being set on an interface even when the IGP itself was disabled with 'igp: false'. This commit fixes #679:
* Changes the BFD IGP code to skip interfaces with IGP disabled
* Disables IGP BFD status if the node is not using BFD module
* Evaluates BFD state early in IGP data transformation to ensure the 'igp: false' flag is not lost
Other fixes:
* Moved OSPF and IS-IS unnumbered processing into a function to make the code more readable
* Fix EIGRP code (it was passing OSPF or IS-IS as parameters to _routing functions)
=> IGP BFD status should not be present on interfaces without IGP

docs/platforms.md, netsim/ansible/tasks/deploy-config/vyos.yml, netsim/topology-defaults.yml
We can't use the official 1.3-epa2 image from Docker Hub because it's outdated and doesn't work correctly with virtual network devices [1]. The thing is critical for the container environment with veth devices. Hence for now we can use the unofficial image [2] that is based on VyOS nightly ISO.
1. https://github.com/vyos/vyos-1x/commit/8cf5a4f023c5459cad4c84e93f73a9ddd69be81a
2. https://github.com/sysoleg/vyos-container
=> Add support for containerized VyOS.

netsim/ansible/templates/ospf/frr.ospfv2.j2, netsim/ansible/templates/vrf/frr.ospfv2-vrf.j2
"passive-interface IFNAME" is deprecated and emits warning [1].
1. https://github.com/FRRouting/frr/commit/3eec4ee0773786b7ba366bc7499ed6bbd28fdf79
=> FRR: use "ip ospf passive"

netsim/ansible/templates/vrf/frr.j2
VRF enslavement leads to link flap. Linux kernel doesn't keep IPv6 address by default in this case. keep_addr_on_down sysctl knob fix this behavior.
=> FRR: don't lose interface IPv6 address after VRF enslavement

docs/labs/libvirt.md, netsim/cli/external_commands.py, netsim/cli/up.py, netsim/providers/libvirt.py, tests/integration/vagrant-batches/topology.yml
Documentation @ docs/labs/libvirt.md
@petercrocker This one is based on the discussions we had about Vagrant DHCP failures. Could you please test it out on one of your large topologies (please note that this is a parallel branch to the `multilab` one, so you can't use both features in parallel while testing it ;)
=> Split large topology into smaller 'vagrant up' batches (fixes #732)

docs/labs/clab.md, netsim/ansible/tasks/deploy-config/srlinux.yml
Containerlab 0.37 introduced a change to the path location of generated CA files.
A breaking change - this PR fixes it, and calls out the minimum required version (easy to upgrade)
=> Update CA file path to match latest Containerlab changes

netsim/ansible/tasks/deploy-config/srlinux.yml
inventory_dir | basename happens to work when the lab is in the same directory, but...
=> Correct clab directory name for labs in sub-directories

docs/install/ubuntu-vm.md
As per https://stackoverflow.com/questions/71851185/unable-to-install-uninstall-with-pip-due-to-cryptographydeprecationwarning it is required to install cryptography version 3.3.2 on Ubuntu 20.04 before running the netlab install command
Tested on multipass Ubuntu 20.04
=> Missing pip install step on Ubuntu 20.04

netsim/devices/asav.yml, netsim/install/libvirt/asav.txt, netsim/install/libvirt/asav/day0-config
In newer version ASAv enforces a minimum password length of 8.
Therefore I have changed the default password to match this criteria.
Users have to rebuild old vagrant boxes to be able to work with them after this change.
=> Change default password for ASAv

netsim/ansible/templates/vrf/sros.j2
Template implicitly assumed bgp module was being used, it may not be
Note that we may want to simplify the router_id modeling to a single, global attribute per node - instead of per protocol, vrf, etc. There is bgp.router_id, ospf.router_id, etc. but in the typical case each router has a single unique ID
=> Remove dependency on bgp module

docs/labs/clab.md, netsim/data/filemaps.py, netsim/providers/__init__.py, netsim/providers/clab.py, netsim/templates/provider/clab/clab.j2, tests/topology/expected/components.yml, tests/topology/expected/device-node-defaults.yml, tests/topology/expected/evpn-hub-spoke.yml, tests/topology/expected/libvirt-clab-complex.yml, tests/topology/expected/vlan-access-links.yml, tests/topology/expected/vlan-access-single.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vxlan-router-stick.yml
The clab.binds and clab.config_templates dictionaries could contain dots in keys (filenames) which results in weird values in clab.yml configuration file. This patch:
* Checks the validity of clab.binds and clab.config_templates parameters
* Converts them into lists of host:target strings
* Converts those strings into dicts and back as needed
=> Deal with Python Box expanding dots in keys read from YAML files

netsim/ansible/templates/vxlan/srlinux.j2
It is possible for a VLAN to be in vxlan.vlans but not in evpn.vlans
=> Check if vlan has evpn enabled

netsim/install/containerlab.sh
New release has backwards compatibility for old mgmt_ipv[x] attributes
=> Update containerlab.sh to release 0.41.2

netsim/augment/groups.py, netsim/modules/vrf.py, tests/topology/expected/evpn-node-vrf.yml, tests/topology/expected/vrf.yml, tests/topology/input/evpn-node-vrf.yml
Some module (like EVPN) modify global VRF data and expect the modified global VRF data to be used for node VRF data. Code introduced in #482 pulls global VRF data into node VRF data very early in the transformation process -- in those cases, the global changes are never copied into the node VRF data.
This PR fixes the #482 logic to create stub node VRF structures, and carefully populates them with auto-generated or global ID/RD/RT values. The full global VRF data is then merged with node VRF data in post_transform hook.
=> Merge global VRF data with node VRF data in post-transform hook

netsim/ansible/templates/evpn/frr.evpn-config.j2, netsim/extra/ebgp.utils/frr.j2
* Enable allowas-in also for ebgp evpn neighbors (l2vpn address family)
* Enable soft-reconfiguration inbound to see/debug incoming routes
(1) was the reason why FRR hosts weren't working in the ebgp topology shared earlier
=> FRR template fixes/enhancements

tests/integration/evpn/ebgp-evpn-allowas_in.yml
Note that there are other ways to forward all EVPN routes between the hosts - RR is only supported for iBGP on some platforms
=> Integration test case for allowas_in in combination with EVPN eBGP

netsim/ansible/templates/vxlan/frr.j2
As suggested [here](https://docs.frrouting.org/en/latest/evpn.html):
* Disable dynamic MAC learning on VXLAN devices when EVPN is used
* Disable auto-generated ipv6 address for vxlan devices
=> Improvements to FRR VXLAN config

MANIFEST.in
ubuntu@libvirt:~$ netlab show
Traceback (most recent call last):
File "/usr/local/bin/netlab", line 8, in <module>
sys.exit(lab_commands())
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/__init__.py", line 256, in lab_commands
mod.run(sys.argv[arg_start:])   # type: ignore
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/show.py", line 85, in run
args = parse_show_args(cli_args)
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/show.py", line 64, in parse_show_args
show_usage()
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/show.py", line 59, in show_usage
print_usage('show-usage.txt')
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/usage.py", line 16, in print_usage
with resources.open_text(package,fname) as fid:
File …
=> MANIFEST.in: missing include for show-usage.txt

docs/nodes.md
Document a working containerlab + sros example. Adds defaults and node specific overrides.
=> Add containerlab example to nodes docs

netsim/extra/ebgp.utils/plugin.py, netsim/extra/ebgp.utils/srlinux.j2, netsim/extra/ebgp.utils/sros.j2
* Configure bgp.tcp_ao=True (or a specific algorithm like 'aes-128-cmac','hmac-sha-1') at global or link level
* SR Linux YANG model supports tcp-ao, but no algorithms yet
=> Add TCP-AO support to the ebgp.utils plugin, plus general SR OS support

netsim/ansible/templates/mpls/sros.ldp.j2, netsim/ansible/templates/mpls/sros.mplsvpn.j2
* Disable IGP LDP sync when requested (enabled by default)
* Add Inter-AS option B peering using VPNv4/v6 family
=> A few minor fixes for SR OS MPLS configs

docs/plugins/ebgp.multihop.md, netsim/ansible/templates/initial/sros.openconfig.j2, netsim/extra/ebgp.multihop/srlinux.j2, netsim/extra/ebgp.multihop/sros.j2
* Docs says VRFs not supported, but templates do include support?
* No support yet for address family activation like the EVPN example
* Templates assume multihop is an integer between 1 and 255
=> Add ebgp.multihop support for SR Linux and SR OS

netsim/augment/devices.py, netsim/extra/bgp.policy/defaults.yml, netsim/extra/bgp.policy/plugin.py, netsim/extra/bgp.policy/srlinux.j2, netsim/extra/ebgp.multihop/srlinux.j2
Creates a single default policy per neighbor to set either MED or local-preference
- unnumbered BGP peers are treated as a group -> all get the same MED or local-pref (sorry)
=> BGP policy support for SR Linux supporting MED and local-pref

docs/plugins/bgp.session.md, netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/srlinux.j2
* BGP timers
* BFD
* remove_private_as ('on', 'all' or 'replace')
* passive
Note: `replace` implies `all` for consistency with other devices, could distinguish `remove_private_as: [ replace, all ]`
=> Extend BGP session support for SR Linux

netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/ospf/sros.j2
Alternative fix for #942 . Moved the naming logic of SROS interfaces to the macro in intial.j2
=> Move Nokia SROS interface naming logic to initial.j2 if_name macro

docs/caveats.md, docs/labs/arubacx.md, docs/module/evpn.md, netsim/ansible/templates/evpn/arubacx.j2, netsim/devices/arubacx.yml
With AOS-CX Virtual release 10.13, we can support VXLAN EVPN L3VNI (Symmetric IRB)
=> AOS-CX: Support for L3VNI (and release 10.13)

docs/module/vxlan.md, netsim/ansible/templates/vxlan/arubacx.j2, netsim/ansible/templates/vxlan/csr.j2, netsim/ansible/templates/vxlan/dellos10.j2, netsim/ansible/templates/vxlan/eos.j2, netsim/ansible/templates/vxlan/nxos.j2, netsim/defaults/attributes.yml, netsim/modules/vxlan.py, netsim/modules/vxlan.yml, tests/topology/expected/evpn-asymmetric-irb-ospf.yml, tests/topology/expected/evpn-vxlan.yml, tests/topology/expected/vxlan-router-stick.yml, tests/topology/expected/vxlan-static.yml, tests/topology/expected/vxlan-vrf-lite.yml
@ipspace This is a proposal to make the VXLAN VTEP source configurable, and not "hardcoded" to loopback 0.
It is based on a custom flag that can be set on an additional loopback interface. In that case, the first loopback interface with the flag will be used as vtep source (interface/address)
If this is ok for you, I will try to add the proper doc.
/cc @jbemmel
=> Proposal: VXLAN configurable VTEP address/interface

docs/dev/config/initial.md, netsim/ansible/templates/initial/cumulus.j2, netsim/ansible/templates/initial/eos.j2, netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/initial/ios.j2, netsim/augment/links.py, netsim/modules/vrf.py, tests/topology/expected/addressing-lan.yml, tests/topology/expected/addressing-p2p.yml, tests/topology/expected/bgp-ibgp.yml, tests/topology/expected/bgp-unnumbered-dual-stack.yml, tests/topology/expected/bgp-unnumbered.yml, tests/topology/expected/igp-af.yml, tests/topology/expected/isis-feature-test.yml, tests/topology/expected/ospf.yml, tests/topology/expected/unnumbered.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vrf-igp.yml, tests/topology/input/vrf-igp.yml
* Set _parent_intf and _parent_ipv4 on unnumbered IPv4 interfaces
* Fix _parent_intf and _parent_ipv4 to point to in-VRF loopback (where available) for in-VRF unnumbered IPv4 interfaces
* Use these attributes when configuring unnumbered interfaces on CSR, EOS, FRR and Cumulus Linux
Please note that we don't need corresponding IPv6 mechanism as IPv6 uses LLA.
Fixes #993, prepares the infrastructure for #1000
=> Add parent interface data to unnumbered interface

docs/netlab/show.md, docs/platforms.md, netsim/ansible/tasks/deploy-module.yml, netsim/augment/devices.py, netsim/augment/nodes.py, netsim/cli/__init__.py, netsim/cli/show_commands/devices.py, netsim/daemons/bird.dockerfile, netsim/daemons/bird.yml, netsim/daemons/bird/bgp.j2, netsim/daemons/bird/bird.j2, netsim/modules/__init__.py, netsim/providers/__init__.py, netsim/providers/clab.py, netsim/topology-defaults.yml
Limitations:
* Includes a minimal implementation of BGP on Bird
* Supports daemons in containers, not in VMs
Changes:
* Include daemons/*.yml configurations into 'daemons:' default key
* Merge 'daemons:' with 'devices:' during device initialization step
* Set _daemon, _daemon_parent and _daemon_config node variables from device data to skip lookups into device data
* Copy topology modules into host modules if the host is a daemon
* Trim _daemon_config node dictionary based on modules active on the node (skips extraneous generation of irrelevant config files later on)
* Merge _daemon_config dictionary into clab.config_template to generate daemon config files as clab.binds
* Consider parent device and daemons directory when generating files from clab.config_templates
* Skip module …
=> Initial implementation of control-plane daemons

docs/netlab/status.md, netsim/cli/__init__.py, netsim/cli/ansible.py, netsim/cli/down.py, netsim/cli/external_commands.py, netsim/cli/initial.py, netsim/cli/status.py, netsim/cli/up.py, netsim/providers/__init__.py, netsim/providers/clab.py, netsim/providers/libvirt.py, netsim/providers/virtualbox.py, netsim/utils/callback.py
* Display workload of current lab instance in tabular format
* Display all running instances in tabular format
* Add CLI options to display log, reset system, or shut down a lab instance
Also:
* Add 'get_lab_status' provider function to retrieve provider-specific workload information
* Add 'get_node_name' provider function to retrieve provider-specific workload name
* Add 'lab_status_log' to add lines to lab log
* Use 'lab_status_log' to log external commands based on external_commands.LOG_COMMANDS variable
* Use external command logging in netlab up/down/initial
* Initialize global topology variable after loading topology or snapshot file
* Use 'external_commands' module to run Ansible playbooks
=> Refactor the "netlab status" printout (fixes #1044)

netsim/ansible/templates/mpls/sros.ldp.j2
To make the BGP free core example work, LDP tunnels must be allowed to get used
=> SROS LDP: Allow BGP next-hop resolution via LDP

netsim/ansible/templates/initial/vyos.j2
Fixes #1064 
```
[ping]    IPv4 ping H1 => H2 [ node(s): h1 ]
[PASS]    h1: Ping to h2 succeeded
[PASS]    Test succeeded
[pmtud]   ICMP DF error when pinging H2 => H1 (succeeds once) [ node(s): h2 ]
[PASS]    h2: Ping to h1 size 1400 failed as expected
[PASS]    Test succeeded
[mtud]    H2 => H1 MTU discovered [ node(s): h2 ]
[PASS]    h2: Ping to h1 size 1400 succeeded
[PASS]    Test succeeded
[ra]      Check RA-generated default route [ node(s): h1,h2 ]
[PASS]    h1: IPv6 default route is present
[PASS]    h2: IPv6 default route is present
[PASS]    Test succeeded
[ping6]   IPv6 ping H1 => H2 [ node(s): h1 ]
[PASS]    h1: Ping to ipv6 2001:db8:1:1::3 succeeded
[PASS]    Test succeeded
[SUCCESS] Tests passed: 6
```
=> VyOS: support for sending IPv6 RA

netsim/ansible/templates/bgp/vyos.j2
Fixes #1063 
```
[ospf_adj_dut] Check OSPF adjacencies with DUT [ node(s): r1 ]
[WAITING]      Waiting for OSPF adjacency process to complete (retrying for 40 seconds)
[PASS]         Validation succeeded on r1
[PASS]         Succeeded in 5.2 seconds
[PASS]         Test succeeded
[ospf_adj_r1]  Check OSPF adjacencies with R1 [ node(s): r2,rr2 ]
[PASS]         Validation succeeded on r2
[PASS]         Validation succeeded on rr2
[PASS]         Test succeeded
[session]      Check BGP sessions with DUT [ node(s): r1,r2,rr2,x1 ]
[PASS]         x1: Neighbor 10.1.0.13 (dut) is in state Established
[WAITING]      Wait for BGP sessions to be established (retrying for 30 seconds)
[PASS]         rr2: Neighbor 10.0.0.1 (dut) is in state Established
[PASS]         r1: Neighbor 10.0.0.1 (dut) is in …
```
=> VyOS: add cluster-id in rr config

netsim/ansible/templates/bgp/vyos.macro.j2
Fixes #1079 
**NOTE**: only `standard` and `extended` values allowed (for now).
```
[session]      Check BGP sessions with DUT [ node(s): rc,r2,x1 ]
[PASS]         rc: Neighbor 10.0.0.1 (dut) is in state Established
[PASS]         r2: Neighbor 10.0.0.1 (dut) is in state Established
[PASS]         x1: Neighbor 10.1.0.9 (dut) is in state Established
[PASS]         Test succeeded
[prefix]       Check whether DUT propagates the beacon prefix [ node(s): r2,x1 ]
[PASS]         r2: The prefix 172.0.42.0/24 is in the BGP table
[PASS]         x1: The prefix 172.0.42.0/24 is in the BGP table
[PASS]         Test succeeded
[ibgp_comm]    Check community propagation on IBGP sessions [ node(s): r2 ]
[PASS]         r2: The prefix 172.0.42.0/24 contains the expected communities
[PASS]         Test …
```
=> VyOS: controlled community propagation

netsim/ansible/templates/bgp/srlinux.macro.j2
The config has a 'community' array at the global level, not per VRF
=> Fix bgp communities inside VRFs

netsim/ansible/templates/evpn/dellos10.j2, netsim/ansible/templates/gateway/dellos10.j2, netsim/ansible/templates/vrf/dellos10.bgp.j2, netsim/ansible/templates/vrf/vyos.j2
++ bonus point: do not fail on vyos template if `vrfs` is not defined (see #1104 )
=> OS10: Improvements/Fixes on EVPN+BGP+IPv6

netsim/ansible/templates/evpn/srlinux.j2, tests/integration/evpn/vxlan-asymmetric-irb-ospf.yml
In the asymmetric irb case, vrf.evpn is not defined
Adds a validation test that allowed me to identify this issue
=> Fix srlinux asymmetric irb evpn, add validation for integration test

netsim/ansible/templates/isis/sros.j2
VLANs with mode=irb are created in the 'default' VPRN service, not the base routing context.
Consequently, IS-IS interfaces in such VLANs must be configured in the correct context
=> SR-OS Instantiate IS-IS in the correct context

netsim/install/libvirt/arubacx.txt
It seems that Aruba CX 10.13 consistently messes up startup configuration on first reboot. Changed the box-building recipe to reboot the device first, then apply the desired configuraton.
Fixes #1117
=> Doc fix: Aruba CX box-building recipe

docs/labs/dellos10.md, netsim/ansible/tasks/deploy-config/dellos10.yml
* It looks like OS10 requires dellemc.os10 Ansible collection to work. Added that information to the box-building instructions
* The 'dellos10.yml' configuration deployment task failed for me. It looks like the newer versions of the dellemc.os10 Ansible collection expect a filename, not the actual commands, as the parameter to dellemc.os10.os10_config.
=> Fix Dell OS10 Ansible-related information

docs/labs/routeros7.md, netsim/install/libvirt/routeros7.txt, netsim/templates/provider/libvirt/routeros7-domain.j2
netlab is using admin/admin username/password to access RouterOS7 devices. There's no need to add 'vagrant' user to the initial configuration or copy Vagrant key to the device.
=> Simplify RouterOS7 box building process

docs/labs/dellos10.md, netsim/cli/libvirt_actions/package.py, netsim/devices/dellos10.yml, netsim/install/libvirt/dellos10/run.sh
Trying to simplify the OS10 box building process, I added a simple preinstall hook that copies installation- and platform disks to the build directory.
=> Add box preinstall hook that copies extra Dell OS10 files to build directory

netsim/ansible/templates/bgp/dellos10.j2
Apparently, with newer OS10 ansible collection, it's required to explicitly exit the bgp template stanza before running other commands.
=> Dell OS10: fix on bgp template definition

netsim/templates/provider/libvirt/dellos10-domain.j2
I think two minutes should be enough for a recent OS10 to boot, and it would reduce the wasted time in automated tests when the SSH server does not start.
=> Reduce the Dell OS10 boot waiting time to two minutes

netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/vrf/srlinux.j2, netsim/devices/srlinux.yml
Fixes https://github.com/ipspace/netlab/issues/1074
Note that integration tests 31-34 with common VRF fail; SR Linux currently supports route leaking based on prefix filters, but not communities
=> Fix SR Linux VRF BGP import/export policies

netsim/ansible/templates/bgp/srlinux.macro.j2
Fixes https://github.com/ipspace/netlab/issues/1071
=> SR Linux allow activation of bgp ipv4 af over ipv6 session and vice versa

netsim/ansible/templates/initial/srlinux.j2, netsim/devices/srlinux.yml
Requires release 24.3.1 or above
=> Fix SR Linux IS-IS over ipv4 unnumbered interfaces

netsim/devices/dellos10.py
This fixes two "configuration failed" OS10 VXLAN test results
=> Quirk: OS10 cannot run OSPF on SVI interfaces

netsim/ansible/templates/initial/dellos10.j2
Fix #1153
```
[WARNING] Initial wait time extended by 30 seconds required by dellos10
[red]     Ping-based reachability test in VRF red [ node(s): h1 ]
[PASS]    h1: Ping to ipv6 h2 succeeded
[PASS]    Test succeeded
[ping]    Ping-based reachability test in VRF blue [ node(s): h3 ]
[PASS]    h3: Ping to ipv6 h4 succeeded
[PASS]    Test succeeded
[red_lb]  Pinging red VRF IPv6 loopback [ node(s): h1 ]
[PASS]    h1: Ping to ipv6 2001:db8:c001:cafe::1 succeeded
[PASS]    Test succeeded
[blue_lb] Pinging blue VRF IPv6 loopback [ node(s): h3 ]
[PASS]    h3: Ping to ipv6 2001:db8:c001:cafe::1 succeeded
[PASS]    Test succeeded
[SUCCESS] Tests passed: 4
```
=> Dell OS10: do not set IPv6 ND on loopbacks

netsim/ansible/templates/bgp/dellos10.j2
should fix #1154
On the worst case, we can call another time the `router bgp XXX` to "restart" from the main bgp context.
=> Dell OS10: update command indent on bgp

netsim/devices/arubacx.yml
fix #1146 ... not a real fix, since this was not supported from the beginning...
=> ArubaCX: local-as is not supported for iBGP

netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/routeros7.j2
* Fix #1151 (stupid typo)
* Add support for remove-private-as
Test for **bgp.session-08** (*remove-private-as*):
```
bgpse08# netlab validate
[session_v4]     Check IPv4 EBGP sessions with DUT [ node(s): x1,x2 ]
[PASS]           x1: Neighbor 172.16.0.1 (dut) is in state Established
[PASS]           x2: Neighbor 172.16.1.1 (dut) is in state Established
[PASS]           Test succeeded
[session_v6]     Check IPv6 EBGP sessions with DUT [ node(s): x1,x2 ]
[PASS]           x1: Neighbor 2001:db8:4::1 (dut) is in state Established
[PASS]           x2: Neighbor 2001:db8:4:1::1 (dut) is in state Established
[PASS]           Test succeeded
[pfx_x2_v4]      Check for X1 IPv4 prefix on X2 [ node(s): x2 ]
[PASS]           x2: The prefix 172.42.42.0/24 is in the BGP table
[PASS]           Test …
```
=> ROS7: update for bgp.session

netsim/ansible/templates/initial/srlinux.j2
Also add a few more platforms to the MTU max length check
=> Cannot configure L2 MTU on IXR-H platforms

docs/module/ospf.md, netsim/devices/srlinux.yml
fixes test ospfv2/05-unnumbered.yml
=> SR Linux can now support OSPF over unnumbered ipv4 interfaces

netsim/extra/bgp.session/srlinux.j2
current implementation rejects AS_PATH containing >= allow-own-as instances, somewhat counterintuitively
=> Add +1 to allow-own-as value

netsim/ansible/templates/bgp/srlinux.macro.j2
* Set local transport address at neighbor level (ibgp neighbor implies loopback address by default)
=> srlinux: Fix ibgp localas test case

docs/caveats.md, netsim/devices/srlinux.py
Test case 05 filters extended communities from EBGP - SR Linux only supports filtering standard or large communities
=> srlinux: Add quirk to warn about extended communities not being filtered

netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/srlinux.macro.j2
Fixes https://github.com/ipspace/netlab/issues/1068
This uses 3rd party next hop set to self (loopback).
=> SR Linux: Fix use case 3 and 13 with next hop self override for EBGP routes received from peers

netsim/ansible/tasks/frr/initial-clab.yml, netsim/ansible/templates/initial/frr.j2
Fixes https://github.com/ipspace/netlab/issues/1209
=> FRR: Load VRF kernel module upon initial startup, disable use of vrfs when not available

docs/plugins/bgp.policy.md, netsim/extra/bgp.policy/defaults.yml, netsim/extra/bgp.policy/plugin.py, netsim/extra/bgp.policy/sros.j2, tests/integration/bgp.policy/10-bgp-bandwidth-auto.yml
* Enable extended communities for EBGP inside the plugin, for all platforms
* Also adds MED and localpref
=> Implement bgp bandwidth auto for SR OS

docs/addressing.md, docs/prefix.md, docs/topology-reference.md, netsim/augment/addressing.py, netsim/augment/links.py, netsim/data/types.py, netsim/defaults/attributes.yml, tests/errors/prefix-exclusive-attribute.log, tests/errors/prefix-exclusive-attribute.yml, tests/topology/expected/addressing-prefix.yml, tests/topology/input/addressing-prefix.yml
This PR implements 'named prefixes' -- a dictionary of prefixes that can be used in 'links.prefix', 'vlans.prefix', validation code, and (future) prefix lists.
The named prefixes can be static (ipv4 and/or ipv6 subnets, optionally with allocation mechanism) or allocation from one of the addressing pools, in which case the named prefix serves as a mechanism to prevent data duplication
=> Implement named prefixes for use in validation and prefix lists

docs/module/routing.md, netsim/ansible/templates/routing/_route_map_ios.j2, netsim/ansible/templates/routing/_route_policy_vyos.j2, netsim/ansible/templates/routing/arubacx.j2, netsim/ansible/templates/routing/vyos.j2, netsim/devices/arubacx.yml, netsim/devices/vyos.yml
(Tested backward compat for the `as-path keyword` with FRR)
=> AOS-CX+VYOS: route-map match as-path

.devcontainer/Dockerfile
Closes #1261 
Install the apt package `linux-headers-generic` in the devcontainer enabling to start the VyOS container "ghcr.io/sysoleg/vyos-container:latest"
=> Add linux-headers-generic to devcontainer

docs/labs/clab.md, netsim/providers/clab.yml
Supporting set of https://containerlab.dev/manual/nodes/#startup-delay
=> clab: support for node parameter startup-delay

netsim/ansible/templates/initial/vyos.j2
... this will allow Graphite to log into it.
thanks to @ubaumann.
=> VyOS: enable SSH service when running in containerlab

netsim/ansible/templates/vrf/arubacx.bgp.j2
tested with https://github.com/ipspace/netlab/blob/dev/tests/integration/vrf/23-multi-vrf-mixed-ipv6.yml
and also with https://github.com/ipspace/netlab/blob/dev/tests/integration/vrf/15-multi-vrf-mixed.yml for backward compatibility
=> ArubaCX Fix: redistribute ospfv3 as well if present

docs/module/bgp.md, docs/module/ospf.md, netsim/ansible/templates/bgp/arubacx.j2, netsim/ansible/templates/bgp/vyos.j2, netsim/ansible/templates/ospf/arubacx.ospfv2.j2, netsim/ansible/templates/ospf/arubacx.ospfv3.j2, netsim/ansible/templates/ospf/vyos.ospfv2.j2, netsim/ansible/templates/ospf/vyos.ospfv3.j2, netsim/ansible/templates/vrf/arubacx.bgp.j2, netsim/ansible/templates/vrf/vyos.bgp.j2, netsim/devices/arubacx.yml, netsim/devices/vyos.yml, netsim/modules/bgp.yml, netsim/modules/ospf.yml, tests/topology/expected/rp-aspath-numbers.yml
includes forced config order, for configuring routing before bgp and ospf
testing:
**Aruba CX**
**VyOS**
=> Routing import for AOS-CX and VyOS

docs/caveats.md, docs/module/ospf.md, docs/module/vrf.md, netsim/ansible/templates/initial/vyos.j2, netsim/ansible/templates/ospf/arubacx.ospfv2.j2, netsim/ansible/templates/ospf/arubacx.ospfv3.j2, netsim/ansible/templates/ospf/vyos.default.j2, netsim/ansible/templates/ospf/vyos.ospfv2.j2, netsim/ansible/templates/ospf/vyos.ospfv3.j2, netsim/ansible/templates/vrf/arubacx.ospfv2-vrf.j2, netsim/ansible/templates/vrf/arubacx.ospfv3-vrf.j2, netsim/ansible/templates/vrf/vyos.default.j2, netsim/ansible/templates/vrf/vyos.j2, netsim/ansible/templates/vrf/vyos.ospfv2-vrf.j2, netsim/ansible/templates/vrf/vyos.ospfv3-vrf.j2, netsim/devices/arubacx.py, netsim/devices/arubacx.yml, netsim/devices/vyos.yml
ArubaCX + VyOS OSPF/v3 default originate
++ bonus: Support for OSPFv3 in VRF for VyOS
**Testing caveats for ospfv2/20-default.yml**
- ArubaCX allows to generate the default only as `E2` - the test is failing for the wrong metric received from `dut_c` --> created device quirk for removing `metric-type` from ospf struct
- VyOS does not have a management VRF; a default route is always present on the main routing table - hence, test is failing because the probe always receive the E1 route announced by `dut_c` (which shall announce the default only if present) --> documented in `caveats.md`
=> ArubaCX + VyOS OSPF/v3 default originate + bonus

docs/module/bgp.md, docs/module/ospf.md, netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/ospf/srlinux.j2, netsim/ansible/templates/ospf/srlinux.macro.j2, netsim/ansible/templates/vrf/srlinux.j2, netsim/devices/srlinux.yml, netsim/extra/bgp.policy/srlinux.j2, tests/integration/bgp.policy/31-med.yml, tests/integration/bgp.session/04-default-originate.yml
Adds SR Linux support for unconditional route import into BGP and OSPF. Also, creates chains for BGP import/export policies so the per-neighbor routing policy works correctly (as opposed to dumping the whole RIB to the neighbor)
=> SR Linux: route import (redistribution) into OSPF and BGP

netsim/ansible/templates/ospf/srlinux.macro.j2, netsim/devices/srlinux.yml, tests/integration/ospf/ospfv2/20-default.yml, tests/integration/ospf/ospfv3/20-default.yml
Another feature not yet supported in SR Linux netlab templates: OSPF default route. Validation tests pass, although with warnings as it's impossible to set OSPF metric or OSPF metric type on SR Linux routes exported into OSPFv2/OSPFv3
=> SR Linux: Implement OSPF default route

netsim/ansible/templates/bgp/srlinux.macro.j2, tests/integration/bgp/03-ibgp-rr.yml
SR Linux needs an export to set next-hop to "self" on EBGP routes but not on reflected IBGP routes.
The original template created two per-AF export policies and set the BGP next hop to the IP address
of the loopback interface.
With the new "action.bgp.next-hop: self" option, we can simplify that into a single route map that does
not depend on IP addresses or address families.
Last but not least, we're removing the internal BGP communities used to mark IBGP routes.
=> SR Linux: Simplify the IBGP export policy with the new 'next-hop: self' action

docs/module/isis.md, netsim/ansible/templates/isis/srlinux.j2, netsim/devices/srlinux.py
SR Linux 24.7 has IS-IS multi-topology for IPv6. It would be a shame not to use it ;)
=> SR Linux: Enable IS-IS IPv6 multi-topology

docs/caveats.md, docs/module/sr-mpls.md, netsim/devices/dellos10.yml, netsim/devices/srlinux.py, netsim/templates/provider/libvirt/dellos10-domain.j2
Trying to implement the "Principle of Least Astonishment", netlab checks whether you have the necessary license to
run IXR6/IXR10 containers. 
https://containerlab.dev/manual/kinds/srl/#types
Figuring out why those containers are crashing is an experience I wouldn't recommend to anyone.
=> SR Linux: Check for the license needed to run IXR6/IXR10 containers

docs/labs/linux.md, docs/platforms.md, netsim/ansible/templates/initial/cumulus.j2, netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/initial/linux.j2, netsim/ansible/templates/initial/linux/hosts-common.j2, netsim/ansible/templates/initial/linux/hosts.j2, netsim/ansible/templates/initial/linux/ubuntu.j2, netsim/devices/cumulus.yml, netsim/outputs/ansible.py, netsim/templates/provider/clab/cumulus/hosts-common.j2, netsim/templates/provider/clab/frr/hosts-common.j2, netsim/templates/provider/clab/linux/hosts-common.j2, netsim/templates/provider/clab/linux/hosts.j2, tests/topology/expected/bgp-unnumbered.yml, tests/topology/expected/device-node-defaults.yml
The hosts file handling is done exclusively in the 'linux/hosts.j2' template with the contents being generated in the 'linux/hosts-common.j2' template.
These templates are used in CL, FRR, and Linux initial configuration templates as well as (using symlinks) in the hosts.j2 templates used to generate clab_files that are mapped into the container /etc/hosts files.
The content-generation template has been rewritten from scratch (the previous one generated invalid file format) and can be controlled with the 'netlab_intf_hosts' variable to generate hostnames that include interface names.
=> Unify /etc/hosts file handling across CL,FRR and Linux VMs and containers

docs/install/linux.md
Add Host Networking Caveats section in documentation, linux.md. Document possible solutions for multi-access links not passing layer3 traffic.
=> [DOC] Add Host Networking Caveats doc section. 

netsim/providers/__init__.py, netsim/templates/provider/clab/cumulus/interfaces.j2
ssh to Cumulus nodes is currently broken due to the implied /32 prefix
It might be more elegant to fix this by normalizing ```mgmt.ipv4``` to include the prefix, and then removing it everywhere else.
It could also be considered to condition the use of the mgmt vrf on ```netlab_mgmt_vrf``` like done for FRR
=> Fix Cumulus mgmt ip prefix

netsim/templates/provider/clab/cumulus/interfaces.j2
This route is used for things like DNS and NTP
=> Add default route to mgmt

netsim/augment/links.py, tests/topology/expected/vlan-vrrp.yml, tests/topology/input/vlan-vrrp.yml
The link prefix processing was also setting the link gateway ID which broke the creation of VLANs with specified gateway.id because the VLAN module assigns prefixes to VLANs before the nodes are attached to the virtual VLAN links.
This fix splits the prefix processing from the propagation of gateway IP, allowing the 'gateway.id' attribute to be specified on a VLAN.
Please note that while this fix works, it's still affected by #1351
=> Split processing of link prefix and gateway data

netsim/modules/vlan.py, netsim/modules/vlan.yml, tests/topology/expected/vlan-vrrp.yml, tests/topology/input/vlan-vrrp.yml
The VLAN module did not copy gateway.* items specified in the global or node VLAN data to prevent 'gateway: true' overwriting the data computed through the gateway module transformation and subsequent link transformation.
With a perfect hindsight, that was wrong. This fix:
* Removes the 'do not copy gateway.* items' restriction
* Changes the 'merge interface data with node vlan data' logic to say 'if the VLAN data is True and the interface data exists, use the interface data'
The first change fixes the 'vlan-vrrp' test case. The second change keeps 'anycast-gateway' test case working.
=> Use node-level VLAN gateway data on SVI interfaces (fixes #1349)

.github/workflows/tests.yml, setup.py
Python 3.13 was released 3 days ago - include it in CI/CD testing, and remove the now-deprecated 3.8 version from testing
=> Add python 3.13, remove end-of-support 3.8

docs/conf.py, docs/module/gateway.md, netsim/modules/gateway.py, tests/errors/anycast-params.log, tests/errors/anycast-prefix.log, tests/errors/gateway-global-params.log, tests/topology/expected/vlan-vrrp.yml, tests/topology/input/vlan-vrrp.yml
Fixes the easier part of #1351
=> Fix: Reserve gateway.id parameters specified on links and global VLANs

netsim/devices/ioll2.py, netsim/devices/iosvl2.py
Symlink Cisco iosvl2 quirks as quirk module for ioll2 devices. Update error message to mention both devices. Even if vlan module is disabled for now on ioll2, do this change now so it is done and present for future development on ioll2.
=> Symlink Cisco iosvl2 quirks for ioll2 images. Update error message

netsim/data/filemaps.py
Fixes https://github.com/ipspace/netlab/issues/1402 by limiting split on ':' to at most 2 parts
=> Allow for ':' in values of binds dict

README.md, docs/cli-overview.md, docs/index.md, docs/netlab/cli.md, docs/netlab/exec.md, netsim/cli/connect.py, netsim/cli/exec.py, netsim/cli/validate.py
Synposis:
netlab exec [-h] [-v] [-q] [--dry-run] [--snapshot [SNAPSHOT]]
node
The rest of the arguments are passed to SSH or docker exec command.
Let my people go execing!
This is a draft pull request. It misses cosmetics and documentation.
It is also the first line of python I wrote in my life. So more merciless your review is it,  the better for me to learn this language.
I choose to duplicate ~24 lines of code. In the end is 0 maintenance burden.  It could have been refactored, but it works this way.
Error reporting is no better or worse than other part of netlab. It may be improved. 
Please use it. Break it.
=> Netlab exec

netsim/ansible/templates/initial/eos.j2
Errors in transformation logic can lead to ```int``` type values being passed to templates.
As it turns out, ```ipv4``` believes ```1``` is a perfectly valid IP address -  this PR correctly marks it as "invalid"
=> Be extra pedantic about IP address values

netsim/cli/usage.txt
Add exec command to usage.txt. Ensures that the new exec command is listed in the usage banner when netlab command is invoked without any parameters.
This  one slipped between the cracks yesterday.
=> Add exec command to usage.txt.

netsim/modules/vlan.py, netsim/modules/vlan.yml, tests/topology/expected/vlan-vrrp.yml, tests/topology/input/vlan-vrrp.yml
Majority of node VLAN data is copied into SVI interface data after the link transformation. However, that means we could not influence the SVI IP address or selectively enable gateway functionality on a node VLAN.
This fix copies a subset of node vlan data into link interface data for all (virtual or real) access VLAN links, and ensures those attributes do not overwrite the results of link transformation.
Fixes #1411, probably also VLAN part of #1413 (need a regression test after #1422 is merged)
=> Fix: copy select node VLAN data into intf data before link transform

docs/module/vlan.md
=> Doc fix: VLAN module configures only the data-plane functionality

docs/module/gateway.md, netsim/ansible/templates/gateway/arubacx.j2, netsim/ansible/templates/gateway/cumulus.j2, netsim/ansible/templates/gateway/dellos10.j2, netsim/ansible/templates/gateway/eos.j2, netsim/ansible/templates/gateway/frr.vrrp-config.j2, netsim/ansible/templates/gateway/ios.j2, netsim/ansible/templates/gateway/nxos.j2, netsim/ansible/templates/gateway/sros.j2, netsim/ansible/templates/gateway/vyos.j2
#1418 - simple tweak to force the `no vrrp <group> preempt`
=> #1418 - vrrp no preempt needs to be explicit on cEOS

netsim/ansible/templates/initial/frr.j2
Needed for VLAN templates
Fixes https://github.com/ipspace/netlab/issues/1429
=> Install bridge-utils when using Libvirt

docs/labs/clab.md, netsim/install/containerlab.sh, netsim/providers/clab.yml, netsim/templates/provider/clab/clab.j2
Containerlab sets the Docker restart policy of Linux-based containers to 'on-failure' which restarts all lab nodes with kind=linux (FRR, IOSv) after a server reboot without the necessary connectivity (veth pairs)
The containerlab 0.59.0 release added 'restart-policy' keyword. That keyword is now part of configurable 'clab' parameters and is set by default to 'no' on Linux containers.
Template fixes include indentation cleanup; documentation fixes include URLs to various clab parameters
Fixes #1399
=> Use containerlab 'restart-policy' keyword to prevent FRR restarts

netsim/ansible/templates/vlan/iosvl2.j2, netsim/devices/ioll2.yml
Ioll2 was promoted to multilayer switch
Routed sub-interfaces where enabled and the vlan template was taught how to configure them
Routed Native vlan was enabled
This change set does not promotes iosvl2 to a multilayer switch.  The platform was not tested. When enabled and tested, depending of the results of the tests, we may have to do away with the symlinks which are still present. 
It also does not contain any attempt to mixed trunks.
Changes where tested on vlan integration test suite.  At this time all tests up and including 61-vlan-routed-native are a success.  test success is dependent of running the correct version of iouyap.
=> Further IOLL2 enablement

netsim/modules/vlan.py, tests/topology/expected/vlan-access-single.yml, tests/topology/input/vlan-access-single.yml
A premature optimization in VLAN pre_link_transform code skipped links that did not have the link-level VLAN attribute, ignoring links where the access VLAN was specified on an interface.
Fixes #1436 (root cause found by @jbemmel in #1442)
=> Bug fix: copy node VLAN data into interface data on all links

docs/module/dhcp.md, docs/module/vlan.md, netsim/modules/dhcp.py, netsim/modules/vlan.py, netsim/modules/vlan.yml, tests/topology/expected/dhcp-vlan.yml, tests/topology/input/dhcp-vlan.yml
This fix introduces a strict check of link interface attributes for VLAN access connections where the VLAN forwarding mode is 'bridge' or 'irb'. The only exceptions are the physical interface attributes, STP parameters, and 'no IPv4/IPv6' parameters.
The fix resulted in 'dhcp-vlan' transformation test failure, and after fixing that transformation test, #1359 magically disappeared.
Replaces #1442, accidentally fixes #1359
=> Bug fix: reject per-link irb/bridge VLAN interface attributes

netsim/ansible/tasks/linux/initial-clab.yml
Docker containers do not have their network namespaces mapped into the /var/run/netns directory, so we cannot use 'ip netns exec' command with regular containers, and we used a dirty hack to provision Linux container networking.
Containerlab does map the container network namespace into that directory, so we can replace the hack with a much cleaner and more robust solution, using clab container name as the network namespace.
Replaces #1463
=> Fix: remove the 'temporary net namespace' hack

docs/module-reference.md, docs/module/stp.md, netsim/ansible/templates/stp/cumulus.j2, netsim/ansible/templates/stp/eos.j2, netsim/ansible/templates/stp/frr.j2, netsim/ansible/templates/vlan/frr.j2, netsim/devices/cumulus.yml, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/modules/stp.py, netsim/modules/stp.yml, netsim/modules/vlan.yml, tests/errors/invalid-module.log, tests/errors/module-missing-prerequisite.log, tests/errors/validate-list.log, tests/integration/stp/01-vlan-loop-single.yml, tests/integration/stp/02-vlan-loop-multiple.yml, tests/integration/stp/03-vlan-multi-link.yml, tests/integration/stp/03b-vlan-multi-link-no-stp.yml, tests/integration/stp/04-disable-stp.yml, tests/integration/stp/05-mstp.yml, tests/integration/stp/06-disable-stp-per-vlan.yml, tests/topology/expected/stp-mstp.yml, tests/topology/expected/stp-pvrst.yml, tests/topology/input/stp-mstp.yml, tests/topology/input/stp-pvrst.yml
* Brings enable/disable STP under Netlab control
* ```stp.protocol```: One of ```stp```(default),```mstp```,```rstp```,```pvrst```, global flavor to run on all supporting nodes
* ```stp.priority``` for setting bridge priority
* ```stp.port_priority``` for selecting between multiple local interfaces
PR modifies FRR vlan template to enable STP before the bridge is enabled, to prevent loops also during startup. A slight violation of modularity, but warranted imho
Cumulus container was found to start sending duplicate BPDUs with both old and new port priority values, requiring a mstpd daemon restart to restore sanity
```
The following table describes per-platform support of individual STP features:
| Operating system   | STP | MSTP | RSTP | Per-VLAN (R)STP | Enable per port
| …
```
=> STP module

docs/labs/clab.md, netsim/ansible/tasks/deploy-config/linux-clab.yml, netsim/ansible/tasks/linux/initial-clab.yml, netsim/cli/status.py, netsim/providers/clab.py, netsim/providers/clab.yml, netsim/templates/provider/clab/clab.j2, tests/topology/expected/clab-attributes.yml, tests/topology/input/clab-attributes.yml
Fixes https://github.com/ipspace/netlab/issues/1466
Usage: ```netlab up 02-vlan-bridge-multiple.yml -p clab -d frr -s defaults.providers.clab.lab_prefix=""```
=> Cleanup container names

netsim/defaults/hints.yml, netsim/modules/vlan.py, netsim/modules/vlan.yml, tests/topology/input/rt-vlan-mode-link-route.yml, tests/topology/input/vlan-routed-vrf.yml
Connecting a bridge/IRB interface to two segments of a routed VLAN results in a shared IP prefix used on both segments.
This change checks for the forwarding mode mismatch and triggers an error that can be disabled with a defaults setting (because someone might want to use the shared IP prefix)
It turns out several routed VLAN transformation tests relied on this behavior, so they got the VLAN default tweak.
Fixes #1461
=> Fix: check the VLAN/interface fwd mode compatibility

docs/caveats.md
Initial support for IOL images was introduced in 0.58.0, but a breaking change was introduced soon after, to fix the issue with the system bridges having same MAC. In effect, image docker containers will not start under containerlab 0.58.0 anymore.
=> Document minimum containerlab version as 0.59.0. 

netsim/modules/vrf.py, tests/topology/expected/null-vrfs.yml, tests/topology/input/null-vrfs.yml
If a topology contains only node local vrfs, normalization is skipped
=> Fix order of vrf normalization

netsim/ansible/templates/gateway/dellos10.j2
OS10 defaults to VRRP version 2, which only supports ipv4, has different timer resolution and supports authentication
When modeling an ipv4-only network, the version needs to be set to 2
Context: https://www.dell.com/support/kbdoc/en-us/000135285/vrrp-version-2-and-version-3-in-dell-emc-networking-os10-switches
=> Dell OS10: Only enable VRRP version 3 if ipv6 is used

docs/plugins.md, docs/plugins/vrrp.version.md, netsim/extra/vrrp.version/defaults.yml, netsim/extra/vrrp.version/dellos10.j2, netsim/extra/vrrp.version/plugin.py
Provides control over the VRRP protocol version to run, specifically by downgrading to (obsolete) v2
=> VRRP version plugin for gateway module

netsim/defaults/hints.yml, netsim/modules/evpn.py
This commit simplifies the EVPN node VRF checks: the node VRFs should not have any EVPN attributes (at the moment).
Inspired by #1489
=> Fix: Node VRFs should not have any EVPN attributes

netsim/augment/nodes.py, netsim/outputs/ansible.py
This fix implements additional checks on main loopback IP addresses:
it cannot be true/false (unnumbered/LLA loopbacks make no sense) and
it cannot be int (node ID is used in that case).
Prevents https://github.com/ipspace/netlab/pull/1495 for good
=> Fix: Check for unnumbered/LLA loopback addresses

netsim/devices/__init__.py, netsim/devices/dellos10.py
The generic report_quirk function provides an abstraction on top of log.error that checks whether the specified quirk should be reported, giving the user means of turning off device-specific warnings.
Implemented for OSPF on DellOS10 SVI as a proof-of-concept
Fixes #1501
=> Make quirk errors configurable

docs/module/vrf.md, netsim/modules/vrf.py, netsim/modules/vrf.yml, tests/topology/input/vrf-leaking-loop.yml
Some VRF names cannot be used because they might interfere with built-in VRF names.
Closes #1509
=> Check for reserved VRF names

netsim/providers/libvirt.py
Not needed and may interfere with STP module (e.g. by forcing ports into basic STP compatibility mode)
Considered making this dependent on STP module being used, but I think it's better to disable in any case
=> Disable STP on libvirt created bridges

netsim/providers/libvirt.py
Some people may use a management subnet that is not /24
Fixes https://github.com/ipspace/netlab/issues/1524
=> Libvirt: Limit DHCP pool size to max 254 hosts to avoid crash

netsim/devices/linux.yml, netsim/providers/clab.py
The current devices only use ```kmods:``` (empty) to specify they need system default kernel modules loaded
* Cumulus NVUE needs ebtables loaded too, regardless of which modules are used (modeled as depending on 'initial')
* Linux nodes don't need any (don't support any modules that would require additional kmods); ndata.module becomes ```{}``` for hosts
The original code wasn't actually using ```ddata.kmods```, but because none of the current devices had any value for it that didn't cause any issues
=> Fix clab device specific kernel module loading

netsim/providers/clab.py, netsim/providers/libvirt.py, netsim/utils/linuxbridge.py
Using Libvirt forwarding for LACP frames is not enabled for the bridges interconnecting the nodes. This PR removes some duplicate code, and consolidates proper bridge forwarding settings in a utils package
=> Refactor Linux bridge function to configure LACP forwarding for Libvirt too

docs/dev/plugins.md, docs/groups.md, docs/netlab/connect.md, docs/release/1.0.md, docs/release/1.2.md, docs/release/1.3.md, docs/release/1.4.md, netsim/augment/groups.py, netsim/data/validate.py, netsim/defaults/attributes.yml, tests/errors/group-invalid-attr-type.log, tests/errors/invalid-group-attribute.log, tests/errors/invalid-group-vars-element.log, tests/errors/validate-list.log, tests/topology/expected/groups-vlan-vrf.yml, tests/topology/input/groups-vlan-vrf.yml
This PR generalizes "node groups" into "object groups" and adds VLAN and VRF groups.
The new group types are identified with the **type** attribute, whereas a group with no
**type** attribute is assumed to be a node group.
=> VLAN and VRF groups

netsim/ansible/templates/stp/cumulus.j2, netsim/ansible/templates/stp/cumulus_nvue.j2, netsim/ansible/templates/vlan/cumulus_nvue.j2, netsim/devices/cumulus.py, netsim/devices/cumulus_nvue.py, netsim/devices/cumulus_nvue.yml, tests/integration/stp/02-vlan-loop-multiple.yml, tests/integration/stp/02b-vlan-loop-trunk.yml, tests/integration/stp/03-vlan-multi-link.yml, tests/integration/stp/03c-vlan-trunk-priority.yml, tests/integration/stp/07-pvrst-interop.yml, tests/integration/stp/templates/vlan/dellos10.j2
Cumulus 5.6 introduced support for PVRST on VLAN-aware bridges. This PR adds support for that in Netlab
* Fixes a critical issue with NVUE auto-generating the same MAC for each br_default (not sure why...)
* Configures per-VLAN port priority (including on VLAN trunks, which is somewhat convoluted)
* PR includes a PVRST interop test between Dell OS10 and Cumulus NVUE; correct root bridges are elected
* Update Cumulus NVUE libvirt image to 5.10
Open issues:
* Configured per-vlan port priorities do not appear on the wire - could be a bug in Cumulus. Unable to solve that here
* PVRST seems to work best when using trunk vlans between switches, not access vlans (per-VLAN tagging gets lost)
Could add a quirk warning about this combination
Note: the cumulus.j2 change doesn't really belong in this …
=> Cumulus_nvue: add stp support (including PVRST)

netsim/ansible/templates/stp/dellos10.j2, tests/integration/stp/03-vlan-multi-link.yml, tests/integration/stp/03b-vlan-multi-link-no-stp.yml
Fixes the configuration of ```stp.port_priority``` on VLAN trunks
=> Dell OS10: Fix trunk STP port priority

netsim/ansible/templates/initial/dellos10.j2, netsim/ansible/templates/lag/dellos10.j2, netsim/devices/dellos10.yml, tests/integration/lag/03-l3-lag-passive.yml
Adds passive mode test
TODO: Could rename ```lag_interface_name``` to ```features.lag.interface_name``` for consistency with vlan module
=> Dell OS10: Add lag support

.pre-commit-config.yaml, docs/module/lag.md, netsim/ansible/tasks/deploy-config/cumulus_nvue.yml, netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/ansible/templates/lag/cumulus_nvue.j2, netsim/ansible/templates/vlan/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml, tests/integration/lag/01-l3-lag.yml
* Enables bonded interfaces with dynamic (LACP) or static modes
* Refactor IP address config as macro; used only in 'initial' script
* Explicitly disable ipv6 when not configured
* Define MTU in lag OSPF test such that it works on libvirt too
Note: Fixes ipv6-only unnumbered config, would have been skipped prior to this PR
=> Cumulus_nvue: basic lag support

docs/platforms.md, netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml
* Removes interface ```type``` test
* Puts interfaces in the correct VRF
* Fixes IPv6 to send out router-advertisements ( "off" means enable them ... )
* Updates docs (note I could not find ```bandwidth``` setting in NVUE)
Note that Cumulus supports multiple loopbacks by putting multiple IPs on a single loopback device; ```set``` commands are cumulative and don't replace existing addresses
This also means applying Netlab configs to a system that already has some existing configs won't replace those; this would require an 'unset' command
=> Cumulus_nvue: Add loopback and VRF support, fix IPv6

netsim/ansible/templates/initial/dellos10.j2
By default, OS10 enables ipv6 on loopbacks and assigns a LLA. If the config says 'no ipv6', it should be disabled
Context: #1494
=> OS10: Disable ipv6 on loopback if not configured

docs/module/vrf.md, netsim/ansible/templates/ospf/cumulus_nvue.j2, netsim/ansible/templates/vrf/cumulus_nvue.j2, netsim/devices/cumulus_nvue.py, netsim/devices/cumulus_nvue.yml, netsim/modules/vrf.py
* Passes ```integration/vrf/11-multi-vrf-ospf```
* Cannot do ```integration/vrf/33-vrf-common-ospf``` yet; add quirk check for missing vrf route leaking
Note: NVUE VRF aware loopback support was added in a previous PR, but not updated in docs yet
=> Cumulus_nvue: Add OSPFv2 in vrf support

netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/devices/cumulus.yml, netsim/devices/cumulus_nvue.yml, netsim/templates/provider/libvirt/cumulus_nvue-domain.j2
* Use variable for cumulus password provisioned into the box
* Declare Cumulus container images unsupported (warning to be added)
=> Cumulus_nvue: Use password variable instead of hardcoded string, declare container image unsupported

docs/caveats.md, netsim/devices/cumulus_nvue.py
=> Fix: Print a warning when using CL 5.x containers

docs/module/bgp.md, docs/plugins/bgp.domain.md, docs/plugins/ebgp.utils.md, docs/release.md, docs/release/1.3.md, docs/release/1.6.md, netsim/devices/cumulus.yml, netsim/devices/cumulus_nvue.yml, netsim/devices/dellos10.yml, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/devices/sonic.yml, netsim/devices/srlinux.yml, netsim/devices/sros.yml, netsim/devices/vyos.yml, netsim/modules/bgp.py, netsim/modules/bgp.yml, tests/topology/expected/bgp-unnumbered-dual-stack.yml, tests/topology/input/bgp-unnumbered-dual-stack.yml
The EBGP session creation code was a bit of a mess (including references to non-existent interface 'unnumbered' attribute). With the redefinition of ipv6_lla and rfc8950 feature flags triggered by #1562 and #1565 a refactoring was overdue (hopefully making the code easier to read):
* All references to 'unnumbered' attribute or AF were removed. The link transformation module turns them into 'ipv4: True' and 'ipv6: True' anyway.
* The ipv6_lla feature flag now means 'the box supports IPv6 LLA sessions and RFC 8950 IPv4 AF over those sessions'. We found no device that would support IPv6 LLA EBGP sessions without RFC 8950 IPv4 next hops, so it made no sense to keep two feature flags. If such a device ever appears, the exception will be handled as a device quirk.
* The rfc8950 feature flag …
=> Refactor EBGP IPv6 LLA/RFC 8950 code

netsim/modules/lag.py, tests/topology/expected/lag-mlag.yml, tests/topology/input/lag-mlag.yml
Corrects an issue with duplicate ```lag.ifindex``` assignment, due to restarting the count for each link
Adds a test case for multiple lag links between the same pair of nodes
=> lag: Assign unique lag.ifindex

netsim/utils/linuxbridge.py
For Netlab purposes, the main point is LLDP forwarding
=> Remove promise to forward LACP; it doesn't work

netsim/ansible/templates/ospf/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml
Fix loopback interface name to be 'lo' instead of 'lo0'
Fixes #1584
=> cumulus_nvue: Fix ospf dict merging

netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/augment/links.py, tests/topology/expected/link-loopback.yml, tests/topology/input/link-loopback.yml
Fixes https://github.com/ipspace/netlab/issues/1583
Also modifies Netlab link augmentation code to remove MTU settings from loopbacks, since they generally don't make sense and might trip over other platform templates
=> Cumulus_nvue: Don't try to configure MTU for loopback interfaces

netsim/ansible/templates/ospf/cumulus_nvue.j2, netsim/devices/cumulus_nvue.py
"Fixes" https://github.com/ipspace/netlab/issues/1585
Also cleanup OSPF template using ```combine``` filter instead of **dict expansion
=> Cumulus_nvue: Add quirk to alert user to lack of OSPFv3 support in NVUE

netsim/ansible/templates/bgp/cumulus_nvue.j2
Fixes https://github.com/ipspace/netlab/issues/1594
=> Cumulus NVUE: Set neighbor BGP AS to "internal" when it is the same as bgp.as

docs/platforms.md
Validated that Cumulus passes the first OSPFv3 integration test
=> Cumulus: Update OSPFv3 support check mark

netsim/ansible/templates/initial/dellos10.j2
Dell OS10 enables ipv6 unless told not to. On ipv4-only interfaces it should be disabled
=> Dell OS10: Disable ipv6 on ipv4-only interfaces

netsim/ansible/tasks/deploy-config/dellos10.yml, netsim/ansible/tasks/deploy-config/vyos.yml, netsim/ansible/tasks/readiness-check/vsrx.yml, netsim/ansible/templates/initial/cumulus.j2, netsim/ansible/templates/lag/frr.j2
Needed to fix multi-provider deployments; FRR clab nodes in a libvirt topology currently try to run ```modprobe``` for example
=> Replace use of 'netlab_provider' with 'node_provider' in templates

extool/nso.md, extools.md, netsim/tools/nso.yml
This PR adds the Cisco NSO Docker container as an external tool to any lab topology. Also have created documentation.
This PR closes #1615
=> Adds NSO Docker as an external tool

netsim/modules/lag.py, tests/topology/expected/lag-l2.yml, tests/topology/expected/lag-l3-access-vlan.yml, tests/topology/expected/lag-l3-vlan-trunk.yml, tests/topology/expected/lag-l3.yml, tests/topology/expected/lag-mlag.yml, tests/topology/input/lag-mlag.yml
This PR solves an issue with ```lag.ifindex``` allocation; in an a-typical mixed use case where there are both regular lags and mlags there are cases where overlapping ```lag.ifindex``` values get generated
On the "M" side of mlags the lag.ifindex needs to match, on the "1" side and on regular lags any locally unique value will suffice
=> lag: Avoid picking overlapping lag.ifindex in mixed scenarios

netsim/extra/node.clone/defaults.yml, netsim/extra/node.clone/plugin.py, tests/topology/expected/node.clone-plugin.yml, tests/topology/input/node.clone-plugin-lag.yml, tests/topology/input/node.clone-plugin.yml
* Remove attribute definitions as they are not being validated by Netlab anyway
* Add parameter validation
* Cleanup test cases, split between lag and non-lag
Replaces https://github.com/ipspace/netlab/pull/1638
=> node.clone plugin cleanup

netsim/install/libvirt.sh
There is a later release, if we want people to use this specific one the user may need to downgrade
=> Use --allow-downgrades to install specific Vagrant version

docs/caveats.md, netsim/ansible/templates/initial/frr.j2, netsim/templates/provider/libvirt/frr-domain.j2
Installing FRR during 'vagrant up' processing should result in reduced overall start time as other VMs usually take longer to boot.
In labs using only fast-start VMs it might be better to postpone the FRR installation, in particular if you use --fast-config option. Setting netlab_quick_start node variable postpones FRR installation until the initial configuration process.
Closes #1596
=> Install FRR during 'vagrant up' processing

netsim/modules/stp.yml, tests/topology/expected/lag-l2.yml, tests/topology/expected/stp.yml, tests/topology/input/stp.yml
* Set ```intf_to_neighbor``` to False to prevent propagation to neighbor data
* Generalize STP test case to include various ```stp.enable: False``` cases
=> STP: Prevent propagation of attributes to neighbor data

netsim/devices/none.yml
The ```none``` device should declare to support lag features, such that devices can be emulated without being instantiated
=> Add 'lag' support to the 'none' device

docs/addressing.md, docs/dev/transform.md, docs/example/addr-builtin.txt, docs/links.md, docs/prefix.md, docs/release/1.9.md, netsim/augment/links.py, tests/topology/expected/bgp-vrf-local-as.yml, tests/topology/expected/bgp.yml, tests/topology/expected/dual-stack.yml, tests/topology/expected/groups-vlan-vrf.yml, tests/topology/expected/libvirt-clab-complex.yml, tests/topology/expected/link-tunnel.yml, tests/topology/expected/rt-vlan-mode-link-route.yml, tests/topology/expected/vlan-vrf-lite.yml, tests/topology/expected/vrf-leaking-loop.yml, tests/topology/input/dual-stack.yml
netlab used the link.type attribute to select the default prefix allocation pool, resulting in LAN prefixes assigned to some P2P links.
This commit removes the dependency on link.type and consistently assigns prefixes from p2p pool to inter-router P2P links.
Closes #1647, replaces #1648
=> Use # of nodes on a link (not link type) to select default pool

netsim/templates/provider/libvirt/define-domain.j2
Ruby requires at least the first character to be lower case, easier to just make the entire string ```lower()```
Fixes https://github.com/ipspace/netlab/issues/1675
=> Libvirt/Vagrant: Fix vm name constant to be lowercase

docs/module/ospf.md, netsim/ansible/templates/ospf/dellos10.macro.j2, netsim/ansible/templates/ospf/dellos10.ospfv2.j2, netsim/ansible/templates/ospf/dellos10.ospfv3.j2, netsim/ansible/templates/vrf/dellos10.j2, netsim/ansible/templates/vrf/dellos10.ospfv2-vrf.j2, netsim/devices/dellos10.yml, tests/integration/ospf/ospfv2/31-priority.yml
* Refactor templates to use a common ```configure_ospf_interface``` macro
* Keep existing redistribution configs for VRFs (though inconsistent with default VRF)
* Add ```ipv6 ospf passive``` to v6 loopback (tested - yes it makes a difference, though aesthetic more than material)
* Add ospf priority setting on interface, if defined
Passes ```integration/ospf/ospfv2/30-timers.yml``` test case
Passes (modified) ```integration/ospf/ospfv2/31-priority.yml``` test case
=> Dell OS10: Add ospf timers/priority support

netsim/augment/links.py, netsim/augment/main.py, netsim/augment/nodes.py, tests/topology/expected/anycast-gateway.yml, tests/topology/expected/components.yml, tests/topology/expected/device-node-defaults.yml, tests/topology/expected/dhcp-vlan.yml, tests/topology/expected/evpn-asymmetric-irb-ospf.yml, tests/topology/expected/evpn-vxlan.yml, tests/topology/expected/fabric-ebgp.yml, tests/topology/expected/groups-vlan-vrf.yml, tests/topology/expected/lag-mlag-m_to_m.yml, tests/topology/expected/libvirt-clab-complex.yml, tests/topology/expected/node.clone-plugin.yml, tests/topology/expected/rt-vlan-anycast.yml, tests/topology/expected/rt-vlan-mode-link-route.yml, tests/topology/expected/unmanaged-device.yml, tests/topology/expected/vlan-access-links.yml, tests/topology/expected/vlan-access-node.yml, tests/topology/expected/vlan-access-single.yml, tests/topology/expected/vlan-bridge-trunk-router.yml, tests/topology/expected/vlan-coverage.yml, tests/topology/expected/vlan-native-routed.yml, tests/topology/expected/vlan-routed.yml, tests/topology/expected/vlan-trunk-native.yml, tests/topology/expected/vlan-vrf-lite.yml, tests/topology/expected/vlan-vrrp.yml, tests/topology/expected/vxlan-vrf-lite.yml
This commit prepares the static routes that have to be configured on lab devices not running a routing protocol (hosts). It mirrors the functionality currently implemented in the Linux configuration template but makes it generic and ensures the static routes always have a next hop if at least one interface has a default gateway.
The data structures for all hosts in a lab topology are significantly modified:
* The 'gateway' data structure is always copied from the link to the hosts to ensure the next step has all the relevant information available
* The host data contains 'routing.static' list of static routes pointing to the first usable gateway.ipv4 address.
The change prepares the data structures needed to fix #1641 but provides a more generic framework that will be used to implement …
=> Generic host static routing framework

netsim/augment/links.py, tests/topology/expected/bgp-unnumbered-dual-stack.yml
Netlab link augmentation code uses address family from the loopback interface to figure out what to do on old-style unnumbered links.
That clearly does not work on hosts that have no loopback interface. This fix enables IPv6 LLA on hosts attached to unnumbered links, hoping someone might eventually figure out whether that makes sense.
It also removes 'unnumbered' attribute from the link, as no device configuration template checks it. We'll clean up other references to the 'unnumbered' flag in another commit.
Fixes #1692
=> Fix: Deal with hosts attached to unnumbered links

netsim/ansible/templates/vrf/dellos10.ospfv2-vrf.j2
Might be related to https://github.com/ipspace/netlab/issues/1135
Fixes both 33-vrf-common-ospf and 34-vrf-common-mixed integration test cases
Technically this flag is only required if there are multiple VRFs running OSPF and they import from each other - but I think it's safe to enable whenever OSPF is used in VRFs
Note: Also fixes reference_bandwidth attribute
=> Dell OS10: Fix test cases 33-vrf-common-ospf and 34- by redistributing imported OSPF routes too

docs/module/lag.md, netsim/ansible/templates/initial/arubacx.j2, netsim/ansible/templates/lag/arubacx.j2, netsim/devices/arubacx.py, netsim/devices/arubacx.yml
Tested with all 'lag' integration tests except for *11-host-lag-active-standby.yml* (which complains about unsupported lag module on linux).
Will re-run the tests after #1698 - but there should be no problems.
=> AOS-CX: support for LAG and MCLAG

netsim/modules/gateway.py, tests/topology/expected/anycast-gateway.yml, tests/topology/input/anycast-gateway.yml
Similar to IGP routing protocols, the module should be removed when not used
(Note: Same could be done for the ```vlan``` module on ```r3``` in this test case)
=> gateway: Remove config/module if not used on a node

docs/module/stp.md, netsim/ansible/templates/stp/cumulus.j2, netsim/ansible/templates/stp/cumulus_nvue.j2, netsim/ansible/templates/stp/dellos10.j2, netsim/ansible/templates/stp/eos.j2, netsim/devices/cumulus.yml, netsim/devices/cumulus_nvue.yml, netsim/devices/dellos10.yml, netsim/devices/eos.yml, netsim/devices/none.yml, netsim/modules/stp.py, netsim/modules/stp.yml, tests/errors/stp-on-l3-intf.log, tests/integration/stp/08-stp-port-type.yml, tests/topology/expected/stp-port-type.yml, tests/topology/expected/stp.yml, tests/topology/input/stp-port-type.yml, tests/topology/input/stp.yml
* Option to auto-configure stp.port_type as 'edge' for ports with only hosts connected, default disabled
* Feature flag stp.port_type (not supported by FRR)
=> STP: Add stp.port_type configuration for Cumulus 4.x/NVUE, EOS and Dell OS10

docs/links.md, netsim/augment/links.py, netsim/defaults/const.yml, netsim/modules/vlan.py, tests/topology/expected/unnumbered.yml, tests/topology/expected/vlan-access-links.yml, tests/topology/input/unnumbered.yml, tests/topology/input/vlan-access-links.yml
The interface description is limited to 255 characters due to SNMP MIB-2 limitations. This fix introduces two system const parameters (maxlength and max neighbors) that limit the length of the interface description.
Fixes #1709
=> Fix: restrict interface description length

netsim/modules/lag.py
Based on feedback from https://github.com/ipspace/netlab/pull/1711
At least Dell OS10 and Aruba CX don't support "routed MLAG" interfaces
=> lag: Disallow direct IP addressing on MLAG interfaces

netsim/ansible/templates/lag/dellos10.j2, netsim/devices/dellos10.py
Updated after feedback:
* (still) limit interface descriptions to 255 characters when adding local string
* Enable switchport on mlag interfaces in case there is no VLAN (-trunk)
* Replace comma's in descriptions, if any
=> Dell OS10: interface description fixes & mlag switchport fix

.github/workflows/tests.yml
After adding back Python 3.8, we need to increase parallelism
=> CI/CD: Increase max parallel tests

netsim/ansible/templates/initial/frr.j2, netsim/devices/linux.yml
Combining the bonding plugin branch with the Linux lag support changes wasn't the best idea in hindsight - some obvious integration test cases got skipped in the process
* Set 'lag' feature flag for Linux devices
* Create lag devices on FRR
Tested:
```netlab up integration/lag/01-l3-lag.yml -p clab -d frr -s lag.mode=balance-xor```
```netlab up integration/lag/04-host-mlag.yml -d eos -p clab```
=> lag: Set Linux feature flag, create lag devices on FRR

docs/module/lag.md, netsim/ansible/templates/lag/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml, netsim/modules/lag.py, netsim/modules/lag.yml, tests/integration/lag/09-mlag-m-to-m.yml, tests/topology/expected/lag-mlag-m_to_m.yml, tests/topology/expected/node.clone-plugin-lag.yml
* Generalize lag module features, adding ```global``` option to use per-node peerlink settings instead of per interface
* Add ```backup_ip``` option
* Update documentation
=> Cumulus_NVUE: Add mlag support

docs/caveats.md, docs/module/vlan.md, netsim/ansible/tasks/readiness-check/vptx-clab.yml, netsim/ansible/tasks/readiness-check/vptx.yml, netsim/ansible/templates/initial/junos.j2, netsim/ansible/templates/initial/junos.vlan.j2, netsim/ansible/templates/vlan/vjunos-switch.j2, netsim/ansible/templates/vlan/vmx.j2, netsim/ansible/templates/vlan/vptx.j2, netsim/devices/junos.py, netsim/devices/vjunos-router.py, netsim/devices/vjunos-router.yml, netsim/devices/vjunos-switch.yml, netsim/devices/vptx.yml, tests/topology/expected/ospf.yml
**(v)Junos VLAN Major Fixes and refactoring**
(unfortunately for multiple stuff it was hard to split in different PR, so I preferred to keep all the things together)
Re-tested vJunos-switch, vJunos-router, vJunos-EVO (vPTX) and an old version of vSRX (unable to access newer ones)(only for specific supported features) with: 
* 01-vlan-bridge-single.yml
* 02-vlan-bridge-multiple.yml
* 21-vlan-irb-single.yml
* 22-vlan-irb-multiple.yml
* 23-vlan-mixed-multiple.yml
* 31-vlan-bridge-trunk.yml
* 32-vlan-bridge-trunk-router.yml
* 33-vlan-irb-trunk.yml
* 41-vlan-bridge-native.yml
* 42-vlan-irb-native.yml
* 51-vlan-routed-trunk.yml
* 52-vlan-vrf-lite.yml
* 61-vlan-routed-native.yml
* 62-vlan-mixed-trunk.yml (mixed trunk not supported on switch devices)
* 63-vlan-mixed-native.yml (mixed trunk not …
=> (v)Junos VLAN Major Fixes and refactoring

docs/module/ospf.md, netsim/ansible/templates/ospf/arubacx.ospfv2.j2, netsim/ansible/templates/vrf/arubacx.ospfv2-vrf.j2, netsim/devices/arubacx.yml
Tested with:
* 30-timers.yml
* 31-priority.yml
* 32-password.yml
=> AOS-CX: Add OSPFv2 timers, priority, plain text auth

docs/plugins/node.clone.md, netsim/extra/node.clone/plugin.py
Use case: Declare a large number of hosts as 'unmanaged', instantiate one or two for validation testing
Rather than reject clones matching existing node names, this PR merges their properties
=> Node.clone: Allow override of properties by including cloned node name in topology

netsim/ansible/tasks/deploy-config/cumulus_nvue.yml
There are cases where the output of ```nv config apply``` shows errors, while the command returns "success".
In my case, due to a bug somewhere else the script was trying to provision a non-existent device
Catch such errors and report failure
=> Cumulus NVUE: Fail in case of errors in "nv config apply"

netsim/augment/links.py, tests/errors/anycast-prefix.log
#1673 deprecated the use of ```link.type``` to select addressing pools
=> Links: update hint to remove obsolete 'type' method of controlling addressing

netsim/ansible/tasks/readiness-check/vm-clab-ssh-check.yml, netsim/devices/vjunos-router.yml
The SSH client used to check vrnetlab readiness can be stuck for an awfully long when the VM is in just the right phase of getting ready. This change uses the 'timeout' command (when available) to kill the check after 5 seconds, allowing the Ansible retry mechanism to work as expected.
=> Use timeout to kill vrnetlab readiness check SSH sessions

netsim/ansible/templates/initial/linux/ubuntu.j2
Update: Modified to add static routes under each interface separately, such that the interface type is automatically correct
=> Ubuntu: Add static routes per interface instead of a separate single file

netsim/providers/libvirt.py, tests/topology/expected/node.clone-plugin-lag.yml, tests/topology/expected/node.clone-plugin.yml
As can be seen in the corrected test outputs, VLAN SVI interfaces can have an ```ifindex```<1000 which causes libvirt to count them as 'physical' interfaces. This in turn messes up the padding logic, resulting in missing interfaces
This bug can be triggered in topologies involving VLANs and custom ```ifindex``` override attributes
Partly fixes https://github.com/ipspace/netlab/issues/1738
=> Libvirt: Don't depend on ifindex to identify physical interfaces

netsim/ansible/templates/stp/cumulus_nvue.j2
It is not sufficient to configure the priority globally, the default priority per VLAN must also be configured
Fixes https://github.com/ipspace/netlab/issues/1746
=> Cumulus NVUE: Configure global stp.priority also for each VLAN (in case of PVRST)

netsim/ansible/templates/stp/dellos10.j2
Partially fixes https://github.com/ipspace/netlab/issues/1747
STP path cost on Dell OS10 is lower (800) than EOS (20000) because Dell OS10 emulates 25G NICs versus EOS' 1G NICs
=> Dell OS10: Apply global stp.priority per VLAN too

netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/initial/linux/vanilla.j2, netsim/ansible/templates/lag/cumulus_nvue.j2, netsim/modules/lag.py, netsim/modules/lag.yml, tests/topology/expected/lag-l2.yml, tests/topology/expected/lag-l3-access-vlan.yml, tests/topology/expected/lag-l3.yml, tests/topology/expected/lag-mlag.yml, tests/topology/expected/lag-vlan-trunk.yml
It used to be that setting MTU on a Linux bond device resulted in an error - or so I thought. In any case, now it works so we can use that to fix MTU related issues with lags
Setting the MTU changes the MTUs of all members
Fixes https://github.com/ipspace/netlab/issues/1750 and #1751
=> lag: Restore mtu attribute on lag interfaces

docs/module/lag.md, netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/ansible/templates/lag/cumulus_nvue.j2
Depending on RACE conditions, the bond could fail to come up if a lag member is brought up too early, and a duplicate IP is detected
Initially keep lag member interfaces down, and only bring them up once the peerlink is configured
Fixes https://github.com/ipspace/netlab/issues/1759
=> Cumulus NVUE: Postpone bringing lag member interfaces up until the bond is in place

netsim/ansible/templates/bgp/dellos10.macro.j2, netsim/ansible/templates/initial/dellos10.j2, netsim/devices/dellos10.yml
Attempted to add ibgp_localas support, but the device just won't behave correctly
* Conditionally add 'no-prepend replace-as' flags, not always
* Use `_source_ifname` to set loopback source interface
* Handle both ibgp and localas_ibgp neighbor types
* Simplify community processing
* Fix loopback IP selection (see #1767)
=> Dell OS10: Cleanup BGP template

netsim/ansible/tasks/deploy-config/arubacx.yml
Instead of invoking two times `aoscx_config`, we can add the `auto-confirm` as *before* param of the "real" module call.
=> AOS-CX: optimize configuration task

netsim/extra/bonding/linux-clab.j2, netsim/extra/bonding/plugin.py, netsim/modules/vlan.py
Context: https://github.com/ipspace/netlab/issues/1727
* bonding plugin was executing after gateways had already been assigned, resulting in the wrong interface being selected -> use ```post_link_transform``` instead
* With the corrected nexthop gateway, the bonding plugin bringing down the bond interface cleared the carefully crafted routes -> don't do that
* Cleanup IP addresses in the member neighbors list
* VLAN: Don't assign gateways to L2 interfaces (as are now being introduced with bonding)
* rename bond neighbor ifnames
=> Bonding: Fix gateway routes

netsim/ansible/tasks/deploy-config/cumulus_nvue.yml, netsim/ansible/templates/vlan/cumulus.j2, netsim/ansible/templates/vlan/cumulus_nvue.j2
```bridge-vids``` turns out to be a filter for the vlans allowed on a bond device; if not set, it defaults to *all* vlans on the ```br_default``` bridge, which is obviously incorrect in many cases
The integration tests don't check for this, and it is somewhat tricky to adapt them because FRR on the other side of the bond is doing the right thing and only allowing the correct set of vlans.
While fixing this, I found another case of the ```nv config apply``` command not reporting an error when it should (though not normally triggered by the script)
Tested:
* ```netlab up integration/lag/01-l3-lag.yml -p libvirt -d cumulus_nvue```
* ```netlab up integration/lag/02-lag-vlan-trunk.yml -p libvirt -d cumulus_nvue```
* ```netlab up integration/lag/10-mlag.yml -p libvirt -d cumulus_nvue```
=> Cumulus and Cumulus NVUE: Limit vlans on bonds to those actually part of the trunk

netsim/ansible/templates/stp/cumulus_nvue.j2
Labs are unlikely to hit the 300 VLANs times 24 ports limit to require 7200 pps, the default 2000 pps should suffice
=> Cumulus NVUE: Remove policer increase

netsim/modules/vxlan.py
Many templates use tests like ```if 'vni' in vlan ...```
=> vxlan: Avoid creating empty 'vni' attribute on VLANs

netsim/ansible/templates/vlan/srlinux.j2, netsim/devices/srlinux.yml, tests/integration/mpls/20-vpnv6-connected.yml, tests/integration/ospf/ospfv2/06-vlan-mtu.yml, tests/integration/ospf/ospfv3/07-vlan-mtu.yml
Fixes https://github.com/ipspace/netlab/issues/1844
SR Linux only supports MTU values starting from 1436, propose to increase the values used in the integration tests
=> Srlinux: Configure vlan mtu

netsim/ansible/templates/vlan/cumulus_nvue.j2, tests/integration/vlan/41-vlan-bridge-native.yml
This PR fixes an issue that arises in case of a trunk with a native vlan. Somewhat counter-intuitively, the ```access_id``` attribute gets set, and hence the template failed to create the trunk. As a consequence, all vlans on the bridge would be allowed on the trunk
Fixes logic order of testing, start with trunk
Expand test 41-vlan-bridge-native to include a vlan that is not on the trunk, and hence should be blocked.
Note: All vlan tests are testing DUT against itself, which might fail to detect certain misconfigurations. For example, a device configuring a vlan as tagged while it should be untagged, or vice versa, would still succeed in talking to itself
=> Cumulus NVUE: Allow only those VLANs requested on the trunk, not all vlans on the bridge

netsim/ansible/templates/normalize/eos.j2, netsim/ansible/templates/normalize/iosvl2.j2
Fixes https://github.com/ipspace/netlab/issues/1871
Summary: A user reported an issue with the 'initial' configuration step failing. The Ansible module reporting made it look like an issue with description length or invalid characters, but in reality the topology was using VLANs in the range 1006+<number of interfaces> (starting at 1011, causing issues on devices with 5 interfaces or more)
The ```normalize``` step introduced in ```1.9.4``` configures all ports as ```no switchport```, causing an internal VLAN to be allocated. This PR shuts down the port instead, avoiding the (useless) allocation of VLAN resources
=> EOS/IOS: Use 'shutdown' instead of 'no switchport' to avoid allocating internal VLAN resources

netsim/ansible/templates/initial/cumulus_nvue.j2
Fixes #1864
> It might be better to go for a loop over 'ipv4' and 'ipv6' checking if intf[ax] is defined
I considered that, but the conditions are different for each so I think writing them out separately works better in this case
=> Cumulus NVUE: Disable ipv6 on l2-only interfaces

netsim/ansible/templates/vlan/cumulus_nvue.j2, tests/integration/vlan/31-vlan-bridge-trunk.yml
Fixes https://github.com/ipspace/netlab/issues/1866 (Cumulus NVUE part)
Still passes VLAN tests 31 (modified), 32, 33 and 42 and initial test 01
=> Cumulus NVUE: Don't trunk native VLAN unless requested

netsim/ansible/templates/initial/dellos10.j2, netsim/devices/dellos10.yml, tests/topology/expected/lag-l2.yml, tests/topology/expected/lag-l3.yml, tests/topology/expected/lag-mlag.yml
Passes ```initial/04-mtu``` test
The Dell templates already configure a system wide MTU - this PR simplifies the configuration by removing per-interface MTU settings and declaring system MTU as supported
Some tweaks to the initial template to enable unreachables and MTU discovery on ipv6
=> Dell OS10: Already configures system wide mtu, enable unreachables

netsim/ansible/templates/initial/dellos10.j2, netsim/ansible/templates/vlan/dellos10.j2, tests/integration/vlan/22-vlan-irb-multiple.yml
Expand the types of interfaces for which to disable ipv6: Everything except LAG related interfaces such as peerlinks, port-channels and lag member interfaces.
NB L2-only interfaces include bridged VLANs
Fixes https://github.com/ipspace/netlab/issues/1868
Clear counters on virtual network interfaces (they remain 0)
Tested using OS Version 10.5.6.5 on clab:
* ```lag/11-mlag-anycast.yml```
* ```vlan/21-vlan-irb-single.yml```
* ```vlan/22-vlan-irb-multiple.yml``` (modified to add ipv6 tests in separate PR)
* ```vlan/41-vlan-bridge-native.yml```
Note: Only one of the VLAN integration tests includes ipv6 testing (21), and not between hosts - I figured it would be good to add one more
=> Dell OS10: Don't enable IPv6 for L2-only interfaces or VLANs

tests/integration/vlan/22-vlan-irb-multiple.yml
* Wait for RA default route
* Ping6 between all 4 hosts
Created in the context of https://github.com/ipspace/netlab/pull/1870/files to increase coverage of ipv6 in combination with vlans
=> Integration tests: Expand VLAN test 22-vlan-irb-multiple with ipv6 checks

netsim/modules/lag.py
Fixes https://github.com/ipspace/netlab/issues/1877
There can still be vlan_members that reference the linkindex of the virtual lag links
=> lag: Postpone link cleanup until after vlan module_post_link_transform

netsim/ansible/templates/lag/linux.j2
```ethtool``` line needs to be executed also on libvirt
=> Libvirt Linux lag: Fix conditional logic to set link speed on lag members

netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/ansible/templates/normalize/cumulus_nvue.j2, netsim/ansible/templates/vlan/cumulus_nvue.j2
…such that it also works in (mlag) topologies without VLANs
The MAC is read from the EEPROM, and if it's not set to a unique value each instance gets the same (duplicate) value which breaks mlag and STP to name a few
=> Cumulus NVUE: Move initialization of bridge MAC to 'initial' step

netsim/ansible/templates/initial/linux/ubuntu.j2, netsim/ansible/templates/lag/arubacx.j2, netsim/ansible/templates/lag/cumulus.j2, netsim/ansible/templates/lag/cumulus_nvue.j2, netsim/ansible/templates/lag/dellos10.j2, netsim/ansible/templates/lag/eos.j2
Allows the use of lag.ifindex==0
=> lag: Correct comparison with missing _parentindex using 'None', not 'False' (==0)

tests/integration/lag/04-lag-vlan-routed-trunk.yml
EOS currently fails this test (separate PR):
```
dut#show run int port-channel 1
interface Port-Channel1
description dut -> xr
dut#show run int port-channel 1.1
interface Port-Channel1.1
description dut -> xr
encapsulation dot1q vlan 1000
ip address 10.1.0.1/30
ip ospf network point-to-point
ip ospf area 0.0.0.0
dut#show int Port-Channel 1.1
Port-Channel1.1 is down, line protocol is dormant (notconnect)
Hardware is Subinterface, address is 001c.73f0.28da
Description: dut -> xr
Internet address is 10.1.0.1/30
Broadcast address is 255.255.255.255
IP MTU 9194 bytes (default), BW 2000000 kbit
Down 1 minute, 4 seconds
```
=> lag: Add integration test for routed trunk over lag

tests/integration/gateway/01-anycast.yml
Reduces False positives - fixes https://github.com/ipspace/netlab/issues/1853
Also explicitly check the IPv6 neighbor entry for "REACHABLE" (not "PROBE")
=> Gateway test: Disable the FRR anycast interface before testing pings

netsim/ansible/templates/initial/junos.vlan.j2, tests/integration/vlan/70-vlan-1-trunk.yml
Closes #1910
Tested with vjunos-router (and compat testing with vjunos-switch)
(side note, as reported: requires adding wait timer to test `70-vlan-1-trunk//ping_irb_1`)
=> vJunos: VLAN 1 trunk tweak/fix

docs/dev/validation.md, netsim/data/types.py, netsim/defaults/attributes.yml, netsim/extra/bgp.originate/defaults.yml, netsim/modules/bgp.yml, netsim/modules/routing.yml, tests/errors/bgp-cluster-id.log, tests/errors/ia-ospf-links.log, tests/errors/ia-ospf-nodes.log, tests/errors/link-invalid-node-addr.log, tests/errors/rid-pool-overflow.log
Add more granular IPv4/IPv6 attribute uses:
* Address and prefix
* Host and subnet prefix
* Interface address and ID
Closes #1831
=> Make IPv4/IPv6 address/prefix validation more granular

netsim/devices/nxos.yml
Correct typo in name ```netlaby_check_delay```
=> NXOS: Move netlab_check_* variables to group_vars (where they get read)

netsim/augment/addressing.py, netsim/augment/links.py, netsim/augment/nodes.py, netsim/data/types.py, netsim/extra/ebgp.multihop/plugin.py, netsim/extra/mlag.vtep/plugin.py, netsim/extra/multilab/__init__.py, netsim/extra/proxy-arp/plugin.py, netsim/modules/_routing.py, netsim/modules/bgp.py, netsim/modules/dhcp.py, netsim/modules/routing.py, netsim/modules/srv6.py, netsim/modules/vrf.py, netsim/modules/vxlan.py, netsim/outputs/ansible.py, netsim/providers/libvirt.py, netsim/utils/routing.py, netsim/validate/_common.py, netsim/validate/bgp/eos.py, netsim/validate/eos.py, netsim/validate/isis/frr.py, netsim/validate/ospf/eos.py, netsim/validate/ospf/frr.py, netsim/validate/route/frr.py, tests/errors/addr-pool-errors.log
* Most netaddr calls have been replaced with ipaddress calls, the major exception is MAC address handling which is not available in ipaddress
* The 'get ip from interface' and 'get prefix from interface' functions have been moved to 'utils.routing' and most other modules use those functions
* Direct calls to ipaddress functions are use only for more advanced use cases.
* Error messages in augment.addressing and augment.links have been simplified and include parsing error information from ipaddress
* 'get_addr_mask' and 'get_nth_ip_from_prefix' functions did almost the same thing and have been merged into a single function
* Extra properties available in ipaddress make it easier to check if an address is a network address, multicast address, or a broadcast address
Note:
* Sometimes we …
=> Migrate from netaddr to ipaddress

netsim/ansible/templates/gateway/eos.j2
Allows EOS to pass ```gateway/01-anycast``` tests
=> EOS: Configure ipv6 anycast gateway IP when provided

docs/caveats.md, docs/module/vxlan.md, netsim/ansible/templates/vxlan/cumulus_nvue.j2, netsim/devices/cumulus_nvue.py, netsim/devices/cumulus_nvue.yml
Passes all integration tests except 07 (IPv6 VTEP not supported, blocked on lack of support in ifupdown2)
* Test ```04-vxlan-irb-ospf.yml```: Added a quirk to remove ospf.passive configuration from VRF interfaces, with warning
* Test ```08-vxlan-alt-vtep.yml```: Added a quirk to merge loopback OSPF settings if they are identical, else throw error
=> Cumulus NVUE: Add VXLAN support

netsim/ansible/templates/lag/cumulus_nvue.j2
For a backup connection to mgmt (eth0) to work, it needs to be placed in the ```mgmt``` vrf
=> Cumulus NVUE: Place mlag backup IP in mgmt vrf when applicable

tests/integration/evpn/20-vxlan-irb-ospf.yml
Libvirt causes unnecessary overhead
=> Integration test EVPN 20-vxlan-irb-ospf.yml: Use clab for Linux hosts

netsim/ansible/templates/bgp/cumulus_nvue.j2
Empty ```bgp.neighbors``` list throws an error
=> Cumulus NVUE: Avoid generating invalid YAML when there are no bgp neighbors

docs/module/bgp.md, docs/module/ospf.md, netsim/ansible/templates/bgp/cumulus_nvue.j2, netsim/ansible/templates/ospf/cumulus_nvue.j2, netsim/ansible/templates/routing/_redistribute.cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml
Small tweak to redistribute configs, still missing BGP in VRFs but will adjust when that gets added
Tested: ```integration/ospf/ospfv2/10-import.yml```
=> Cumulus NVUE: Generalized redistribute of OSPF/BGP/connected routes

docs/caveats.md, docs/module/evpn.md, netsim/ansible/templates/evpn/cumulus_nvue.j2, netsim/ansible/templates/vxlan/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml
I ran ```NETLAB_DEVICE=cumulus_nvue NETLAB_PROVIDER=libvirt ./device-module-test evpn```
8/14 tests validate ok. Some are failing due to missing bits that aren't part of EVPN (like missing 'redistribute connected' for VRFs); I could easily fix that, but this isn't the right place
Main things still missing:
* generalized redistribution of routes (separate PR)
* BGP in VRFs
=> Cumulus NVUE: Add EVPN support

docs/netlab/capture.md, docs/netlab/collect.md, docs/netlab/config.md, docs/netlab/connect.md, docs/netlab/down.md, docs/netlab/exec.md, docs/netlab/graph.md, docs/netlab/initial.md, docs/netlab/inspect.md, docs/netlab/report.md, docs/netlab/restart.md, docs/netlab/status.md, docs/netlab/validate.md, netsim/cli/__init__.py, netsim/cli/capture.py, netsim/cli/collect.py, netsim/cli/config.py, netsim/cli/connect.py, netsim/cli/down.py, netsim/cli/exec.py, netsim/cli/graph.py, netsim/cli/initial.py, netsim/cli/inspect.py, netsim/cli/report.py, netsim/cli/restart.py, netsim/cli/status.py, netsim/cli/validate.py, netsim/cli/version.py
* Add '--instance' parameter to most netlab commands
* Add 'change to instance directory' processing to the 'load snapshot' function
* Allow '--snapshot' parameter only in read-only commands that do not access lab devices
Closes #1784
=> Make '--instance' and '--snapshot' CLI parameters consistent

docs/module/vxlan.md, netsim/devices/cumulus_nvue.yml
While rebasing #1881 I accidentally canceled out these changes
=> Cumulus NVUE: Restore VXLAN support accidentally deleted by #1881

tests/topology/expected/isis-bfd-test.yml, tests/topology/expected/libvirt-clab-complex.yml, tests/topology/expected/vlan-access-links.yml, tests/topology/expected/vlan-access-neighbors.yml, tests/topology/expected/vlan-access-single.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vrf-links.yml, tests/topology/expected/vrf.yml, tests/topology/expected/vxlan-router-stick.yml, tests/topology/input/isis-bfd-test.yml, tests/topology/input/libvirt-clab-complex.yml, tests/topology/input/vlan-access-links.yml, tests/topology/input/vlan-access-neighbors.yml, tests/topology/input/vlan-access-single.yml, tests/topology/input/vlan-routed-vrf.yml, tests/topology/input/vrf-links.yml, tests/topology/input/vrf.yml, tests/topology/input/vxlan-router-stick.yml
* Replaced 'eos' device with 'non' in non-VLAN transformation tests
* Set EOS 'clab.image' to 'none' in VLAN transformation tests
Closes #1948
=> Remove dependence on EOS image from transformation tests

docs/plugins/bgp.session.md, netsim/extra/bgp.session/cumulus_nvue.j2, netsim/extra/bgp.session/defaults.yml
Used by EVPN test case ```13-vxlan-ebgp-allowas``` (passes)
=> Cumulus NVUE: Add initial limited bgp.session support for allowas_in

docs/module/evpn.md, netsim/ansible/templates/evpn/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml
Together with the other 2 PRs this now passes all EVPN tests except for ```21-bgp-ce-router``` (which is unsupported for now, due to lack of VRF BGP support)
=> Cumulus NVUE: Add EVPN symmetric IRB support

netsim/augment/addressing.py, netsim/providers/__init__.py, netsim/providers/clab.py, netsim/providers/libvirt.py, tests/errors/mgmt-subnet.log, tests/errors/mgmt-subnet.yml
clab and libvirt management IP addresses must be within the management subnet and the AF used on the node must be defined in the management pool.
Furthermore, libvirt nodes need IPv4 management address.
Closes #1957
=> Check the validity of management IP addresses

docs/caveats.md, docs/module/vrf.md, netsim/ansible/templates/bgp/cumulus_nvue.j2, netsim/ansible/templates/bgp/cumulus_nvue.macro.j2, netsim/ansible/templates/vrf/cumulus_nvue.j2, netsim/devices/cumulus_nvue.py
* Include BGP module config from VRF module template when needed
* Fix BGP RD configuration
* Fix ```advertise_loopback``` (also fixes https://github.com/ipspace/netlab/issues/1975 - I hit the same issue)
* Use custom NVUE snippet to configure FRR route leaking (adding caveat)
Tested: ```NETLAB_DEVICE=cumulus_nvue NETLAB_PROVIDER=libvirt ./device-module-test vrf -v```
- tests involving OSPFv3 fail (21,23 - not supported), but the rest all pass except for 16 (see #1971)
=> Cumulus NVUE: Support VRF route leaking

tests/integration/lag/01-l3-lag.yml
The current L3 LAG integration test uses OSPF and thus fails on Linux. This change replaces OSPF with static routing on the probe, testing just pure L3 forwarding functionality over LAG.
=> Change the L3 LAG integration test to use static routing

netsim/modules/gateway.yml
Fixes https://github.com/ipspace/netlab/issues/1981
The documentation does not list ```protocol``` as a valid node level attribute, and the code ignores it
=> Gateway: Remove node level protocol attribute

netsim/ansible/tasks/fetch-config/sonic.yml
this PR adds a SONiC-specific ansible playbook for use with the `netlab collect` process.
currently, when `netlab collect` command is run against a SONiC node, it only attempts to backup the FRR configuration. (and only the `frr.conf` file)  this extends the backup process to do the following:
- save both the SONiC and the FRR configs to their respective storage locations.
- capture the contents of the `/etc/sonic` directory to the host environment.
- capture the contents of the `/etc/sonic/frr` directory to the host environment.
an `frr` subdirectory is created in the `config_dir` to separate these configurations.  the current naming structure (`<config-file>-<inventory_hostname>`) is retained.
- all tests run clean.  though, in reviewing `tests/run-tests.sh` it doesn't look like ansible …
=> ansible playbook for SONiC platform backup (for use with `netlab collect`)

netsim/ansible/tasks/deploy-config/dellos10.yml, netsim/devices/dellos10.yml
Test: ```netlab up integration/vlan/41-vlan-bridge-native.yml -p clab -d dellos10 -v -s defaults.devices.dellos10.group_vars.netlab_save_config=False```
```
TASK [dellos10_config: deploying initial from /home/jeroen/Projects/netlab/netsim/ansible/templates/initial/dellos10.j2, save to startup=no]
s1# show diff running-configuration startup-configuration 
!
interface ethernet1/1/1
switchport mode trunk
switchport access vlan 700
switchport trunk allowed vlan 701
switchport
!
interface ethernet1/1/2
no ipv6 enable
description "[Access VLAN red] s1 -> h1"
switchport access vlan 700
switchport
!
etc.
```
Fixes https://github.com/ipspace/netlab/issues/1987 (for Dell OS10)
=> Dell OS10: Add 'netlab_save_config' (default:True) to control whether initial config is saved to startup

docs/module/bgp.md, netsim/ansible/templates/bgp/junos.j2, netsim/ansible/templates/vrf/junos.bgp.j2, netsim/devices/junos.yml
Support for BGP local-as and specific AF activate in JunOS.
Passed testing
- bgp/07
- bgp/08
- bgp/09
=> JunOS: support for BGP local-as

docs/caveats.md, docs/module/evpn.md, docs/module/vxlan.md, netsim/ansible/templates/evpn/vjunos-switch.j2, netsim/ansible/templates/vlan/vjunos-switch.j2, netsim/ansible/templates/vxlan/vjunos-switch.j2, netsim/devices/vjunos-switch.yml
This PR uses the "simplistic" default switch options to configure vxlan+evpn on vJunos-switch, which uses the so-called "Enterprise Style VLAN configuration".
Caveats documented.
Despite the drawback of using a single RD for all the announced routes (as required when using switch-options), the supported tests are passing succesfully.
Tests:
* vxlan/01-vxlan-bridging **OK**
* vxlan/02-vxlan-bridging-multinode **OK**
* vxlan/03-vxlan-irb **OK**
* vxlan/04-vxlan-irb-ospf **OK**
* vxlan/05-vxlan-router-stick **OK**
* vxlan/06-vxlan-bridging-multivendor **OK**
* vxlan/07-vxlan-bridging-v6only **not supported**
* vxlan/08-vxlan-alt-vtep **not supported**
* evpn/01-vxlan-bridging **OK**
* evpn/02-vxlan-asymmetric-irb **OK**
* evpn/03-vxlan-symmetric-irb **OK**
* evpn/04-vxlan-central-routing …
=> vJunos-switch: VXLAN and EVPN

netsim/tools/edgeshark.yml
The additional space of indent was causing a linefeed and the next docker command to be inserted into the ex variable. This caused the eval to see the string in ex as two lines of code to evaluate. The first line ended without a ' causing the SyntaxError  
run_command executing: ['bash', '-c', 'docker network inspect "ghost-in-da-edge" >/dev/null 2>&1 || docker network create "ghost-in-da-edge"']
Traceback (most recent call last):
File "/usr/local/bin/netlab", line 14, in <module>
netsim.cli.lab_commands(__file__)
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/__init__.py", line 356, in lab_commands
mod.run(sys.argv[arg_start:])   # type: ignore
File "/usr/local/lib/python3.10/dist-packages/netsim/cli/up.py", line 368, in run
run_up(cli_args)
File …
=> fix indent in list of docker commands in edgetools.yml

docs/plugins/bgp.session.md, docs/plugins/ebgp.multihop.md, netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/junos.j2, netsim/extra/ebgp.multihop/defaults.yml, netsim/extra/ebgp.multihop/junos.j2, netsim/extra/ebgp.multihop/plugin.py, tests/topology/expected/ebgp.utils.yml
Added an additional neigh attribute from the `ebgp.multihop` plugin to expose the entire source loopback data, in order to extract the IP addresses as well (and not only the source interface).
Updated transformation tests as well.
Tests passed:
* bgp.session/01-allowas-in.yml
* bgp.multihop/01-global.yml
* bgp.multihop/02-vrf.yml
=> JunOS: support for ebgp multihop and bgp allowas-in

docs/module/evpn.md, netsim/ansible/templates/bgp/junos.j2, netsim/ansible/templates/evpn/vjunos-switch.j2, netsim/devices/junos.py
Cleaner proposal instead of #2003 - no workaround needed here, and quirk implemented to allow only ebgp-on-ebgp, as per Juniper validated designs.
=> vJunos-switch: ebgp-ebgp evpn overlay

docs/caveats.md, docs/module/gateway.md, netsim/ansible/templates/gateway/junos.j2, netsim/devices/junos.yml, netsim/devices/vptx.yml, netsim/devices/vsrx.yml, tests/integration/gateway/01-anycast.yml
Anycast gateway support for JunOS.
Tested with vJunos-switch, vJunos-router.
On vPTX, reachability test is ok, but the gateway "virtual" MAC address is not used - hence the test is failing. Removing the support for anycast on vPTX for now.
vSRX, not supporting vlan irb cannot be tested.
(caveats documented)
Note: on vJunos-router the test required some additional sleep time before being able to ping hosts - added test param.
=> JunOS: support for anycast gateway

netsim/devices/cumulus_nvue.yml
Passes test ```bgp/09-vrf-localas```, couldn't find a documentation checkbox for it?
=> Cumulus NVUE: VRF local_as works given that the same BGP template is used

netsim/ansible/templates/mpls/frr.ldp.j2
Still passes all MPLS tests - without this, FRR complains about incomplete ipv6 configuration
=> FRR: Only configure active LDP address families

tests/integration/device-module-test
Every test generates a warning like this:
```
09:37:23 bgp/01-ebgp-session.yml: create(ok) /home/jeroen/Projects/netlab/tests/integration/./device-module-test:212: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
RESULTS[test]._timestamp = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
up(ok) /home/jeroen/Projects/netlab/tests/integration/./device-module-test:212: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
RESULTS[test]._timestamp = …
```
=> device-module-test: Replace deprecated utcnow()

netsim/ansible/templates/vlan/cumulus_nvue.j2
```_native_vlan``` is only set for routed interfaces, which aren't connected to the bridge. Need to look at ```vlan.native``` attribute instead
Since the untagged VLAN also gets added as a tagged VLAN, connectivity is not affected
=> Cumulus NVUE: Fix untagged vlan on br_default

netsim/ansible/templates/vlan/cumulus_nvue.j2, netsim/devices/cumulus_nvue.py
Better fix for https://github.com/ipspace/netlab/pull/2026
* Leave 'untagged' VLAN on the bridge untouched
* Declare routed native VLAN on mixed trunks as unsupported (test case 61 with all routed vlans works fine)
I considered changing the mode from "route" to "irb" under the hood, but I figured it's better to reject and let the user do that themselves (as it impacts IP address allocation for example)
Tested: ```NETLAB_DEVICE=cumulus_nvue NETLAB_PROVIDER=libvirt ./device-module-test -v vlan```
Confirmed that ```netlab up integration/vlan/63-vlan-mixed-native.yml -p libvirt -d cumulus_nvue -v -s vlans.blue.mode=irb``` works just fine
=> Cumulus NVUE: Reject routed native vlan on a mixed trunk as unsupported

tests/integration/bgp/08-ibgp-localas.yml
Added:
* A router within the DUT AS that advertises a real IBGP prefix
Extra checks:
* OSPF adjacency with intra-AS router (just to be on the safe side)
* Is the EBGP route propagated over IBGP local-as session valid? (is the next hop changed to self?)
* Is the real IBGP route propagated over IBGP local-as session? (is the local-as IBGP session acting as RR clients?)
* Is the next hop changed correctly for real IBGP route?
The extra checks will be upgraded from "warning" to "fatal" once we fix most of the templates. Also, we'll probably have to mark the IBGP local-as session as having RR clients on both ends.
Closes #1996
=> Add NH- and IBGP-propagation checks to IBGP local-as integration test

docs/netlab/exec.md, docs/netlab/inspect.md, docs/netlab/report.md, netsim/cli/_nodeset.py, netsim/cli/exec.py
=> Use common nodeset parsing function in netlab exec/inspect/report

netsim/ansible/tasks/deploy-custom-config.yml, netsim/defaults/paths.yml
The file search path for custom config templates included the bare filename because the config parameter could include a .j2 suffix.
That can result in a matching directory where we really want to find the .j2 template within the directory (#2051 provides an excellent example).
This modification removes the bare config filename from the search path and modifies the search logic -- if the config filename includes the '.j2' suffix, then we're searching only for that filename, otherwise we're searching for all potential combinations of things.
Fixes #2015
=> Treat custom config requests with .j2 suffix differently

netsim/providers/clab.yml
Without this, we get an error when trying to use `clab.restart-policy`:
```
[ERRORS]  Errors found in topology.yml
[ATTR]    groups: Incorrect node_group attribute 'restart-policy' in topology.groups.kagents.clab
[FATAL]   Cannot proceed beyond this point due to errors, exiting
```
=> Add restart-policy to allowed clab attributes

netsim/ansible/templates/initial/dellos10.vrf.j2, netsim/ansible/templates/vrf/dellos10.bgp.j2, netsim/ansible/templates/vrf/dellos10.ospfv2-vrf.j2
Tested: ```NETLAB_DEVICE=dellos10 NETLAB_PROVIDER=libvirt ./device-module-test -v vrf```
```vrf/16-vrf-bgp-community.yml``` continues to fail when run as ```device-module-test```
```
15:30:50 vrf/16-vrf-bgp-community.yml: create(ok) up(ok) config(ok) [WARNING]  Initial wait time extended by 30 seconds required by dellos10
[session]  Check BGP sessions with DUT [ node(s): x1,x2 ]
[PASS]     x1: Neighbor 10.1.0.1 (dut) is in state Established
[PASS]     x2: Neighbor 10.1.0.5 (dut) is in state Established
[PASS]     Test succeeded in 0.4 seconds
[prefix]   Check whether DUT propagates the beacon prefix [ node(s): x2 ]
[PASS]     x2: The prefix 172.0.42.0/24 is in the BGP table
[PASS]     Test succeeded in 0.2 seconds
[std_comm] Check standard community propagation on VRF EBGP sessions [ …
```
=> Dell OS10: Move route-target setting to VRF module, only when bgp is used

docs/module/ospf.md, docs/module/routing.md, netsim/ansible/templates/ospf/dellos10.macro.j2, netsim/ansible/templates/ospf/dellos10.ospfv2.j2, netsim/ansible/templates/ospf/dellos10.ospfv3.j2, netsim/ansible/templates/vrf/dellos10.ospfv2-vrf.j2, netsim/devices/dellos10.py, netsim/devices/dellos10.yml
* Tweak OSPF timers to avoid instabilities in FRR neighbors during ```ospf/ospfv2/20-default.yml```
* Add quirk about limited attribute support
Testing: ```NETLAB_DEVICE=dellos10 NETLAB_PROVIDER=libvirt ./device-module-test -v ospf/ospfv2```
+ Test ```ospf/ospfv2/20-default.yml``` now passes with warnings (no support for cost on originated default route)
+ Test ```ospf/ospfv2/22-default-vrf.yml``` passes
=> Dell OS10: Add support for originated default routes in OSPF

tests/integration/evpn/02-vxlan-asymmetric-irb.yml
The original calculation of default gateways in VLANs resulted in every host using the nearest switch as the default GW. With the new approach to default gateways, all hosts in an IP subnet get the same default gateway, destroying the whole idea of asymmetrical IRB.
The only correct solution out of this conundrum is the use of anycast gateway that ensures we always get routing on ingress.
Interestingly, some devices (Junos, SR Linux) fail to route packets between VLANs in asymmetrical IRB scenario unless the hosts ping the default gateway first (effectively priming the ARP cache). Go figure :(
Closes #1930
=> Use anycast gateway in EVPN asymmetric IRB integration test

netsim/augment/links.py, netsim/devices/junos.py, netsim/modules/vlan.py, netsim/tools/graphite.py, netsim/utils/strings.py
This is a pure cleanup/consistency change, ensuring we can always use expressions in string formats.
Closes #1914
=> Replace calls to string.format with strings.eval_format

netsim/modules/bgp.py, tests/topology/expected/bgp-vrf-local-as.yml, tests/topology/expected/ebgp.utils.yml, tests/topology/expected/vrf-igp.yml, tests/topology/expected/vrf-routing-blocks.yml, tests/topology/expected/vrf.yml, tests/topology/input/vrf.yml
This makes the data structures more consistent between VRF and global BGP neighbors and makes it easier to write the device configuration templates as we no longer have to check whether the 'activate' dictionary is defined.
=> Add the 'activate' dictionary to VRF EBGP neighbors

netsim/ansible/templates/bgp/junos.j2, netsim/ansible/templates/evpn/vjunos-switch.j2, netsim/ansible/templates/mpls/junos.mplsvpn.j2
Junos cannot create a BGP neighbor that has no active AF. As a workaround, this change shuts down the neighbors that have no active IPv4/IPv6 AF, and reenables them when they're used for EVPN or MPLS/VPN AF.
Closes #2007, replaces #2009 and #2010
=> Shutdown the unused BGP neighbors on Junos

netsim/ansible/templates/vrf/vyos.bgp.j2
Fix #2071
```
root@hippo:~/GIT_H/netlab/tests/integration/vrf# netlab validate
[session]    Check EBGP sessions with DUT [ node(s): r1,r2,r3,r4 ]
[PASS]       r1: Neighbor 10.1.0.1 (dut) is in state Established
[PASS]       r2: Neighbor 10.1.0.5 (dut) is in state Established
[PASS]       r3: Neighbor 10.1.0.9 (dut) is in state Established
[PASS]       r4: Neighbor 10.1.0.13 (dut) is in state Established
[PASS]       Test succeeded in 1.1 seconds
[pfx_red]    Check DUT loopback BGP prefix in red VRF [ node(s): r1,r2 ]
[PASS]       r1: The prefix 10.0.0.42/32 is in the BGP table
[PASS]       r2: The prefix 10.0.0.42/32 is in the BGP table
[PASS]       Test succeeded in 0.5 seconds
[pfx_red_id] Check the router ID on the DUT loopback BGP prefix in red VRF [ node(s): r1,r2 ]
[PASS]       r1: …
```
=> VyOS: fix BGP router-id on VRF

netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/devices/srlinux.py
This is a minimal set of changes that ensures the BGP address families are activated as expected -- the address families that are not explicitely enabled are disabled.
This approach results in a situation where a BGP neighbor might not have any address families. That's rejected by SR Linux, so we need an extra device quirk that cleans up the neighbor transport IP addresses based on the AFs we'll need with the neighbor.
Fixes #2059
=> Fix the SR Linux BGP AF activation

netsim/ansible/templates/bgp/dellos10.macro.j2
It looks like Dell OS10 activates all address families configured in the BGP process for all BGP neighbors. Anything you don't want to have has to be explicitly deactivated.
Fixes #2050
=> Fix Dell OS10 BGP address family activation

docs/module/vrf.md, netsim/modules/vrf.py, tests/errors/vrf-loopback-global.log, tests/errors/vrf-loopback-global.yml, tests/integration/vrf/03-multi-vrf-loopback.yml, tests/integration/vrf/04-multi-vrf-loopback-ipv6.yml, tests/integration/vrf/22-multi-vrf-bgp-ipv6.yml
=> 'loopback' attribute in global VRF definition must be a bool

tests/integration/evpn/02-vxlan-asymmetric-irb.yml, tests/integration/evpn/03-vxlan-symmetric-irb.yml, tests/integration/evpn/anycast-check/plugin.py
* Use Arista EOS as a probe device in symmetric IRB test
* Use a plugin to remove the anycast gateway functionality for devices that do not support it (so they can still have a chance of passing the IRB tests, although with reduced functionality)
=> Use anycast gateway in EVPN (a)symmetric IRB tests

netsim/cli/connect.py, tests/integration/device-module-test
This extra parameter allows the integration tests to be run from GitHub PR comments
=> Add "integration" parameter to device-module-test

docs/caveats.md, docs/example/linux.md, docs/labs/linux.md, docs/links.md, docs/nodes.md, netsim/augment/nodes.py, netsim/daemons/bird.yml, netsim/daemons/dnsmasq.yml, netsim/defaults/attributes.yml, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/devices/ios.yml, netsim/devices/linux.yml, netsim/devices/none.yml, tests/errors/ia-node.log, tests/errors/ia-node.yml, tests/topology/expected/vlan-access-single.yml, tests/topology/input/vlan-access-single.yml
* Each device (apart from routers) must have its valid roles defined
* A node can become a host only if the device allows the 'host' role
* Static routing for hosts checks the 'mgmt_vrf' feature and uses either default route or specific routes for address pool prefixes.
Note:
* We cannot use 'mgmt_vrf' for FRR containers, as we don't know whether we'll manage to load the 'vrf' module during the initial configuration
=> Make the behavior of hosts more controlled

netsim/defaults/hints.yml, netsim/devices/arubacx.py, netsim/devices/asav.py, netsim/devices/cumulus.py, netsim/devices/cumulus_nvue.py, netsim/devices/eos.py, netsim/devices/iosv.py, netsim/devices/iosvl2.py, netsim/devices/junos.py, netsim/devices/linux.py
Changed 'log.error' to 'report_quirk' for Aruba, ASAv, CL NVUE, CL, EOS, IOSv, IOSvL2, Junos, and Linux
=> Use report_quirk to for consistent reporting of device quirks

docs/platforms.md, netsim/ansible/templates/initial/frr.j2, netsim/devices/frr.yml, tests/topology/expected/clab-attributes.yml, tests/topology/expected/device-module-defaults.yml, tests/topology/expected/node.clone-plugin.yml, tests/topology/expected/vlan-routed-multiprovider.yml, tests/topology/expected/vlan-routed-vrf.yml
* Enable SLAAC and RA-derived default route
* Disable IPv4 and IPv6 forwarding
* Disable RA generation in host mode
* Minor tweaks to the interface config process (ifdown at start, ifup at the end of interface sysctl modification)
=> Implement 'host' functionality for FRRouting

netsim/augment/nodes.py, netsim/defaults/attributes.yml, tests/errors/dup-mgmt-addr.log, tests/errors/dup-mgmt-addr.yml
Closes #1959
Note: it was too cumbersome to tweak the management IP logic (and all its exceptions) into something that could be used with regular interface-on-link IP assignment. Adding logic to handle bools and ints was easier ;)
=> Accept 'int' and 'bool' values for management IP addresses

netsim/augment/__init__.py, netsim/augment/main.py, netsim/augment/nodes.py, netsim/roles/__init__.py, netsim/roles/host.py, netsim/roles/router.py
* Create 'roles' subsystem
* Initialize the subsystem as a set of role-specific plugins appended to the topology plugins
* Move loopback creation/addressing into 'router' role plugin
* Move default static route processing into 'host' role plugin
=> Refactor the role-specific node transformation into a separate subsystem

netsim/ansible/templates/gateway/frr.j2, tests/integration/gateway/01-anycast.yml
Based on the detective work by @jbemmel in #2099 (thank you!)
Also: modify the anycast integration test to check for the ARP entry from a host that pings the anycast GW
Fixes #2099
=> FRR: fix the ARP sysctl settings on VARP/anycast GW MACVLAN interface

netsim/ansible/templates/initial/srlinux.j2, netsim/augment/links.py, tests/topology/expected/vrf-leaking-loop.yml
For example:
```
links:
- router01:
router02:
name: 'My Description'
```
Also set interface descriptions on parent interfaces on SR Linux.
For example:
```
--{ + running }--[  ]--
A:router01# info interface ethernet-1/1
interface ethernet-1/1 {
description "My Description"
admin-state enable
subinterface 0 {
description "My Description"
ipv4 {
admin-state enable
address 172.17.0.33/30 {
primary
}
}
}
}
```
I'm happy to break up this PR if you'd prefer.
=> Allow interface name to be set on a per-interface basis

docs/node-roles.md, docs/nodes.md, docs/platforms.md, netsim/devices/eos.yml, netsim/devices/ios.yml, netsim/modules/routing.py, netsim/roles/__init__.py, netsim/roles/bridge.py
This is the initial implementation of the 'bridge' node role:
* Bridge interfaces without a VLAN parameter are assigned to the default VLAN (name/id defined as a topology const)
* The default value of 'vlan.mode' for a bridge device is 'bridge' (not IRB)
* Multi-access link with a single attached bridge are expanded into a series of point-to-point links
Note: any device implementing the VLAN configuration module could potentially be a bridge. Whether that makes sense is a totally different question.
Future plans after this PR:
* Per-node default VLAN name/ID (can be used to implement multiple independent bridging domains)
* Integration test (at least on the platform level, it might not make sense to have it for individual devices)
=> 'bridge' node role: a simple layer-2 bridge

netsim/ansible/templates/stp/frr.j2, netsim/ansible/templates/vlan/frr.j2, netsim/ansible/templates/vxlan/frr.j2
Newer FRR images no longer have [long deprecated 'brctl' support](https://lwn.net/Articles/703776/)
=> FRR: Replace obsolete 'brctl' commands with modern equivalents

netsim/daemons/bird/bird.j2
Fixes https://github.com/ipspace/netlab/issues/2102
Also sets link MTU in RA messages; test ```initial/04-mtu``` passes too
=> Bird: Add IPv6 RA config

netsim/daemons/bird/bgp.j2
Tested: ```netlab up integration/bgp/08-ibgp-localas.yml -d bird -p clab``` -> all 11 cases pass
=> Bird: Fix test case bgp/08-ibgp-localas next hop processing

netsim/ansible/templates/initial/cumulus.j2
Triggered by https://github.com/ipspace/netlab/pull/2114
May not be strictly needed, but just to be consistent
=> Cumulus: Enable ipv6 on extra loopbacks too

netsim/modules/vrf.py, tests/topology/expected/mpls-vpn-simple.yml, tests/topology/expected/vrf-igp.yml, tests/topology/expected/vrf-loopback.yml, tests/topology/expected/vrf-routing-blocks.yml, tests/topology/expected/vrf.yml
This change exposes the VRF loopback interfaces to all post-transform hooks. The only visible side effect is the addition of 'bgp.advertise' flag as the BGP post-transform hook sees a new interface. That would cause a new 'network' statement in the device configurations, but no extra routes as most devices already do 'redistribute connected' into VRF BGP.
=> Fix: Move VRF loopback creation to post_link_transform hook

netsim/modules/_routing.py, tests/errors/vrf-unnumbered.log, tests/errors/vrf-unnumbered.yml
While it's possible to run BGP over unnumbered VRF interfaces borrowing
an IPv4 address over a global loopback (because no IPv4 addresses are
involved), that does not work with most IGPs.
This change (based on work by @jbemmel in #2119/#2120) adds a check
for the source of the unnumbered IPv4 address to VRF-specific IGP
processing.
Replaces #2120, closes #2119
=> Check source VRF of IPv4 addresses used on unnumbered VRF interfaces

docs/caveats.md, docs/module/routing.md, docs/plugins/bgp.policy.md, docs/plugins/bgp.session.md, netsim/ansible/templates/routing/_prefix_list_junos.j2, netsim/ansible/templates/routing/_route_policy_junos.j2, netsim/ansible/templates/routing/junos.j2, netsim/devices/junos.py, netsim/devices/junos.yml, netsim/extra/bgp.policy/defaults.yml, netsim/extra/bgp.policy/junos.j2, netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/junos.j2, tests/integration/routing/21-static-vrf.yml
This PR introduces **foundations and basic working support** for routing policies (and static routing) in JunOS.
Despite it has a lot of quirks (and caveats), it works for basic use cases.
Sooner or later the quirks/caveats will be solved by changing the policy logic (again as a quirk), but for now we have something which works, at least with basic features, in a short time :)
Tested with routing integration test cases; 
test cases which trigger quirks have been validated in terms of "applied config", but of course test validation fails.
NOTES:
* *10-match-prefix.yml* passes as well with the workaround set by the quirk (and disabling the quirk in the topology), but the workaround does not cover all the test cases - see documented caveats.
* *21-static-vrf.yml* and *23-static-indirect.yml* …
=> JunOS: initial/foundation implementation for routing (and bgp) policies

netsim/daemons/bird/ospf.j2
Fixes https://tests.netlab.tools/bird/clab/ospf/ospfv3/06-lb-prefix.yml-validate.log
=> Bird: Advertise IPv6 loopback as /128 in OSPF

netsim/daemons/bird.yml, netsim/daemons/bird/bgp.j2, tests/integration/bgp/05-community.yml
Fixes https://tests.netlab.tools/bird/clab/bgp/05-community.yml-validate.log
=> Bird: Filter BGP communities per neighbor type

docs/plugins.md, docs/plugins/firewall.zonebased.md, netsim/extra/firewall.zonebased/defaults.yml, netsim/extra/firewall.zonebased/plugin.py, netsim/extra/firewall.zonebased/vsrx.j2, netsim/extra/firewall.zonebased/vyos.j2, tests/integration/firewall.zonebased/01-default-zone-policy.yml
Starting point for zone-based firewall, for now supporting default zone-to-zone policies (with `permit`/`deny` actions)
The plugin has been put with `firewall.` as prefix, as in the future we may want to add additional "subplugins" (i.e., `firewall.nat`).
Created basic integration test as well.
Supported on:
* vSRX
* VyOS
=> Initial implementation of firewall.zonebased plugin

netsim/extra/bgp.policy/arubacx.j2
=> ArubaOS-CX: clear all bgp session (soft) after policy config

netsim/ansible/templates/routing/_route_policy_vyos.j2
=> VyOS: routing policy shall consider only ipv4 and ipv6 af

docs/node-roles.md, netsim/roles/bridge.py
A multi-access link without a VLAN attribute is usually a layer-3 segment. Our implementation of bridge-assisted multi-access links has to reflect that -- we have to create a separate VLAN for each such link.
=> Bridge-assisted multi_access links are isolated bridging domains

tests/integration/gateway/02-vrrp.yml, tests/integration/gateway/linkdown/linux.j2
The modified VRRP integration test uses a bridge node to implement the VRRP segment, resulting in a more realistic test scenario in which a link (bridge interface) failure triggers a VRRP failover and eliminating the potential impact of Arista EOS PHY control messages.
Obviously, we could implement the bridge node as a Linux node with a VLAN module, but it was more fun using the new "multi-access link implemented with a bridge node" functionality.
=> Use a bridge node in the VRRP integration test

netsim/ansible/templates/initial/vyos.j2
LLDP FUBAR: different syntax for version 1.4 (used by vagrant box vyos/current) and 1.5
Fix #2160
=> VyOS: lldp intf disable inconsistency between 1.4 and 1.5

docs/dev/transform.md, netsim/augment/groups.py, netsim/augment/main.py, tests/errors/group-invalid-attr-type.log, tests/errors/groups-recursive.log, tests/errors/invalid-group-element.log, tests/errors/validate-list.log
The group data cannot be validated before the 'init' hooks are executed, forcing the 'init' hooks that deal with groups to do redundant checks to ensure the data they're working with is sane.
This change splits the sanity checks performed at the same time as node- and link sanity checks from the in-depth data validation which is performed after 'init' hooks
=> Split group sanity checks from in-depth data validation

netsim/modules/routing.py, tests/topology/expected/rp-clist-expansion.yml, tests/topology/input/rp-clist-expansion.yml
The routing.community objects start as a list of rules but get transformed into a dictionary late in the transformation process to simplify the config templates.
However, the transformation process was also triggered by a routing policy reference, and later executed again when we processed the node clists, resulting in unexpected data structure.
This fix checks whether a clist was already transformed before doing the transformation. It also fixes the common code used in as-path and clist import to recognize 'regexp' attribute (which can never appear in as-path object, so we're OK there ;)
Fixes #2155
=> Fix double transformation for routing.community objects

docs/dev/transform.md, netsim/augment/main.py, netsim/modules/__init__.py
This PR adds another way of calling module hooks: the "hooks" list in the module definition. The primary use case are hooks that have to be called before the topology data is validated and the "modules" list is finalized.
The "normalize" execute_module_hooks function is called before the data validation starts, giving the modules using it (planned: routing) the ability to do pre-validation data transformation.
See the discussion in #2154 for more details (hint: this implements the 'insane' option described in that discussion)
While implementing that functionality, I also refactored the whole module hook calling subsystem and removed duplicate code.
=> Implement static (defaults-driven) module hooks

netsim/modules/routing.py, netsim/modules/routing.yml, tests/errors/rp-invalid-data-types-1.log, tests/errors/rp-invalid-data-types-1.yml, tests/topology/expected/rp-clist-expansion.yml, tests/topology/input/rp-clist-expansion.yml
The 'normalize' hook is the only hook that can be called before the group data is validated, so it has to be used if we want to support shortcut routing object definitions in group data.
Closes #2154 (see that issue for more details)
=> Expand routing object shortcut definitions with the 'normalize' hook

netsim/ansible/tasks/reload-config/srlinux.yml
The 'reload-config' task list uses Docker to copy target configuration into SR Linux container, then loads the file into candidate config and commits/saves it.
Closes #2173
=> Implement 'reload config' for SR Linux

netsim/ansible/templates/initial/linux/ubuntu.j2, netsim/ansible/templates/initial/linux/vanilla-ifconfig.j2
=> Fix: always set 'disable_ipv6' flag on Linux interfaces

docs/defaults.md
this corrects the reference to the system-wide defaults file in the documentation.
=> update reference to system defaults.yml

netsim/augment/devices.py, netsim/augment/nodes.py, netsim/cli/show_commands/module_support.py, netsim/cli/show_commands/modules.py, netsim/devices/linux.yml, netsim/modules/__init__.py, tests/errors/module-device-provider.log, tests/errors/module-device-provider.yml
This change extends the "features" dictionary to device/provider data, allowing us to specify platform-specific
module support (for example, VLANs run only on Linux containers) or provider-specific functionality
(for example, Arista EOS cannot run DHCP clients in containers).
=> Implement provider-specific module/role support

netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/ansible/templates/routing/_redistribute.srlinux.j2, netsim/ansible/templates/routing/srlinux.j2, netsim/devices/srlinux.py, netsim/devices/srlinux.yml
* Fixes extended community filtering
Note: not backwards compatible...
Fix: https://github.com/ipspace/netlab/issues/2058
=> SR Linux: Changes to support release 25.3.1

netsim/ansible/templates/initial/srlinux.j2
One would think that the NOS could derive the correct intended type...but no, not this one
Considered adding a test case to ```integration/initial/01-interfaces``` but I don't think any other platform suffers from this particular stupidity
=> SR Linux: Need to explicitly specify type as link-local for ipv6 addresses that are... link-local (duh)

docs/module/bfd.md, docs/plugins/bgp.session.md, netsim/ansible/templates/bfd/dellos10.j2, netsim/devices/dellos10.yml, netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/dellos10.j2
* BFD timers and BFD on BGP sessions
* BGP passwords, timers, allow AS in, remove private AS, default originate
Tested: ```device-module-test bgp.session -d dellos10 -p libvirt -v```
=> Dell OS10 bgp features

netsim/daemons/dnsmasq/Dockerfile
Still builds the same dnsmasq version 2.90
=> Dnsmasq: Use same Ubuntu base image 24.04 as other daemons (bird)

docs/netlab/clab.md, netsim/cli/clab_actions/build.py, netsim/daemons/bird/Dockerfile.v3
At some point we might decide to make v3 the default, and rename current ```Dockerfile``` to ```Dockerfile.v2```
=> Add support for building multiple different versions of daemons, starting with Bird v3

docs/plugins/bgp.session.md, netsim/daemons/bird/bgp.j2, netsim/extra/bgp.session/defaults.yml, tests/integration/bgp.session/05-gtsm.yml
* Configure retry timer as 10 seconds, default 120s takes too long
* Update test case to set role: router (test assumes a loopback interface)
Modified the test case to verify ibgp working too; bird takes an unreasonably long time to accept the peers, but eventually does. See #2198 for an issue I encountered
=> Bird: Add bgp gtsm support

netsim/modules/bfd.py, netsim/modules/isis.py, tests/topology/expected/isis-bfd-test.yml
The multi-protocol BFD code was referencing igp.af data structures before they were created, resulting in IGP data with no usable AF. Had to move the BFD call to a later step in the IS-IS post-transform.
Also, the multi-protocol BFD code created IGP data on interfaces that were already fully processed, so that bit of code needed further cleanup.
=> Fix: Multi-protocol BFD whacked the IGP AF information

docs/module/ospf.md, docs/platforms.md, netsim/ansible/templates/initial/arubacx.j2, netsim/devices/arubacx.yml
Passing tests:
* ospf/ospfv2/05-unnumbered.yml
* ospf/ospfv3/05-unnumbered.yml
=> ArubaOS-CX: support for unnumbered interfaces (and ospf unnumbered)

netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/plugin.py, tests/topology/expected/removed-attr-inheritance.yml, tests/topology/input/removed-attr-inheritance.yml
* Instead of 'get from interface or node' code, use shared 'get_effective_module_attribute' functionality which now includes the 'removed_attribute' support.
* Define 'description' attribute (to be implemented in another PR) to simplify tracking of test result data ;)
* Add a transformation test checking out all inheritance combinations
Fixes #2198
=> Use shared functionality to computed BGP session attributes

netsim/augment/links.py, netsim/data/types.py, netsim/modules/routing.yml, tests/errors/addr-errors-intf.log, tests/errors/addr-errors-intf.yml, tests/errors/addr-errors.log, tests/errors/addr-pool-errors.log, tests/errors/addr-pool-errors.yml, tests/run-xerr.sh
Also:
* Split the address validation error test in prefix- and link/addr tests
* Fix the error messages in augment/links to use more_* arguments
* Change the static route prefix attribute type from 'subnet_prefix' to 'prefix'
Fixes #2229
=> Check reserved ranges during IPv4/IPv6 address/prefix validation

netsim/defaults/attributes.yml, tests/topology/expected/addressing-ipv6-prefix.yml
This removes nonsensical values such as 'True' and string-type '127'
=> The 'prefix6' attribute should be treated just like the 'prefix' attribute

docs/module/routing.md, netsim/ansible/templates/routing/frr.j2, netsim/devices/frr.yml, netsim/modules/routing.py, netsim/modules/routing.yml, tests/integration/routing/07c-community-delete-list.yml
Also:
* Use this functionality to emulate 'set.community.delete'
* FRR proof-of-concept implementation
Replaces #2162
=> Implement 'delete communities matching a list' in routing policies

netsim/extra/bgp.session/dellos10.j2
Fixes [13-vxlan-ebgp-allowas](https://github.com/ipspace/netlab/blob/dev/tests/integration/evpn/13-vxlan-ebgp-allowas.yml)
=> Dell OS10: Fix allow-as-in for EVPN neighbors (test case 13)

netsim/ansible/templates/vlan/cumulus.j2, netsim/ansible/templates/vxlan/cumulus.j2
This seems to be the fix for #2254 -- I have no idea why things worked in the past, stopped working after changes mentioned in #2254, and behaved randomly afterwards. The root cause seems to be access ports stuck in **learning** phase forever (so clearly a bug somewhere in Linux networking code, but who's counting).
The only other significant thing that changed is b02bc24, but that should not have impacted interface configuration.
Anyway, let's wait until I can run the full suite of integration tests.
=> Cumulus Linux: Change STP parameters on bridge and VXLAN interface

docs/node-roles.md, docs/nodes.md, netsim/ansible/templates/initial/arubacx.j2, netsim/ansible/templates/initial/dellos10.j2, netsim/ansible/templates/initial/routeros.j2, netsim/ansible/templates/initial/routeros7.j2, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/initial/vyos.j2, netsim/augment/links.py, netsim/augment/nodes.py, netsim/defaults/attributes.yml, netsim/roles/router.py, tests/topology/expected/dhcp-vlan.yml, tests/topology/expected/dual-stack.yml, tests/topology/expected/unnumbered.yml, tests/topology/input/dhcp-vlan.yml, tests/topology/input/dual-stack.yml, tests/topology/input/unnumbered.yml
This is the main logic for fixing #2261 and #2266. @jbemmel: would appreciate if you could double-check it.
Next, I have to create test cases to validate the edge conditions (**loopback.ipv4** on host, **loopback: True** and **loopback: False** work correctly), and finally run all known devices through these test cases to verify that the configuration templates don't break.
=> Allow loopback interfaces on all node types when specified by the user

netsim/modules/lag.py, tests/topology/expected/lag-mlag-m_to_m.yml, tests/topology/input/lag-mlag-m_to_m.yml
Fixes #2246
Tested: ```./device-module-test -d eos -p clab lag```
=> LAG: Accept user specified lag.ifindex, also when listed in descending order

netsim/augment/components.py, netsim/augment/links.py, tests/errors/component-links.log, tests/errors/component-links.yml, tests/errors/link-invalid-format.log, tests/errors/link-invalid-format.yml
The code introduced with netlab components accepted any name in the link string definition as long as a valid node name was its prefix. That check was upgraded to 'node name + _ but only for components'
Furthermore, the content of 'links' list is rechecked after the component expansion to ensure the node names are correct (it's impossible to do the final check before components are expanded).
Fixes #2273
=> Fix: implement stricter checks on node names on links

netsim/augment/links.py, tests/platform-integration/components/01-links.yml
This fix moves the 'valid node name' processing from #2280 to a shared function that is used by all link format validation code.
Fixes #2284
=> Fix: accept component nodes in all link formats

netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/initial/linux/hosts-common.j2
* Replace the '_' with '-' in hostnamectl call to get the same hostname as on Linux (affects only FRR VMs)
* Add entries with '-' for every host with '_' in its name to the /etc/hosts file (affects all Linux-based nodes)
Fixes #2286
=> Fix DNS resolution failures on Debian nodes with '_' in node name

MANIFEST.in
Enable the inclusion of sub directories under netsim/daemons in the distribution artifacts. This includes the  Dockerfiles and jinja2 templates for bird and dnsmasq.
=> Update MANIFEST.in to include netsim/daemons sub directories

netsim/devices/sros.yml
One has to admire the incredible audacity of a developer who sets 'features.bgp.ipv6_lla' flag to True while leaving a "TODO BGP unnumbered" comment in the configuration template.
Alas, faced with either implementing the missing functionality or disabling the feature, I decided to take the easy way out.
A brave soul wanting to revert this decision is most welcome to submit a working PR.
=> Fix: SR-OS does not support unnumbered EBGP sessions

netsim/ansible/templates/bgp/sros.gnmi.macro.j2, netsim/ansible/templates/bgp/sros.j2
SR-OS implementation advertised all known prefixes to IBGP neighbors. This fix uses two policies for IBGP session: next-hop-self (for EBGP routes) and default_export (to match prefixes)
=> SR-OS: Control prefix origination for IBGP neighbors

netsim/ansible/templates/bgp/sros.gnmi.macro.j2
Similar to the Junos kludge, we have to disable SR-OS BGP neighbors if they have no active address families. That has to be fixed (the neighbor put into 'enabled' state) in the EVPN and MPLS modules, but they're broken at the moment anyway.
=> SR-OS: Disable BGP neighbor with no active AFs

tests/integration/bgp.policy/31-med.yml, tests/integration/bgp.policy/32-med-unnumbered.yml, tests/integration/bgp/13-ipv6-ibgp-rr.yml, tests/integration/bgp/14-ipv6-originate.yml, tests/integration/bgp/defaults-ipv6.yml, tests/integration/routing/03-med-out.yml
Nokia SR-OS does not accept anything but /128 as the IPv6 on the system loopback interface (probably a smart choice). Instead of fighting that behavior, several integration tests were modified to use the /128 loopback IPv6 prefix on the device under test.
=> Use /128 IPv6 loopback in BGP integration tests

netsim/ansible/templates/bgp/sros.gnmi.macro.j2, netsim/ansible/templates/evpn/sros.j2
Yet again, the "let's leave untested TODO stuff in config templates" mentality caused the total configuration failure of all EVPN scenarios. It turns out that trying to configure VXLAN and MPLS EVPN under the same BGP instance doesn't work.
However, as they say, third time is a charm, I hope that's it.
The minimal fixes in this patch got L2 EVPN to work. More advanced scenarios are still failing with config or validation failures.
Also: applying decent global BGP policies to VPN routes turned out to be a bad idea.
=> SR-OS: Fix L2 EVPN configuration

netsim/ansible/templates/bgp/sros.j2, netsim/ansible/templates/evpn/sros.j2
The "EVPN-over-EBGP" configuration template had no chance of working outside of the most basic SR-OS-as-leaf scenario:
* There were YAML errors in BGP configuration when EVPN was enabled on IBGP and EBGP sessions
* SR-OS could not be used as a spine node because it did not propagate EVPN routes (missing 'inter-as-vpn') or changed the next hop (missing 'next-hop-unchanged')
=> SR-OS: Fix EVPN-over-EBGP when SR-OS is a spine node

netsim/ansible/tasks/reload-config/_copy_config.yml
Updating _copy_config.yml for SCP to use the "-O" option, to avoid using SFTP in transferring files to a Cisco IOS-XE router and prefer SCP instead.
=> Fix: Configuration reload in Cisco IOS-XE devices fails when copying

netsim/ansible/templates/initial/sros.j2, netsim/devices/sros.py
A combination of SVI VLAN and routed VLAN on the same interface requires "hybrid" port mode due to the way routed VLAN interfaces are configured on SR-OS (they are in "router Base", not in IES service).
This commit moves the calculation of port mode into SR-OS device module, making it much easier to understand and debug than the attempts to reverse-engineer it in the Jinja2 template.
=> SR-OS: Set correct port mode for all VLAN combinations

netsim/ansible/templates/mpls/junos.ldp.j2
Following @nmodena's advice, removing `bgp-igp-both-ribs` from default MPLS config.
=> JunOS: remove MPLS bgp-igp-both-ribs

docs/module/ospf.md, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/devices/ios.yml, netsim/devices/none.yml, tests/integration/ospf/ospfv2/10-import.yml, tests/integration/ospf/ospfv3/10-import.yml, tests/integration/plugin/static_import/plugin.py
The existing configuration templates work, the only change is the extra keyword in the 'ospf.import' feature flag.
The main modifications of this PR are the changes to the integration tests that use a new 'static_import' plugin to adjust the test based on whether the DUT supports static routes and redistribution of static routes into OSPF.
=> Import (redistribute) static routes into OSPF on EOS/FRR/IOS

docs/caveats.md, docs/module/evpn.md, netsim/ansible/templates/evpn/sros.j2, netsim/devices/sros.py
Previous implementation created an extra VPLS service for the transit VNI, resulting in EVPN-IFF routes that could not be (easily) exported into other routing protocols.
The VPRN EVPN instance results in EVPN-IFL routes which are easily matched in export routing policies.
=> SR-OS: Implement EVPN transit VNI within the VPRN (VRF) service

docs/caveats.md, docs/labs/fortios.md, docs/labs/libvirt.md, docs/platforms.md, netsim/ansible/tasks/fortinet.fortios.fortios/initial.yml, netsim/devices/fortios.yml
After playing with the FortiGate, I've successfully reproduced the creation of the Vagrant box using the current latest versions (`7.4.8` and `7.6.3`)
I have noticed a weird thing, on `7.4.8`, the MTU on the link between the fw and the device in front, was set to 9500, but it is 1500 on the `7.6.3`. I've only noticed when realising OSPF was configured but not established.
I've added a small fix for this in the yml file, so the MTU will be defaulted to 1500 on `fortios`, unless set in the interface parameter (not in node).
This is the PR I've created, with some documentation updates (caveats and platforms). Please let me know if I haven't followed the PR process correctly, or anything else I may have done incorrectly, I'm still trying to figure out how to correctly work with fork...
I have …
=> fortios - mtu and docs

docs/module/routing.md, netsim/ansible/templates/routing/cumulus_nvue.j2, netsim/devices/cumulus_nvue.yml
Testing:
```
jeroen@j:~/Projects/netlab/tests/integration$ ./device-module-test -d cumulus_nvue -p libvirt --limit=*static routing
Pre-test cleanup: 
13:09:37 routing/20-static.yml: create(ok) up(ok) config(ok) validate(ok) cleanup(ok) OK
13:11:43 routing/21-static-vrf.yml: create(ok) up(ok) config(ok) validate(ok) cleanup(ok) OK
13:13:57 routing/22-static-inter-vrf.yml: create(ok) up(ok) config(ok) validate(ok) cleanup(ok) OK
13:15:59 routing/23-static-indirect.yml: create(ok) up(ok) config(ok) validate(ok) cleanup(ok) OK
13:18:13 routing/24-static-indirect-inter-vrf.yml: create(FAIL) 
13:18:14 routing/25-static-discard.yml: create(ok) up(ok) config(ok) validate(ok) cleanup(ok) OK
```
24 fails due to lack of OSPFv3 support.
Also tested ```ospf/ospfv2/10-import.yml```, …
=> Cumulus NVUE: Implement static routing

netsim/ansible/tasks/reload-config/eos.yml
Somehow the ability to do scp is no longer enabled by default
Fixes #2407
=> Fix EOS config reload

docs/plugins/mlag.vtep.md, netsim/extra/mlag.vtep/plugin.py, tests/integration/mlag.vtep/01-vxlan-bridging.yml
* Set 'linkindex' on created stub link
* Adjust test to check that VTEP loopback gets advertised in OSPF
* Use `loopback.pool` if specified, to enable per-site loopback ranges
=> Mlag vtep plugin enhancements

docs/netlab/connect.md, docs/netlab/report.md, netsim/reports/nodes.j2
This is a potential solution for #2418:
* netlab report nodes --node glob will print out the names of the selected nodes
* The names of the selected nodes can be used in a bash script, for example:
```
#!/bin/bash
for n in $(netlab report --node "${1:-*}" nodes); do
echo $n
done
```
=> New report: names of selected nodes (to be used in bash scripts)

netsim/extra/ebgp.multihop/defaults.yml
=> SR Linux: Mark ebgp.multihop inside VRFs as supported

docs/platforms.md, netsim/devices/iosvl2.yml
Enable iosvl2 under containerlab provider. While at it, modify the provider by device matrix in documentation to reflect those changes. Default image is set to vrnetlab/iosvl2, tag 15.2.2020.
Hope this is not controversial ( didnt open an issue before to see if we want it,  but the deed is done)
=> Enable iosvl2 under containerlab provider. 

netsim/ansible/templates/eigrp/ios.j2
This fix results in a valid EIGRP configuration for an IOS device that has unnumbered interfaces. However, it looks like EIGRP does not work over unnumbered Ethernets anyway (it might over tunnels).
Closes #2440
=> Fix: Configure EIGRP on unnumbered interfaces

netsim/modules/bgp.py, netsim/modules/bgp.yml
Instead of having a hard-coded list of default session types (and similar), this change copies them from the valid values of global BGP attributes, making it possible for plugins to add new session types.
=> Fix: calculate BGP default values from valid values of BGP attributes

netsim/install/libvirt/openbsd/user-data
Disable kernel relinking (KARL, Kernel Address Randomized Link) by removing the checksum file instead of the relinking script.
Since disk space is very scarce with the current available VM image delete all the object files that would be used for kernel relinking and additional kernels in the same directory.
=> Better way to disable KARL and make more space

netsim/cli/install.py, netsim/install/install.yml, netsim/install/libvirt.sh
* Add a 'script configuration' file
* Use the 'scripts' keys from the configuration file to execute scripts in correct order
* Now that we have that file, display nice usage summary
Cleanup:
* Move the inline PIP/APT flag settings to a function
* Remove the ancient comments from libvirt.sh
=> Sort 'netlab install' scripts in dependency order

docs/plugins/mlag.vtep.md, netsim/ansible/templates/evpn/cumulus_nvue.j2, netsim/ansible/templates/lag/cumulus_nvue.j2, netsim/ansible/templates/vxlan/cumulus_nvue.j2, netsim/devices/cumulus_nvue.py, netsim/extra/mlag.vtep/defaults.yml, netsim/extra/mlag.vtep/plugin.py, netsim/modules/vxlan.py, tests/integration/mlag.vtep/03-evpn-vxlan-symm-irb.yml
This PR adds a symmetric IRB routing test case for the mlag.vtep plugin; it illustrates a few issues with the Cumulus NVUE templates (e.g. compared to Arista cEOS)
```
Cumulus NVUE:
xs# show bgp l2vpn evpn route type 5
BGP table version is 4, local router ID is 10.0.0.11
Status codes: s suppressed, d damped, h history, * valid, > best, i - internal
Origin codes: i - IGP, e - EGP, ? - incomplete
EVPN type-1 prefix: [1]:[EthTag]:[ESI]:[IPlen]:[VTEP-IP]:[Frag-id]
EVPN type-2 prefix: [2]:[EthTag]:[MAClen]:[MAC]:[IPlen]:[IP]
EVPN type-3 prefix: [3]:[EthTag]:[IPlen]:[OrigIP]
EVPN type-4 prefix: [4]:[ESI]:[IPlen]:[OrigIP]
EVPN type-5 prefix: [5]:[EthTag]:[IPlen]:[IP]
Network          Next Hop            Metric LocPrf Weight Path
Extended Community
Route Distinguisher: 65000:1
*>i …
```
=> Cumulus NVUE mlag vtep nexthop fixes

netsim/ansible/templates/initial/openbsd.j2, netsim/ansible/templates/routing/openbsd.j2, netsim/devices/openbsd.yml
- Configure and start rad on a router to send out RAs
- Utilise SLAAC on IPv6 enabled interfaces on a host
- Allow setting only IPv6 LLA
=> Improve OpenBSD interface configuration and enable handling of RAs.

netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/isis/sros.j2, netsim/ansible/templates/vrf/sros.j2
Most SR-OS configuration templates used 'declare_router' macro that would select the correct service configuration path based on interface data, leading to an awkward recreation of interface data in case we really wanted to configure a router, not an interface.
This fix adds another layer of indirection (proving RFC 1925) in front of the 'declare_router' macro to make the routing protocol configuration templates a bit cleaner.
=> Fix: Simplify SR-OS IS-IS template with 'configure_router' macro

docs/module/stp.md, netsim/ansible/templates/stp/ios.j2, netsim/devices/ioll2.yml
Based on Arista. 
It passes all netlab integration tests and was also validated on a lot of topologies from:
`https://github.com/ipspace/netlab-examples/tree/master/STP/examples`
Doesn't handle stub port types (does any template ???)
=> Initial implementation of iol2 STP

docs/module/stp.md, netsim/devices/iosvl2.yml
Enable STP support on Iosvl2 devices, and update platform support in stp module documentation.
Passes all current integration tests, as expected.
=> Enable STP support on Iosvl2 devices

netsim/augment/topology.py
Underscores in topology.name are used by clab to generate hostnames, and some Linux distros don't grasp that a clumsy person might have underscores in hostnames.
This fix ensures there are no weird characters in topology.name that is generated from the input directory (and 'default' is used when nothing is left after the cleanup). We don't check what the user specifies in the 'name' argument (they should know better ;)
Fixes #2424
=> Fix: no underscores in topology.name generated from input directory

netsim/cli/external_commands.py, netsim/cli/up.py
This fix tracks the status of 'tool.up' command(s) as well as the output generated by Docker. If the output contains 'warning...platform' text, we might be dealing with a container started on an incompatible platform, in which case we wait a bit (because it will crash very soon), check its status, and report the outcome.
The fix also adds better error reporting on tool start/stop failures and partial-success reporting.
Closes #2456
=> Fix: Check whether a tool was successfully started

netsim/ansible/templates/initial/ios.j2
Allow setting port channels interfaces as "no switchport". Keep current logic for everything else.
=> Allow setting "no switchport" on link agregations on cisco l2 images.

netsim/cli/install.py, netsim/install/containerlab.sh
'netlab install' uses /etc/os-release file to find the linux distro (ID) and its "parents" (ID_LIKE). It uses that information to check whether it's safe to execute an installation script and selects the best (= first mentioned in the config file) option from ID_LIKE when there's no exact match with ID.
=> Automatic detection of Linux distro in 'netlab install'

.github/workflows/t-pull.yml
The 'on-push' GH actions are not executed (within the context of main netlab repo) if the pull request comes from another repository, so we don't know whether they would pass.
This change brings mypy and transformation tests back to the 'on-pull' workflow, but hopefully executes them only if the source repo is not 'ipspace/netlab'
=> Fix: run on-push actions in pull requests from third-party repos

netsim/install/ubuntu.sh
Pop!_OS supposedly has the 'linux-modules-extra' package, but rejects to install it with a weird error messsage that doesn't even produce a proper exit code. This patch uses a slightly different approach to figuring out if the package is there to be installed.
Tested on Pop!_OS 22.04, Ubuntu 24.04 and Debian Bookworm
=> Fix: Handle the messed-up status of packages on Ubuntu derivatives

netsim/tools/suzieq.yml
This fix uses a different name for suzieq container and parquet volume, allowing 'netlab up' to check whether the container has started (otherwise 'docker inspect' returns volume info when asked about the container).
It also creates container without the 'auto remove' flag, so the user can inspect container logs in case of a fatal suzieq failure.
The 'tool.down' command was modified accordingly to kill the container and then remove it.
=> Fix: More robust suzieq tool definition

docs/module/lag.md, netsim/ansible/templates/initial/ios.j2, netsim/ansible/templates/lag/ios.j2, netsim/devices/ioll2.py, netsim/devices/ioll2.yml, netsim/devices/iosvl2.py, netsim/devices/iosvl2.yml
Enabled on ioll2 and iosvl2.
Passes integration tests lag  [01-03-*]. Test 04-lag-vlan-routed-trunk.yml crashes ioll2 image, and !!resets!! the running config of iosvl2.
=> Iosl2 lag implementation.

docs/module/lag.md, docs/module/stp.md
- spellchecking errors
- mention that we use long stp cost method for ioll2 / iosvl2
=> Documentation: spell-checking and a note of using long method in STP calculations

netsim/modules/_routing.py, tests/topology/expected/vxlan-router-stick.yml, tests/topology/input/vxlan-router-stick.yml
The original VRF IGP code checked whether the IGP should be active in the VRF based on whether adjacent nodes were running the same IGP, but not whether they could form an IGP adjacency with the node.
This fix is not perfect, but better than the original -- when checking whether a neighbor is a viable IGP neighbor, it checks not just the IGP module (for example, are both running OSPF), but also whether the two devices have any AF in common on the shared link. That results in IGP not being run between a router connected to a switch with L2-only VLAN (but might still result in IGP being active if the switch has an IP address but does not run IGP in that VRF).
The relevant transformation test was modified to:
* Run OSPF in the underlay
* Put VLANs into a VRF on the router-on-a-stick (to …
=> Fix: Activate VRF IGP interface only when there are viable neighbors

docs/caveats.md, docs/node/debug.md, docs/platforms.md, netsim/ansible/templates/initial/_debug_commands.j2, netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/initial/ios.j2, netsim/devices/frr.yml, netsim/devices/ios.yml
Adds device-specific attributes (ios.debug, frr.debug) that enable debugging at the beginning of initial device configuration.
The debugging attribute can be a list of debugging options or a multi-line string.
Replaces #2544
=> Add 'debug at startup' capability for IOS and FRR

docs/module/isis.md, netsim/ansible/templates/isis/eos.macro.j2, netsim/ansible/templates/isis/frr.macro.j2, netsim/ansible/templates/isis/ios.j2, netsim/ansible/templates/isis/junos.j2, netsim/ansible/templates/isis/nxos.j2, netsim/ansible/templates/isis/srlinux.macro.j2, netsim/ansible/templates/isis/sros.j2, netsim/ansible/templates/isis/vyos.j2, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/devices/ios.yml, netsim/devices/junos.yml, netsim/devices/nxos.yml, netsim/devices/srlinux.yml, netsim/devices/sros.yml, netsim/devices/vyos.yml, netsim/modules/isis.py, tests/integration/isis/03-dual-stack.yml
IS-IS Enable setting circuit type at interface level.
Implemented for ios, eos, frr.
=> IS-IS: Enable setting circuit type at interface level

docs/caveats.md, docs/module/isis.md, netsim/ansible/templates/isis/eos.macro.j2
Arista EOS knob to enable IPv6 ISIS BFD for all interfaces
=> IS-IS: Add IPv6 BFD support for all interfaces

netsim/augment/groups.py, netsim/augment/nodes.py, netsim/defaults/attributes.yml
The list of extra attributes namespaces in groups has been synchronized with the one in nodes. Instead of using hard-coded values, both instances use 'node_extra_ns' attribute value.
Closes #2551
=> Fix: allow output-specific attributes in group node data

docs/plugins.md, docs/plugins/files.md, netsim/augment/plugin.py, netsim/cli/__init__.py, netsim/cli/create.py, netsim/cli/down.py, netsim/extra/files/defaults.yml, netsim/extra/files/plugin.py, tests/integration/bgp/05-community.yml
The 'files' plugin can be used to embed any file (in particular custom configuration templates) into the lab topology.
The following changes were made to other netlab components to support this functionality:
* 'netlab create' calls 'output' plugin hooks for plugins that register themselves as having on in the defaults.netlab.create.output list
* 'netlab down --cleanup' removes files specified in the _cleanup dictionary
* The 'load plugin' and 'execute plugin hook' code was moved to separate functions so it can be called directly from 'netlab create' (the Plugin list is gone by the time 'netlab create' creates output files)
* The 'fs_cleanup' function tries to remove directories when the files it removes contain a directory component.
Finally, the 'bgp/05-community' integration test uses …
=> The 'files' plugin: embed files or custom config templates in topology

docs/netlab/collect.md, netsim/ansible/collect-configs.ansible, netsim/ansible/tasks/fetch-config/cumulus.yml, netsim/ansible/tasks/fetch-config/frr.yml, netsim/ansible/tasks/fetch-config/srlinux.yml, netsim/cli/collect.py
The 'netlab collect' command usually saves configuration files with the '.cfg' suffix (which can then be used in 'netlab up --reload' process). However, when building a multi-platform solution, it might be helpful to save the configuration files with a platform-specific suffix, for example 'eos.j2'. The '--suffix' parameter allows you to replace the standard 'cfg' suffix with something else
As a few 'fetch-config' task lists used hardcoded '.cfg' suffix, most of them were either fixed to use the 'cfg_suffix' variable or (even better) set 'ansible_net_config' fact instead of creating the output file directly.
=> Add '--suffix' parameter to 'netlab collect'

netsim/ansible/tasks/deploy-config/vyos-script.j2, netsim/ansible/tasks/deploy-config/vyos.yml, netsim/ansible/tasks/fetch-config/vyos.yml, netsim/ansible/tasks/readiness-check/vyos-clab.yml, netsim/ansible/templates/bgp/vyos.j2, netsim/ansible/templates/isis/vyos.j2
VyOS configuration templates are vbash scripts that include a lot of
setup and cleanup code. The same code is replicated in every template.
That is not good by itself, but it doesn't allow the users to use
simple custom config templates with just the 'set' commands.
This change implements configuration deployment similar to what
we're doing for FRR: if the configuration code includes 'vbash',
it's executed as-is, otherwise it's wrapped in a standard vbash
script.
Also changed:
* The 'are we ready' check has been moved from the 'deploy config'
task list to 'readyness check' task list
* The 'fetch config' task list fetches device configuration as
'set' commands, allowing it to be used directly as a custom config
template. That should allow 'netlab up --reload' to work with
VyOS.
=> VyOS: Implement configuration templates using only 'set' commands

netsim/modules/bgp.py, tests/topology/expected/6pe.yml, tests/topology/expected/addressing-ipv6-only.yml, tests/topology/expected/addressing-ipv6-prefix.yml, tests/topology/expected/bgp-anycast.yml, tests/topology/expected/bgp-autogroup.yml, tests/topology/expected/bgp-community.yml, tests/topology/expected/bgp-ibgp.yml, tests/topology/expected/bgp-members.yml, tests/topology/expected/bgp-sessions.yml, tests/topology/expected/bgp.yml, tests/topology/expected/components.yml, tests/topology/expected/ebgp.utils.yml, tests/topology/expected/evpn-asymmetric-irb-ospf.yml, tests/topology/expected/evpn-hub-spoke.yml, tests/topology/expected/evpn-l3vni-only.yml, tests/topology/expected/evpn-vxlan.yml, tests/topology/expected/fabric-ebgp.yml, tests/topology/expected/groups-node-data.yml, tests/topology/expected/module-reorder.yml, tests/topology/expected/mpls-vpn-simple.yml, tests/topology/expected/mpls.yml, tests/topology/expected/null-vrfs.yml, tests/topology/expected/vrf-igp.yml, tests/topology/expected/vrf-links.yml, tests/topology/expected/vrf-routing-blocks.yml
The BGP neighbor 'rr_client' and 'next_hop_self' attributes will make the configuration templates much cleaner as we'll avoid all the crazy logic that is repeated in every template.
Note that the existing attributes are not changed, so there's no rush to migrate the templates to the new attributes. That can be done at any time we feel like cleaning them up.
Also: refactor and cleanup the IBGP session generation logic to avoid duplicate code
=> Set 'rr_client' and 'next_hop_self' attributes on BGP neighbor data

docs/cli-overview.md, netsim/cli/validate.py
For example: .*v4 to run only ipv4 tests (assuming they are suitably named), in case a platform doesn't support OSPFv3 in VRFs
=> netlab validate: Allow the use of regular expressions to select tests

docs/netlab/create.md, docs/netlab/up.md, netsim/cli/__init__.py, netsim/cli/create.py, requirements-dev.txt, requirements.txt
The specified URL is downloaded, sanity-checked for YAML correctness, saved in 'downloaded.yml' and used as the lab topology.
Implements #1388
=> Specify the lab topology in netlab create/up command as filename or URL

docs/dev/config/deploy.md, docs/netlab/connect.md, docs/netlab/create.md, docs/netlab/down.md, docs/netlab/graph.md, docs/netlab/initial.md, docs/netlab/inspect.md, docs/netlab/report.md, docs/netlab/restart.md, docs/netlab/status.md, docs/netlab/up.md, docs/topology/validate.md, netsim/cli/__init__.py, netsim/cli/create.py, netsim/cli/down.py, netsim/cli/up.py, netsim/outputs/__init__.py, netsim/outputs/pickle.py, netsim/utils/files.py, netsim/utils/read.py, tests/platform-integration/large/01-large-topo.yml
* Add 'pickle' output module and use it as one of default outputs
* Refactor output file selection into 'select_output_file'. This function can be used by all output modules (future improvement)
* Add 'load_pickled_data' to 'utils.read'
* Read pickled or YAML data in 'load_snapshot' function
Minor changes:
* Change the default value of the 'args.snapshot' parameter
* Change the parser default value of '--snapshot' parameter
* Change the help message in 'netlab create' command
* Add 'snapshot' argument to 'netlab down' to be able to shut down a lab from the YAML snapshot file
* Add 'netlab.snapshot.pickle' as another file to clean up when the lab is shut down
* Fix exception reporting to use 'str(ex)' (just to be on the safe side)
Off-topic:
* Create a large topology in …
=> Use pickled data as snapshot file

docs/module/isis.md, docs/module/ospf.md, docs/module/routing_protocols.md, netsim/augment/nodes.py, netsim/defaults/attributes.yml, netsim/modules/_routing.py, netsim/modules/isis.yml, netsim/modules/ospf.py, netsim/modules/ospf.yml, tests/topology/expected/addressing-ipv6-prefix.yml, tests/topology/expected/bgp-autogroup.yml, tests/topology/expected/bgp-community.yml, tests/topology/expected/bgp-sessions.yml, tests/topology/expected/group-data-vrf.yml, tests/topology/expected/groups-hierarchy.yml, tests/topology/expected/groups-vlan-vrf.yml, tests/topology/expected/igp-af.yml, tests/topology/expected/module-node-global.yml, tests/topology/expected/mpls.yml, tests/topology/expected/vlan-vrf-lite.yml, tests/topology/expected/vrf-igp.yml, tests/topology/expected/vrf-links.yml, tests/topology/expected/vrf-routing-blocks.yml, tests/topology/expected/vrf.yml, tests/topology/input/groups-hierarchy.yml, tests/topology/input/igp-af.yml
* The loopback data is checked as a new 'loopback' type to allow IGP modules to register a subset of link/interface attributes as begin valid on the loopback interface
* The loopback interface must be validated with the top-level 'validate_attributes' function, otherwise the module attributes are not recognized.
* Loopback data is thus checked first as a dict/bool within the node data, and then rechecked against the new 'loopback' type (assuming the 'loopback' attribute is not set to True/False).
* The 'module attribute can be False' list is extended to include the 'loopback' data type
* We have to deal with 'is the IGP set to False on loopback' in numerous places within the generic routing code until we finally remove 'igp: False' data in 'remove_unused_igp' function
* To make that work, …
=> Implement select IGP parameters on the primary loopback interface

.github/workflows/t-pull.yml, netsim/providers/__init__.py, netsim/utils/strings.py
As we're not yet ready to say goodbye to our good friend Python 3.8, we still can't use str.removeprefix, so I added it to the strings utility module to keep mypy (and Ubuntu 20.04 users) happy.
Also: add Python 3.8 to pull request CI/CD pipeline to ensure a similar SNAFU won't happen anytime soon.
=> Fix: Implement 'str.removeprefix' in strings.utils for Python 3.8

docs/netlab/graph.md, docs/outputs/graph.md, netsim/cli/graph.py
We need a way to specify formatting parameters for BGP graphs in the 'netlab graph' command (it's too late to change topology defaults as the lab is already running).
=> Add '--format' parameter to 'netlab graph' command

docs/module/bgp.md, netsim/modules/bgp.yml, netsim/outputs/_graph.py
In a version far far ago, the bgp.as_list entry could have a 'name' attribute that was used in topology and BGP graphs. That attribute was lost once we implemented the strict data checking (because nobody remembered it at the time), and the graph refactoring done in 25.09 borked its use in graphs.
This PR is fixing both blunders and closes #2675
=> Add missing 'bgp.as_list.name' attribute we lost in the mists of time

docs/customize.md, docs/dev/config/deploy.md, netsim/augment/config.py, netsim/cli/__init__.py, netsim/utils/files.py
Replaces the solution proposed in #2660
=> Add '--debug: paths' option to help troubleshoot custom templates

docs/groups.md, docs/module/bgp.md, netsim/augment/groups.py, netsim/modules/bgp.py, netsim/modules/bgp.yml, tests/errors/bgp-as-list-attr.log, tests/errors/bgp-as-list-semantics.log, tests/errors/bgp-as-list-semantics.yml, tests/topology/input/bgp-members.yml
Also: ensure the expanded group members do not contain duplicate node names (irrelevant for regular groups, quite important for as_list)
Closes #2685
=> bgp.as_list support for wildcard/regexp member/rr attributes

docs/outputs/d2.md, docs/outputs/graph.md, netsim/outputs/_graph.py, netsim/outputs/graph.py, netsim/outputs/graph.yml, tests/platform-integration/graph/bgp.yml, tests/platform-integration/graph/create-graphviz.sh, tests/platform-integration/graph/isis.yml, tests/platform-integration/graph/topo.yml
The 'graph.rank' node attribute allows you to group nodes into layers in GraphViz graphs, and to ensure the node positioning is more closely aligned with the network topology in D2 graphs (D2 does not have a shape rank concept)
=> Implement node rank in graph definition files

tests/integration/bgp/04-originate.yml, tests/integration/bgp/14-ipv6-originate.yml, tests/integration/bgp/30-import-ds-ospf.yml, tests/integration/bgp/31-import-policy.yml, tests/integration/isis/21-import-ds.yml, tests/integration/ripv2/21-import-ds.yml, tests/integration/ripv2/31-vrf-ipv4.yml, tests/integration/ripv2/32-vrf-ipv6.yml, tests/integration/wait_times.yml
This change cleans up the kludges introduced to make Cisco IOS, IOS XE, and IOS XR pass BGP validation tests.
Even though the configuration templates were correct, it takes Cisco BGP implementations in some cases an incredibly long time to start announcing originated or redistributed routes.
The BGP origination and redistribution tests were modified to use more granular wait time constants. The default value of these constants is identical to what has been used in the past (so it should not impact any other integration test), but the IOS- and XR-specific values were turned up to 11 (OK, 60 or 80)
=> Use per-device validation wait times in BGP integration tests

netsim/install/ubuntu.sh
This fixes a bug when sudo isn't installed and the build is running as root.
=> Use $SUDO instead of sudo for extra packages
