docs/install.md, netsim/providers/__init__.py, netsim/templates/provider/libvirt/nxos-domain.j2, templates/initial/nxos.j2
=> Fix NXOS under AMD CPUs

.gitignore, create-topology, netsim/__init__.py, netsim/addressing.py, netsim/augment/links.py, netsim/augment/main.py, netsim/augment/nodes.py, netsim/augment/topology.py, netsim/cli_parser.py, netsim/common.py, netsim/inventory.py, netsim/modules/__init__.py, netsim/modules/isis.py, netsim/providers/__init__.py, netsim/read_topology.py
=> Remove all unused imports

netsim/read_topology.py, netsim/topology-defaults.yml, templates/initial/junos.j2
=> Bug fix: try and catch import resources (Python < 3.7)

connect.sh
=> Bug fix: Pass arguments to bash as -c 'arg1 arg2'

docs/labs/libvirt.md
As per documentation https://github.com/sciurus/vagrant-mutate#vagrant-mutate-1
=> Fix vagrant-mutate installation instructions

docs/labs/libvirt.md, docs/platforms.md, netsim/ansible/tasks/deploy-config/vyos.yml, netsim/ansible/tasks/fetch-config/vyos.yml, netsim/ansible/templates/bgp/vyos.j2, netsim/ansible/templates/initial/vyos.j2, netsim/ansible/templates/ospf/vyos.j2, netsim/templates/provider/libvirt/vyos-domain.j2, netsim/topology-defaults.yml, tests/integration/vyos.yml
Support for VyOS device type (https://vyos.io/).
Supported features:
- Initial config
- Config fetch
- BGP Module
- OSPF Module
Documentation is updated as well.
=> VyOS support

netsim/ansible/tasks/deploy-config/sros.yml, netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/initial/sros.gnmi.j2, netsim/ansible/templates/initial/sros.openconfig.j2, netsim/ansible/templates/isis/srlinux.j2, netsim/ansible/templates/isis/sros.gnmi.j2, netsim/ansible/templates/isis/sros.openconfig.j2, netsim/ansible/templates/sr/srlinux.j2, netsim/ansible/templates/sr/sros.gnmi.j2, netsim/ansible/templates/sr/sros.openconfig.j2, netsim/augment/nodes.py, netsim/templates/provider/clab/clab.j2, netsim/topology-defaults.yml, tests/topology/expected/extra-module-attr-link.yml
=> Add SRLinux/SROS ISIS+SR support (clean branch off latest 'dev')

docs/module/bfd.md, netsim/ansible/templates/bfd/srlinux.j2, netsim/ansible/templates/bfd/sros.gnmi.j2, netsim/ansible/templates/isis/srlinux.j2, netsim/ansible/templates/isis/sros.gnmi.j2, netsim/topology-defaults.yml, tests/module/isis-feature-test.yml, tests/topology/expected/isis-bfd-test.yml, tests/topology/input/isis-bfd-test.yml, tests/topology/input/isis-feature-test.yml
Including some minimal documentation, and a (simple, global) config test
=> Add BFD module (for IS-IS on SRLinux and SROS)

netsim/ansible/tasks/deploy-config/sros.yml, netsim/providers/clab.py, netsim/templates/provider/clab/clab.j2
Don't create bridges for 2 node links
=> Fix clab bridge conditions

netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/initial/sros.openconfig.j2, netsim/ansible/templates/isis/srlinux.j2, netsim/ansible/templates/ospf/srlinux.j2, netsim/ansible/templates/ospf/sros.gnmi.j2, tests/topology/expected/ospf.yml, tests/topology/input/ospf.yml
Add a test case for external links in OSPF
=> Update OSPF templates; also fixes 'module' references to be defined

netsim/ansible/templates/bfd/srlinux.j2, netsim/ansible/templates/bfd/sros.gnmi.j2, netsim/ansible/templates/ospf/srlinux.j2, netsim/ansible/templates/ospf/sros.gnmi.j2
Update templates to support BFD for OSPFv2
ipv4/v6 logic is still somewhat ugly for SROS, could be improved
=> Ospfv2 bfd for sros and srlinux

netsim/ansible/templates/isis/sros.gnmi.j2, netsim/topology-defaults.yml, tests/topology/expected/isis-bfd-test.yml
Checked using IS-IS unnumbered example
=> IS-IS unnumbered sros

docs/module/ospf.md, netsim/ansible/templates/ospf/routeros.j2, netsim/ansible/templates/ospf/vyos.j2
Improvement related to #123 for VyOS and RouterOS.
=> Improved OSPF templates for VyOS and RouterOS

netsim/ansible/templates/bgp/routeros.j2, netsim/ansible/templates/bgp/vyos.j2, netsim/ansible/templates/ospf/routeros.j2, netsim/ansible/templates/ospf/vyos.j2
=> Handle BGP and OSPF RouterID in VyOS and ROS

netsim/ansible/templates/bgp/sros.gnmi.j2, netsim/ansible/templates/initial/sros.gnmi.j2, netsim/ansible/templates/sr/sros.gnmi.j2
7250 IXR platform uses a different chipset, with different support for ECMP
=> Add SR OS IXR support and move SR bgp logic to sr module

netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/ospf/srlinux.j2
Fixes https://github.com/ipspace/netsim-tools/issues/171
=> Model stub interfaces as regular interfaces, not loopbacks; set passive flag

docs/caveats.md
See https://github.com/ipspace/netsim-tools/issues/168, Galaxy package hasn't been updated in 2 years
=> Update Nokia grpc plug-in install instructions to use git repo directly

netsim/ansible/templates/initial/junos.j2
Platforms:
- junos: Add static hostname mappings (Issue https://github.com/ipspace/netsim-tools/issues/139)
=> add junos static hostname mapping

docs/platforms.md, netsim/ansible/templates/initial/routeros.j2, netsim/ansible/templates/initial/vyos.j2
=> VyOS and ROS configurable MTU

netsim/install/libvirt/eos.txt, netsim/install/libvirt/vsrx.txt, netsim/install/libvirt/vsrx/juniper.conf
I'm a big fan of keeping the management traffic on a dedicated vrf.
Feel free to reject the PR if you don't like the approach (but I see you are doing the same on CSR, so I guess it's ok).
=> Doc for Management VRF in vEOS and vSRX

docs/module/ospf.md, netsim/ansible/templates/ospf/junos.j2, netsim/ansible/templates/ospf/junos.ospfv2.j2, netsim/ansible/templates/ospf/junos.ospfv3.j2
Support for OSPFv3 on Juniper vSRX.
(sorry for adding that just after the new release...)
=> OSPFv3 on vSRX

requirements-dev.txt
pytest is required for run-tests.sh
=> Pytest missing in requirements-dev.txt

netsim/install/ansible.sh, netsim/install/containerlab.sh, netsim/install/libvirt.sh, netsim/install/ubuntu.sh
Okay... here're the latest updates.
- Tested to see if the root user is doing the installation or if sudo is in the path before proceeding.
- Defined sudo as a variable so that the scripts can run as root in the absence of the sudo command.
- Corrected Y/n test to y/n and require an explicit [Yy] to proceed.
- Added an additional else statement in the lsb-release test to cover all of the bases. There's no need to check the DISTRIBUTION variable because the script will fail without a valid debian_version / lsb-release combination.
Hopefully these updates cover the bases.
=> Debian Compatibility

docs/outputs/graphite.md
According to: https://twitter.com/netreplica/status/1516803584175747080
=> [Fix] Graphite mount point for default.js

docs/module/vlan.md, netsim/ansible/templates/vlan/vyos.j2
Configuration generation has been verified.
Pending end-to-end validation after #270 .
=> VyOS: VLAN Trunk support

netsim/install/ansible.sh
Hi,
`netlab install ansible` is broken when launched inside a virtual env.
I checked the other bash script inside "installation" and they are not impacted since they don't call `pip`.
Cheers
Julien
=> Fix ansible install inside VENV

netsim/extra/ebgp_utils/eos.j2, netsim/extra/ebgp_utils/ios.j2, netsim/extra/ebgp_utils/plugin.py, netsim/extra/ebgp_utils/vyos.j2
Plugin ebgp_utils: handle some additional parameters on eBGP sessions.
Initial implementation with: allowas-in, as-override, password.
Implemented for Arista EOS, Cisco IOS, VyOS.
=> Plugin ebgp_utils: handle some additional parameters on eBGP sessions

docs/dev/config/vlan.md, docs/module/vlan.md, netsim/ansible/templates/initial/vyos.j2, netsim/ansible/templates/initial/vyos.vlan.j2, netsim/ansible/templates/vlan/vyos.j2, netsim/topology-defaults.yml
=> VyOS: support for routed VLANs

docs/dev/config/vlan.md, docs/module/vlan.md, netsim/ansible/templates/initial/routeros.j2, netsim/ansible/templates/initial/routeros.vlan.j2, netsim/ansible/templates/initial/routeros.vrf.j2, netsim/ansible/templates/vlan/routeros.j2, netsim/modules/vlan.py, netsim/topology-defaults.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vlan-trunk-native.yml
@ipspace most probably this will have conflicts due to #298.
After that one has been merged, I'll rebase this.
=> RouterOS: Support for VLAN

docs/module/vxlan.md, netsim/ansible/templates/vxlan/dellos10.j2, netsim/ansible/templates/vxlan/vyos.j2, netsim/topology-defaults.yml, tests/integration/vxlan/vxlan-bridging-multivendor.yml
+ Test topology for EOS+VyOS+OS10 interworking.
=> Initial VXLAN support on VyOS and Dell OS10

docs/module/evpn.md, netsim/ansible/templates/evpn/vyos.j2, netsim/ansible/templates/vrf/vyos.bgp.j2, netsim/topology-defaults.yml
Current limitation:
https://phabricator.vyos.net/T4636
(shoud be fixed soon, hopefully)
Will wait for merge and then rebase, before marking it as complete.
=> VyOS: support for EVPN Symm IRB

docs/module/evpn.md, docs/platforms.md, netsim/ansible/templates/bgp/dellos10.macro.j2, netsim/ansible/templates/evpn/dellos10.j2, netsim/ansible/templates/initial/dellos10.vrf.j2, netsim/ansible/templates/vlan/dellos10.j2, netsim/ansible/templates/vxlan/dellos10.j2, netsim/topology-defaults.yml
- EVPN with L2VNI and L3VNI
- Support for EVPN iBGP-over-eBGP (using the local_as plugin)
- Refactoring on Dell OS10 VLAN handling, Using virtual-network logic, instead of plain VLAN interfaces
=> Dell OS10: Support for EVPN

netsim/ansible/templates/bgp/srlinux.macro.j2
Need to make general bgp template aware of evpn logic to make this happen
=> Allow for evpn-only ibgp sessions

netsim/ansible/templates/bgp/frr.j2, netsim/ansible/templates/initial/frr.j2, netsim/topology-defaults.yml
Cleaned up version of earlier PR
=> Enable bgp ipv6 unnumbered for frr

netsim/extra/ebgp.utils/srlinux.j2
* bgp.default_originate
* bgp tcp-md5 password authentication (basic)
* bgp.allowas_in
* bgp.as_override
=> Add srlinux support for ebgp.utils plugin

netsim/modules/evpn.py
In Python, bool is a subtype of int
=> Fix check for type(vni) != "int"

netsim/addressing.py, tests/topology/expected/vlan-role-unnumbered.yml, tests/topology/input/vlan-role-unnumbered.yml
Fixes https://github.com/ipspace/netlab/issues/424
=> Fix prefix parse error due to bool being converted to string

netsim/ansible/templates/initial/frr.j2
Fixes https://github.com/ipspace/netlab/issues/449
=> Handle role=host case where loopback is not set

docs/module/bgp.md, netsim/ansible/templates/bgp/dellos10.macro.j2, netsim/ansible/templates/bgp/vyos.j2, netsim/topology-defaults.yml
=> Align VyOS and Dell OS10 with tunable AFIs and co

netsim/ansible/templates/bgp/srlinux.macro.j2, tests/integration/bgp/ibgp-v6.yml
* ipv6/64 loopback prefix needs to be normalized
* interface subnet prefixes
* some issue with neighbor stanza, possibly due to ':' characters in neighbor ip
* use passive transport for RR
=> srlinux: Some fixes plus a test case for ipv6 bgp issues

netsim/topology-defaults.yml
=> VyOS and ROS6 support vlan.native_routed

netsim/addressing.py
An address pool like 10.0.1.0/20 is currently accepted, but leads to errors when provisioning static routes on Linux hosts
=> Normalize IP address strings, check pool prefixes for host bits

docs/labs/routeros7.txt, netsim/install/libvirt/routeros7.txt
=> ROS7: add missing install txt

netsim/ansible/tasks/create-custom-config.yml
=> [FIX] netlab initial -o work with subdir

netsim/ansible/templates/ospf/sros.gnmi.j2
YANG model does not like multiple list entries with same area-id -> split into multiple updates
=> Fix ospf interface structure

netsim/callback.py, netsim/modules/srv6.py
* srv6 module was broken (wrong import)
* Print error about being unable to load a given module also without verbosity enabled, include details
=> Fix unloadable modules and visibility of associated debug prints

netsim/ansible/templates/vxlan/srlinux.j2
=> Fix learn-unsolicited for ipv6 case

netsim/ansible/templates/initial/srlinux.j2, netsim/ansible/templates/vxlan/frr.j2, tests/integration/evpn/vxlan-bridging-leaf-spine.yml
* Fix typo in custom mtu attribute
* Set ip-mtu (defaults to 1500) in addition to ethernet mtu
* FRR: Increase vxlan interface mtu to largest value over all interfaces
* Modify integration test to include larger custom mtu on vxlan fabric links
=> Critical: srlinux and frr fix custom link mtu for vxlan

docs/nodes.md, netsim/augment/nodes.py, netsim/outputs/ansible.py, netsim/outputs/provider.py, netsim/topology-defaults.yml, tests/topology/input/unmanaged-device.yml
NOTE: I created the "input" test but not the "expected" one - not sure how to generate it in this very specific case.
Addresses #547
=> Support for unmanaged devices (aka "ghosts")

netsim/ansible/templates/bgp/sros.j2
Somehow got lost since PR #561
=> Critical: sros re-add next-hop-self policy

docs/module/gateway.md, netsim/ansible/templates/gateway/sros.j2, netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/ospf/sros.j2, netsim/ansible/templates/vxlan/sros.j2, netsim/topology-defaults.yml
Known issues:
* ISIS (unchanged here) only works in base routing instance, not inside VRFs yet
=> Add SROS support for anycast gateway and VRRP

netsim/ansible/tasks/deploy-config/srlinux.yml, netsim/ansible/tasks/deploy-config/sros.yml, netsim/ansible/templates/bgp/sros.gnmi.macro.j2, netsim/ansible/templates/vxlan/srlinux.j2, netsim/ansible/templates/vxlan/sros.j2
* Skip retries when verbosity level is set, to see error messages
* srlinux: Handle case of empty import/export list
* sros: Configure RT also for L3 VNIs
* sros: Enable VRF apply-import/export
* sros: Don't enable client-reflect (RR) within VRF context
=> Various fixes sros/srlinux

netsim/augment/groups.py
Fixes https://github.com/ipspace/netlab/issues/619
(seems like the code that checks node attributes and the code that checks group level attributes could share some of the same logic?)
=> Allow provider attributes in groups too

docs/caveats.md, docs/module/evpn.md, docs/module/ospf.md, docs/platforms.md, netsim/ansible/templates/evpn/dellos10.j2, netsim/topology-defaults.yml
For #622 
++ documented a caveat found on Dell OS10, OSPF and Virtual-Network interfaces
=> Define support for EVPN Asymm IRB on Dell OS10 and VyOS

netsim/ansible/templates/evpn/srlinux.j2, netsim/ansible/templates/vxlan/srlinux.j2
Context: https://github.com/ipspace/netlab/issues/562 and https://github.com/ipspace/netlab/issues/622
Need to advertise IPs in EVPN RT2 routes for the asymmetric case. Also verified that OSPF inside vrf works as expected
=> srlinux evpn asymmetric fixes

docs/labs/clab.md
To address https://github.com/ipspace/netlab/issues/599
Perhaps more of a 'dev' item
=> Document clab config_templates

docs/labs/asav.md, docs/module/isis.md, docs/platforms.md, netsim/ansible/tasks/deploy-config/asa.yml, netsim/ansible/tasks/fetch-config/asa.yml, netsim/ansible/templates/bgp/asa.j2, netsim/ansible/templates/bgp/asa.macro.j2, netsim/ansible/templates/initial/asa.j2, netsim/ansible/templates/isis/asa.j2, netsim/cli/libvirt.py, netsim/install/libvirt/asav.txt, netsim/install/libvirt/asav/day0-config, netsim/modules/_routing.py, netsim/templates/provider/libvirt/asav-domain.j2, netsim/topology-defaults.yml
I have added Cisco ASA images to netlab and configurations for
- initial config
- IS-IS
- BGP
I look forward to feedback.
=> Introduce Cisco ASA platform

docs/caveats.md, docs/module/gateway.md, netsim/ansible/templates/gateway/dellos10.j2, netsim/ansible/templates/gateway/vyos.j2, netsim/topology-defaults.yml
* VyOS
* VRRP 3 (v4 and v6)
* Dell OS10
* Anycast - *partial* (see new caveats)
* VRRP 3 (v4 and v6) - *partial* (see new caveats)
Tested with all the module "integration test" files.
**SAD NOTE**: New caveats for Dell OS10
=> VyOS and Dell OS10 - support for Gateway module

netsim/modules/vlan.py
=> Check that interface has neighbors attribute

netsim/ansible/templates/isis/srlinux.j2
Check for platform type ixr6 or ixr10
=> IS-IS multi-topology only supported on some platforms

docs/platforms.md, netsim/topology-defaults.yml
Using info from https://containerlab.dev/manual/kinds/vr-ftosv/ and https://github.com/hellt/vrnetlab/tree/master/ftosv
=> Dell OS10 works also with clab

netsim/ansible/templates/evpn/srlinux.j2, netsim/ansible/templates/ospf/srlinux.macro.j2
* Don't assume vrfs is defined when using EVPN
* Fix stub interface naming for OSPF
=> SRLinux template fixes

docs/caveats.md, docs/platforms.md, netsim/ansible/templates/bgp/srlinux.j2, netsim/ansible/templates/bgp/srlinux.macro.j2, netsim/topology-defaults.yml
* New default admin password
* Policy model YANG changes
=> Updates to accommodate changes in SR Linux release 22.11.1

docs/dev/config/initial.md, docs/dev/device-box.md, docs/dev/device-platform.md, docs/dev/devices.md
=> Update developer documentation to use device parameter files

netsim/ansible/templates/initial/junos.j2
=> Fixes #731 - JunOS MTU

netsim/ansible/tasks/deploy-config/srlinux.yml, netsim/ansible/tasks/deploy-config/sros.yml, netsim/ansible/templates/gateway/sros.j2
* Check for plugin only once per device
* Fix SR OS anycast gateway ID (vrrp not present)
=> SR OS / SR Linux enhancements

docs/netlab/create.md, docs/netlab/up.md, docs/plugins.md, docs/plugins/multilab.md, netsim/augment/plugin.py, netsim/augment/topology.py, netsim/cli/__init__.py, netsim/defaults/multilab.yml, netsim/extra/multilab/plugin.py, netsim/providers/__init__.py, netsim/providers/libvirt.py, netsim/providers/libvirt.yml, netsim/read_topology.py, netsim/templates/provider/clab/clab.j2, netsim/templates/provider/libvirt/Vagrantfile.j2, netsim/templates/provider/libvirt/libvirt-bridge.j2, netsim/templates/provider/libvirt/libvirt-tunnel.j2, netsim/templates/provider/libvirt/vsrx-domain.j2, tests/integration/multilab/topology.yml
Implements 'multilab' plugin that modifies numerous system defaults based on 'lab id' specified in lab topology, defaults, or CLI argument. Documentation @ docs/plugins/multilab.md
=> Running Multiple Labs on Linux Servers

netsim/ansible/templates/ospf/sros.j2
System interface was being left out due to missing IP address
=> SR OS OSPF: Include system interface

docs/netlab/down.md, docs/netlab/up.md, docs/release/1.5.md, netsim/cli/__init__.py, netsim/cli/down.py, netsim/cli/external_commands.py, netsim/cli/restart.py, netsim/cli/up.py, netsim/outputs/__init__.py, netsim/providers/clab.py, netsim/providers/libvirt.py
Also: do a bit of cleanup in various CLI modules
=> Implement dry-run functionality for netlab up/netlab down

netsim/install/containerlab.sh
I've spoken to the maintainers and they agree the recent version upgrade could have been handled more smoothly - but going forward, they suggested picking a specific version
=> Update containerlab.sh - pick specific Containerlab version

netsim/providers/clab.yml
Points at a missing test case - I'll see if I can add that
=> Update clab.yml - allow srl-agents attribute

netsim/ansible/templates/initial/sros.j2
Don't depend on other platforms/tools to enable ports
=> Update sros.j2 - enable ports

netsim/ansible/templates/evpn/sros.j2, netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/vrf/sros.j2
The 7250 IXR platform uses ECMP profiles rather than direct ECMP values
=> Fixes for IXR ECMP profiles

docs/caveats.md, docs/platforms.md, netsim/ansible/tasks/readiness-check/vsrx.yml, netsim/devices/vsrx.yml
Supporting also vSRX running in containerlab (using vrnetlab)
=> Juniper vSRX: support for Containerlab

docs/module/ospf.md, netsim/ansible/templates/bfd/sros.j2, netsim/ansible/templates/ospf/sros.j2, netsim/devices/sros.yml, netsim/modules/ospf.py, netsim/modules/ospf.yml, tests/integration/ospf/ospfv2/strict_bfd.yml, tests/module/ospf-feature-test.yml
Could also be added as a plug-in - let me know if that's preferred
=> Add support for RFC9355 OSPF BFD Strict-Mode

netsim/devices/arubacx.yml, netsim/devices/dellos10.yml, netsim/devices/junos.yml, netsim/devices/routeros.yml, netsim/devices/routeros7.yml, netsim/devices/vmx.yml, netsim/devices/vptx.yml, netsim/devices/vsrx.yml, netsim/devices/vyos.yml, netsim/modules/bfd.yml, netsim/modules/bgp.yml, netsim/modules/evpn.yml, netsim/modules/gateway.yml, netsim/modules/isis.yml, netsim/modules/mpls.yml, netsim/modules/ospf.yml, netsim/modules/sr.yml, netsim/modules/vlan.yml, netsim/modules/vrf.yml, netsim/modules/vxlan.yml
Aligned device feature "auto-generation" for
- dellos10
- arubacx
- vyos
- routeros
- routeros7
Additionally, created a "meta" device junos, with no specific provider support (apart from external), to be used for other juniper devices attributes inheritance.
=> Align device features/inheritance

docs/labs/arubacx.md, docs/release/1.6.md
* fix a typo in release notes
* update link for arubacx download (latest version)
=> Minor documentation fixes

netsim/ansible/tasks/readiness-check/arubacx.yml, netsim/devices/arubacx.yml, netsim/install/containerlab.sh
In draft status waiting for next containerlab release after https://github.com/srl-labs/containerlab/pull/1488
=> Support for ArubaOS-CX with containerlab

docs/platforms.md
Sorry, forgot to update the documentation
=> Update platform doc for AOS-CX on CLAB

netsim/modules/evpn.yml, tests/topology/expected/evpn-vlan-attr.yml, tests/topology/input/evpn-vlan-attr.yml
Due to a typo, vlan attributes were broken
Added a regression test case
=> Fix EVPN VLAN attributes

netsim/install/ubuntu.sh
=> Add linux-modules-extra to ubuntu install script

netsim/modules/vlan.py, tests/topology/expected/vlan-mode-priority.yml, tests/topology/input/vlan-mode-priority.yml
=> Copy node-level vlan.mode into global VLANs copied into node VLANs

netsim/ansible/tasks/deploy-config/sros.yml, netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/vlan/sros.j2, netsim/ansible/templates/vxlan/sros.j2
On IXR, an ECMP profile is used instead of an absolute number
=> Fixes for 7250 IXR platform

netsim/ansible/templates/initial/junos.vlan.j2, netsim/modules/vlan.py, tests/topology/expected/anycast-gateway.yml, tests/topology/expected/bgp-vrf-local-as.yml, tests/topology/expected/evpn-vxlan.yml, tests/topology/expected/group-data-vlan.yml, tests/topology/expected/rt-vlan-anycast.yml, tests/topology/expected/rt-vlan-mode-link-route.yml, tests/topology/expected/rt-vlan-native-routed.yml, tests/topology/expected/rt-vlan-role-unnumbered.yml, tests/topology/expected/rt-vlan-trunk-partial-overlap.yml, tests/topology/expected/vlan-access-links.yml, tests/topology/expected/vlan-access-neighbors.yml, tests/topology/expected/vlan-access-node.yml, tests/topology/expected/vlan-access-single.yml, tests/topology/expected/vlan-bridge-trunk-router.yml, tests/topology/expected/vlan-coverage.yml, tests/topology/expected/vlan-mode-priority.yml, tests/topology/expected/vlan-native-routed.yml, tests/topology/expected/vlan-routed-access.yml, tests/topology/expected/vlan-routed-vrf.yml, tests/topology/expected/vlan-routed.yml, tests/topology/expected/vlan-router-stick.yml, tests/topology/expected/vlan-trunk-native.yml, tests/topology/expected/vlan-vrf-lite.yml, tests/topology/expected/vrf-leaking-loop.yml, tests/topology/expected/vxlan-router-stick.yml, tests/topology/expected/vxlan-static.yml
=> Consistently use _vlan_mode attribute throughout the VLAN module

docs/links.md, docs/module/bgp.md, docs/plugins.md, docs/plugins/ebgp.multihop.md, netsim/extra/ebgp.multihop/defaults.yml, netsim/extra/ebgp.multihop/ebgp-multihop-load-balancing.yml, netsim/extra/ebgp.multihop/eos.j2, netsim/extra/ebgp.multihop/evpn-ebgp-over-ebgp.yml, netsim/extra/ebgp.multihop/plugin.py
Missing bits:
* per-AF activation
* BGP session attributes
* Integration with ebgp.utils
=> EBGP multihop plugin

docs/addressing.md, docs/example/addr-builtin.txt, docs/example/addr-ipv6.txt, docs/example/addr-static.txt, netsim/augment/addressing.py, netsim/augment/nodes.py, netsim/defaults/attributes.yml, tests/topology/expected/addressing-ipv6-prefix.yml, tests/topology/input/addressing-ipv6-prefix.yml
=> Add configurable IPv6 prefix length to address pools

docs/plugins/bgp.policy.md, docs/plugins/bgp.session.md, docs/plugins/ebgp.multihop.md, netsim/devices/arubacx.yml, netsim/extra/bgp.policy/_route_map_aoscx.j2, netsim/extra/bgp.policy/arubacx.j2, netsim/extra/bgp.policy/defaults.yml, netsim/extra/bgp.session/arubacx.j2, netsim/extra/bgp.session/defaults.yml, netsim/extra/ebgp.multihop/arubacx.j2, netsim/extra/ebgp.multihop/defaults.yml
Adding support on Aruba AOS-CX for plugins:
* bgp.session
* bgp.policy
* ebgp.multihop
=> AOS-CX: BGP plugins support

netsim/augment/devices.py
Implies missing regression test...
=> Typo 'feature' instead of 'features'

docs/install/ubuntu-vm.md
=> fixes outdated link in Ubuntu VM installation documentation

netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/isis/sros.j2, netsim/ansible/templates/mpls/sros.ldp.j2, netsim/ansible/templates/vlan/sros.j2
Context: https://github.com/ipspace/netlab/issues/942
=> Fix missing macro parameter 'name'

docs/module/mpls.md, netsim/ansible/templates/initial/sros.j2, netsim/ansible/templates/mpls/sros.bgp.j2, netsim/ansible/templates/mpls/sros.j2, netsim/ansible/templates/mpls/sros.ldp.j2, netsim/ansible/templates/mpls/sros.mplsvpn.j2, netsim/devices/sros.yml
Note: LDP within VRFs not currently configured properly
=> Add sros 6pe and bgp-lu

netsim/install/containerlab.sh, netsim/install/libvirt.sh, netsim/install/ubuntu.sh
=> Bug fix: installation scripts have to work with root user

docs/release.md
Release notes for 1.7.0 has broken referral to Validation feature
=> Fix release notes referral to validation feature

docs/caveats.md, docs/platforms.md, netsim/ansible/tasks/deploy-config/arubacx.yml, netsim/ansible/tasks/fetch-config/arubacx.yml, netsim/ansible/templates/initial/arubacx.j2
Fix #975 
Plus:
* implement collect/fetch
* update doc on L3VNI caveat
* set session auto confirm to allow running "netlab initial" multiple times
=> ArubaCX: fix MTU plus minor stuff

netsim/ansible/templates/initial/dellos10.j2, netsim/devices/dellos10.yml
=> Dell OS10: MTU fixes

netsim/augment/groups.py, netsim/augment/links.py, netsim/augment/nodes.py, netsim/data/types.py, netsim/data/validate.py, netsim/defaults/hints.yml, netsim/modules/bgp.py, netsim/modules/vlan.py, netsim/utils/log.py, netsim/utils/strings.py, tests/errors/anycast-prefix.log, tests/errors/evpn-asym-irb.log, tests/errors/invalid-group-all-members.log, tests/errors/invalid-group-member-element.log, tests/errors/invalid-group-member.log, tests/errors/node-dict-invalid-data.log, tests/errors/unnumbered-capability.log, tests/errors/vlan-link-error.log
=> Color-code error messages

docs/platforms.md, netsim/ansible/tasks/readiness-check/vptx.yml, netsim/devices/vptx.yml, netsim/install/containerlab.sh
Fixes #996
(easier than I thought ;) )
=> Juniper vPTX: support for Containerlab

netsim/cli/status.py
My first Pull Request via fork, it's not about the fix (it's the simplest fix I could think of!) it's about learning how to do more git things, for hopefully more things to come in the future!
=> #1058 add type int for netlab status instance

netsim/ansible/templates/vrf/vyos.j2
Fixes #1067 
```
[red]     h1 trying to reach srv [ node(s): h1 ]
[PASS]    h1: Ping to srv succeeded
[PASS]    Test succeeded
[blue]    h2 trying to reach srv [ node(s): h2 ]
[PASS]    h2: Ping to srv succeeded
[PASS]    Test succeeded
[s2s]     h1 should not be able to reach h2 [ node(s): h1 ]
[PASS]    h1: Ping to h2 failed as expected
[PASS]    Test succeeded
[SUCCESS] Tests passed: 3
```
=> VyOS: fix route leaking without BGP module

docs/caveats.md, netsim/ansible/templates/initial/arubacx.j2, netsim/ansible/templates/vrf/arubacx.bgp.j2, netsim/ansible/templates/vrf/arubacx.j2, netsim/ansible/templates/vrf/arubacx.ospfv2-vrf.j2
Fixes: 
* ipspace/netlab#1120
* ipspace/netlab#1122
=> Multiple Aruba Fixes

netsim/ansible/templates/initial/routeros7.j2, netsim/ansible/templates/ospf/routeros7.ospf-include.j2
* ipspace/netlab#1126
* ipspace/netlab#1127
=> Multiple fixes for RouterOS 7

netsim/devices/srlinux.py
Fixes https://github.com/ipspace/netlab/issues/1073
=> Add SR Linux quirk to catch inter-VRF leaking scenarios without EVPN

netsim/ansible/templates/ospf/srlinux.macro.j2
Fixes https://github.com/ipspace/netlab/issues/1072
=> SR Linux fix formatting of OSPF area id as ipv4 address

netsim/extra/bgp.session/arubacx.j2, netsim/extra/bgp.session/plugin.py, tests/integration/bgp.session/01-allowas-in.yml, tests/integration/bgp.session/10-timers.yml, tests/topology/expected/ebgp.utils.yml
=> Clear BGP sessions after configuring parameters in bgp.session plugin

netsim/ansible/templates/bgp/arubacx.j2, netsim/ansible/templates/bgp/arubacx.macro.j2
=> Speed up BGP on Aruba CX

docs/module/isis.md, netsim/devices/srlinux.py
"fixes" https://github.com/ipspace/netlab/issues/1169
=> Capture lack of IS-IS multi-topology support for SR Linux

netsim/ansible/templates/isis/srlinux.j2
=> Fix SR Linux IS-IS cost metric configuration

netsim/ansible/templates/ospf/sros.j2
=> SR OS fix ospf router id

netsim/ansible/templates/bgp/dellos10.j2, netsim/ansible/templates/bgp/dellos10.macro.j2, netsim/ansible/templates/vrf/dellos10.bgp.j2
=> Multiple fixes for OS10 BGP

netsim/extra/bgp.session/defaults.yml, netsim/extra/bgp.session/vyos.j2
=> VyOS: refactor of bgp.session template

netsim/ansible/templates/initial/srlinux.j2
=> SR Linux: Remove the hardcoded notion that stubs get implemented as loopbacks

docs/caveats.md, netsim/ansible/templates/bgp/routeros7.j2, netsim/ansible/templates/vrf/routeros7.bgp.j2, netsim/ansible/templates/vrf/routeros7.ospfv2-vrf.j2, netsim/extra/bgp.session/routeros7.j2
=> ROS7: fix new syntax for BGP and redistribute proto

netsim/ansible/templates/bgp/srlinux.macro.j2
* add explicit export policy at group level
* include BGP routes from peers and prefixes, including loopback unless excluded
=> srlinux: Fix bgp originate case 04

netsim/ansible/templates/bgp/sros.gnmi.macro.j2, netsim/ansible/templates/bgp/sros.j2, netsim/ansible/templates/vrf/sros.j2
=> SR OS: Add export policy to filter what gets announced

netsim/ansible/tasks/create-custom-config.yml, netsim/ansible/tasks/deploy-config/vyos.yml
=> Fix: update template file name render for custom config

docs/module/ripv2.md, netsim/ansible/templates/ripv2/vyos.j2, netsim/devices/vyos.yml
(all integration tests passed)
=> VyOS: support for ripv2 and ripng

netsim/ansible/tasks/readiness-check/vjunos-switch-clab.yaml, netsim/devices/vjunos-switch.py, netsim/devices/vjunos-switch.yml
vJunos-switch baseline - See #1253
=> vJunos-switch baseline

netsim/ansible/tasks/readiness-check/vptx.yml
Unfortunately the number of retries is too low :(
=> vPTX: need to increase the time to wait for interface to appear

docs/module/routing.md
See:
- https://tests.netlab.tools/_html/arubacx-libvirt-routing
- https://tests.netlab.tools/_html/vyos-libvirt-routing
=> Doc update for routing (mismatch with real capabilities)

netsim/ansible/templates/bgp/eos.macro.j2, netsim/ansible/templates/bgp/frr.j2, netsim/ansible/templates/bgp/ios.macro.j2, netsim/modules/bgp.py, tests/topology/expected/6pe.yml, tests/topology/expected/addressing-ipv6-only.yml, tests/topology/expected/addressing-ipv6-prefix.yml, tests/topology/expected/bgp-anycast.yml, tests/topology/expected/bgp-autogroup.yml, tests/topology/expected/bgp-community.yml, tests/topology/expected/bgp-ibgp.yml, tests/topology/expected/bgp-members.yml, tests/topology/expected/bgp-sessions.yml, tests/topology/expected/bgp.yml, tests/topology/expected/components.yml, tests/topology/expected/ebgp.utils.yml, tests/topology/expected/evpn-asymmetric-irb-ospf.yml, tests/topology/expected/evpn-hub-spoke.yml, tests/topology/expected/evpn-l3vni-only.yml, tests/topology/expected/evpn-vxlan.yml, tests/topology/expected/fabric-ebgp.yml, tests/topology/expected/groups-node-data.yml, tests/topology/expected/module-reorder.yml, tests/topology/expected/mpls-vpn-simple.yml, tests/topology/expected/mpls.yml, tests/topology/expected/vrf-igp.yml, tests/topology/expected/vrf-links.yml, tests/topology/expected/vrf-routing-blocks.yml
Also: modify EOS, FRR and IOS template to use the new attribute
=> Set source interface name (_source_ifname) on IBGP neighbors

docs/module/vrf.md, docs/plugins/ebgp.multihop.md, netsim/ansible/templates/bgp/arubacx.macro.j2, netsim/ansible/templates/vrf/arubacx.j2, netsim/ansible/templates/vrf/arubacx.ospfv3-vrf.j2, netsim/devices/arubacx.yml, netsim/extra/ebgp.multihop/arubacx.j2, netsim/extra/ebgp.multihop/defaults.yml
Tested with:
* https://github.com/ipspace/netlab/blob/dev/tests/integration/vrf/21-multi-vrf-ospfv3.yml
* https://github.com/ipspace/netlab/blob/dev/tests/integration/bgp.multihop/02-vrf.yml
=> ArubaCX: OSPFv3 in VRF, and ebgp multihop

docs/example/linux.md, docs/labs/multi-provider.md, docs/tutorials.md
=> Tutorial: add Linux hosts and custom software to a netlab topology

netsim/extra/bgp.session/srlinux.j2
Adds admin-state: enable
Fixes https://github.com/ipspace/netlab/issues/1293
=> Update srlinux.j2 - fix MD5 auth

docs/caveats.md, docs/module/bgp.md, docs/module/isis.md, docs/module/ospf.md, netsim/ansible/templates/isis/srlinux.j2, netsim/ansible/templates/ospf/srlinux.macro.j2, netsim/ansible/templates/routing/_redistribute.srlinux.j2, netsim/devices/srlinux.yml
The PR also includes route import/default route caveats for OSPF and BGP.
=> SR Linux: IS-IS route import

docs/labs/clab.md, docs/labs/libvirt.md, docs/netlab/capture.md, docs/netlab/cli.md, netsim/cli/capture.py, netsim/cli/usage.txt, netsim/defaults/hints.yml, netsim/defaults/netlab.yml, netsim/providers/__init__.py, netsim/providers/clab.py, netsim/providers/libvirt.py, netsim/utils/log.py, netsim/utils/read.py, netsim/utils/strings.py
=> Implement packet capture on VM- or container interfaces (netlab capture)

netsim/devices/dellos10.yml
=> OS10: Fix CLAB credentials

docs/caveats.md
Automatic L2 loop detection is ffs
=> Add caveat about STP being disabled on FRR

docs/module/gateway.md, netsim/modules/gateway.py, tests/topology/expected/vlan-vrrp.yml, tests/topology/input/vlan-vrrp.yml
=> Implement node-level 'gateway' parameters

docs/custom-config-templates.md, docs/customize.md, docs/netlab/config.md, docs/netlab/initial.md
Finally found time to describe the details of the custom configuration templates.
@ddutt: I hope I managed to capture everything we discussed. If something is unclear, please leave a comment or an improvement suggestion ;)
=> Improve the custom configuration template documentation (fixes #1348)

netsim/data/types.py, tests/errors/multicast-mac.log, tests/errors/multicast-mac.yml
Adds error test case to check
Fixes https://github.com/ipspace/netlab/issues/1428
=> Check for the multicast bit in MAC addresses, and report an error if set

docs/example/link-definition.md, docs/module/gateway.md, netsim/augment/links.py, netsim/modules/gateway.py, tests/topology/expected/vrrp-interface-granularity.yml, tests/topology/input/vrrp-interface-granularity.yml
=> Enable gateway protocols with interface-level granularity

netsim/modules/vlan.py
Multiple global VLANs configured with interface vlan.access on the same link generate an error, a combination of at most one global VLAN and one or more per-node VLANs generates a warning.
Fixes #1437
=> Bug fix: check for multiple access VLANs per link

netsim/augment/links.py, netsim/defaults/warnings.yml, netsim/modules/vlan.py, tests/topology/expected/addressing-lan.yml, tests/topology/expected/link-formats.yml, tests/topology/expected/vrf-leaking-loop.yml, tests/topology/input/addressing-lan.yml, tests/topology/input/link-formats.yml, tests/topology/input/vrf-leaking-loop.yml
Closes #1351, makes #1457 impossible
=> Detect duplicate IP address on links and bridge/irb VLANs

docs/labs/clab.md, netsim/providers/clab.yml, netsim/templates/provider/clab/clab.j2, netsim/utils/templates.py, tests/topology/expected/clab-attributes.yml, tests/topology/input/clab-attributes.yml
See https://containerlab.dev/manual/nodes/#dns
=> Add support for 'clab.dns' (DNS servers and search domain settings)

docs/extool/edgeshark.md, docs/extools.md, docs/plugins/multilab.md, netsim/tools/edgeshark.yml
- tool template
- initial documentation with caveats
=> Edgeshark support as external tool.

netsim/modules/stp.py
Based on https://github.com/ipspace/netlab/discussions/1486
* During node_pre_transform device support for the ```stp``` module hasn't been validated
* Allow the user to disable STP on a node and build topologies in which other devices run unsupported STP protocols
=> Move check for supported STP protocols to post_transform hook

docs/module/stp.md, netsim/ansible/templates/stp/cumulus.j2, netsim/ansible/templates/stp/eos.j2, netsim/devices/cumulus.yml, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/modules/stp.py, netsim/modules/stp.yml, tests/integration/stp/03-vlan-multi-link.yml
Tested use case 03 using cEOS and FRR
Fixes https://github.com/ipspace/netlab/issues/1505
=> Refactor stp port priority

netsim/providers/libvirt.py
=> Fix typo in bridge name variable

netsim/modules/stp.py, tests/errors/stp-on-l3-intf.log, tests/errors/stp-on-l3-intf.yml
Cannot configure STP on a L3 interface; check for that
=> Check for STP being applied to L3 interfaces

netsim/providers/__init__.py
=> Error when using unmanaged node

netsim/validate/linux.py
Fixes https://github.com/ipspace/netlab/issues/1567
=> Update linux.py - fix ipv4 ping

netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/ansible/templates/vrf/cumulus_nvue.j2
Fixes https://github.com/ipspace/netlab/issues/1587
=> Cumulus_nvue: Postpone putting interfaces into vrfs until the vrf is created

netsim/ansible/templates/bgp/cumulus_nvue.j2
* Explicitly set to 'on' or 'off'
* Add neighbor description
* Treat ibgp_localas as ibgp
* Check bgp.next_hop_self
Fixes #1606
=> Cumulus NVUE: Fix BGP communities being advertised

docs/netlab/show.md, netsim/cli/show.py, netsim/cli/show_commands/modules.py
=> Implement 'netlab show module --feature' argument

docs/module/ospf.md, netsim/modules/ospf.yml
Replaces https://github.com/ipspace/netlab/pull/1612
=> OSPF: Allow global default setting of ospf.passive (default: False)

netsim/ansible/tasks/readiness-check/vsrx.yml, netsim/ansible/templates/initial/frr.j2, netsim/devices/frr.yml, netsim/templates/provider/libvirt/frr-domain.j2, netsim/templates/provider/virtualbox/frr-domain.j2
Fixes #1595
Also: includes a YAML validation fix for an unrelated file
=> Change the FRR Vagrant box to Debian bookworm

docs/module/ospf.md, netsim/ansible/templates/ospf/cumulus.ospfv2.j2, netsim/ansible/templates/ospf/cumulus.ospfv3.j2, netsim/ansible/templates/ospf/eos.ospfv2.j2, netsim/ansible/templates/ospf/eos.ospfv3.j2, netsim/ansible/templates/ospf/frr.ospfv2.j2, netsim/ansible/templates/ospf/frr.ospfv3.j2, netsim/ansible/templates/ospf/ios.ospfv2.j2, netsim/ansible/templates/ospf/ios.ospfv3.j2, netsim/ansible/templates/ospf/nxos.ospfv2.j2, netsim/ansible/templates/ospf/nxos.ospfv3.j2, netsim/devices/cumulus.yml, netsim/devices/eos.yml, netsim/devices/frr.yml, netsim/devices/ios.yml, netsim/devices/nxos.yml, netsim/validate/ospf/eos.py, netsim/validate/ospf/frr.py, tests/integration/ospf/ospfv2/31-priority.yml, tests/integration/ospf/ospfv3/31-priority.yml
Includes integration tests and minor tweaks to the OSPF validation plugins
=> OSPF v2/v3 router priority (CL, EOS, FRR, IOS, NXOS)

netsim/ansible/templates/initial/cumulus_nvue.j2
Replaces https://github.com/ipspace/netlab/pull/1619
=> Cumulus NVUE: Replace underscores in hostname

netsim/devices/arubacx.yml
Updated version and container image name for AOS CX
=> AOS-CX: bump version and image name

docs/module/stp.md, netsim/ansible/templates/stp/arubacx.j2, netsim/devices/arubacx.yml
(may have a conflict after #1699 - will rebase if needed)
=> AOS-CX: support for STP (pvrst, mstp)

netsim/extra/bonding/plugin.py
0 is a valid bonding.ifindex value
=> Bonding: Fix bond creation when bonding.ifindex==0

docs/caveats.md
(documented as caveat)
Close #1730
=> Junos: require ncclient to be installed

netsim/ansible/templates/lag/dellos10.j2
Going back to my original quick fix
=> Dell OS10: Reduce mlag delay-restore timer from 90 to 30

docs/module/stp.md, netsim/devices/dellos10.py
"Fixes" https://github.com/ipspace/netlab/issues/1747
Also contains some doc fixes, too many check marks...
=> Dell OS10: Add quirk to report PVRST on virtual networks as not supported

netsim/augment/links.py, netsim/augment/nodes.py, tests/integration/bgp/08-ibgp-localas.yml
=> Fix: Add check for static loopback interface address validity

netsim/ansible/templates/bgp/srlinux.macro.j2
Fixes https://github.com/ipspace/netlab/issues/1808
=> SR Linux BGP localas_ibgp: Fix lookup of IP address based on neighbor ifindex

netsim/install/containerlab.sh, netsim/providers/clab.yml
=> Update to latest Containerlab version

netsim/ansible/templates/initial/cumulus.j2, netsim/ansible/templates/vlan/cumulus.j2
* Move all IP and MTU assignment to initial, remove it from vlan script
* Remove filter on interface types, simply do all
Fixes https://github.com/ipspace/netlab/issues/1843 (both those test cases pass now, I did test a couple of others but not all integration tests)
Could use some more testing, but I'm sharing for comments
=> Cumulus: Fix MTU setting on VLAN interfaces

netsim/devices/dellos10.py
The use of virtual networks for VLANs really limits the available functionality - VRRP is another example
=> Dell OS10: Add quirk to check for unsupported use of VRRP on virtual networks

netsim/ansible/templates/initial/cumulus_nvue.j2
Re-ran ```integration/lag/10-mlag.yml```
=> Cumulus NVUE: Fix indent error introduced by #1865

netsim/ansible/templates/stp/cumulus_nvue.j2
Fixes test case ```12-pvrst-vlan-disable```
=> Cumulus NVUE: Take vlan.stp.enable into account

netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/vlan/frr.j2
* Use 'i' for interfaces consistently
Fixes https://github.com/ipspace/netlab/pull/1900
=> FRR: Fix SVI MTU

netsim/ansible/templates/initial/cumulus_nvue.j2, netsim/ansible/templates/lag/cumulus_nvue.j2
Fixes https://github.com/ipspace/netlab/issues/1885
* Don't attach l3 interfaces to the bridge
* Move lag bridging config to lag module script, and only connect to bridge for MLAG cases
=> Cumulus NVUE: Fix l3 lag test case

netsim/modules/gateway.py
=> Gateway: Fix incorrect "merging" of non-protocol attributes

netsim/ansible/templates/vxlan/frr.j2
Allows FRR to pass integration/evpn/20-vxlan-irb-ospf.yml
Fixes #1943
=> FRR: Fix incorrect MTU setting on vxlan devices

docs/plugins/ebgp.multihop.md, netsim/extra/ebgp.multihop/cumulus_nvue.j2, netsim/extra/ebgp.multihop/defaults.yml
Passes ```14-vxlan-ebgp-ebgp```
=> Cumulus NVUE: Add ebgp.multihop support

docs/module/lag.md
Addresses https://github.com/ipspace/netlab/issues/1949
=> lag: Document lag.mlag.peer.backup_ip

netsim/ansible/templates/initial/linux/ubuntu.j2
… and fix the speed to 1G full duplex
Fixes https://github.com/ipspace/netlab/issues/1978
=> Ubuntu: Configure Systemd to disable auto-negotiation on Ethernet interfaces

netsim/devices/junos.py
=> vJunos quirk: EVPN cannot be used on EBGP sessions

docs/labs/libvirt.md, netsim/templates/provider/libvirt/libvirt-bridge.j2
=> Set libvirt MTU larger than 1500 on bridge-based networks

netsim/data/types.py, netsim/defaults/attributes.yml, tests/errors/node-invalid-name.log, tests/errors/node-invalid-name.yml
=> Fix: max_length parameter of 'id' type can refer to a constant

docs/links.md, docs/module/vlan.md
=> Clarify addressing rules on routed VLANs

docs/module/routing.md, netsim/modules/routing.py, netsim/modules/routing.yml, tests/topology/expected/rp-static-gw.yml, tests/topology/input/rp-static-gw.yml
=> Add default gateway as a valid next-hop for static routes

docs/module/routing_protocols.md, netsim/modules/bgp.py, tests/topology/expected/bgp-vrf-local-as.yml
=> Fix: Set 'external' role on inter-AS VLANs

netsim/augment/nodes.py, tests/topology/expected/dhcp-server-on-segment.yml, tests/topology/expected/dhcp-vlan.yml, tests/topology/expected/group-ansible-variables.yml
=> Skip creation of host static routes for DHCP clients

netsim/install/libvirt.sh
=> Change the installed Vagrant version to 2.4.3-1

netsim/templates/ansible.cfg.j2
=> Remove paramiko-specific options from ansible.cfg

docs/caveats.md, tests/integration/evpn/x-03-vxlan-symmetric-irb-same-vendor.yml
=> JunOS Caveat for EVPN vlan-aware and sym-irb-same-vendor test

netsim/modules/lag.py
=> lag: Check for lag links with Linux bridges after removing virtual ones

tests/integration/routing/20-static.yml
=> Fix 2115: bad collapsed yaml parsing on some env

docs/groups.md, docs/module/bgp.md
=> Document the impact of setting a node parameter for an auto-created node

netsim/daemons/bird/bird.j2, netsim/daemons/bird/protocols.j2, netsim/daemons/bird/radv.j2
Fixes https://tests.netlab.tools/bird/clab/initial/05-host.yml-validate.log
=> Bird: Do not send IPv6 RA in 'host' role

docs/module/ospf.md, netsim/daemons/bird.yml, netsim/daemons/bird/ospf.j2
Modified OSPFv2 tests (removing VRFs) pass
=> Bird: Implement OSPF timers, priority, password (simple, OSPFv2 only)

netsim/daemons/bird.yml, netsim/daemons/bird/ospf.j2
Test: ```ospf/ospfv2/10-import.yml```
=> Bird: Add support for OSPF protocol imports

netsim/extra/bgp.policy/dellos10.j2
=> Dell OS10: Fix VRF context for bgp.policy plugin

netsim/ansible/tasks/deploy-config/vyos.yml, netsim/ansible/templates/initial/vyos.j2
(proposal, based on stderr error message match - I know it's not "elegant", but it seems to work, since I found a template error with this)
Fix #2147
Fixes also a template error discovered with this "validation".
=> VyOS: ansible check for config failure

docs/links.md, docs/node-roles.md, netsim/roles/bridge.py, tests/errors/bridge.log, tests/errors/bridge.yml, tests/integration/gateway/02-vrrp.yml, tests/integration/initial/06-bridge.yml
=> Refactor multi-access links with bridge node to use 'bridge' attribute

netsim/ansible/templates/initial/frr.j2, netsim/ansible/templates/initial/linux/ubuntu.j2, netsim/ansible/templates/initial/linux/vanilla.j2
=> Set arp_announce to 2 on FRR and Linux

docs/module/routing.md, netsim/ansible/templates/routing/vyos.j2, netsim/devices/vyos.yml
Current "caveat" in integration testing: #2157
=> VyOS: support for static routing

LICENSE.md, docs/conf.py
=> Copyright and license: Update year to 2025

netsim/cli/__init__.py, netsim/cli/up.py, netsim/utils/stats.py
* Extract some useful data from lab topology (called at 'netlab up')
* Track which netlab commands were used
Implements the data-gathering part of #1481
=> Core usage-statistics-gathering functionality

docs/netlab/cli.md, netsim/cli/usage.py, netsim/cli/usage_actions/show.py, netsim/cli/usage_actions/utils.py, netsim/utils/stats.py
Also: implement _disabled flag in stats.json to stop collection
=> Add CLI interface to usage statistics

docs/module/bgp.md, netsim/modules/bgp.py, netsim/modules/bgp.yml
=> Make 'localas_ibgp' a valid bgp.activate value

netsim/modules/_routing.py
=> Fix: prune IGP interfaces based on IGP/interface AF match

netsim/modules/bgp.py, tests/topology/expected/bgp-community.yml, tests/topology/expected/bgp-vrf-local-as.yml
=> Fix: consider intf/node bgp.local_as when computing 'external' role

docs/module/mpls.md, netsim/modules/mpls.py
=> Fix: enable VPNv4/VPNv6 AF based on mpls.vpn settings

README.md, docs/caveats.md, docs/dev/device-box.md, docs/dev/device-platform.md, docs/dev/devices.md, docs/example/external.md, docs/example/linux.md, docs/example/release.md, docs/index.md, docs/install.md, docs/labs/nxos.md, docs/labs/virtualbox.md, docs/links.md, docs/netlab/create.md, docs/netlab/test.md, docs/outputs/provider.md, docs/platforms.md, docs/providers.md, docs/topology-overview.md
WSL and multipass Ubuntu VM are much better alternatives.
Closes #1788, closes #1629
=> Make VirtualBox and direct Windows/macOS installations obsolete

README.md, docs/netlab/cli.md, docs/netlab/defaults.md, netsim/cli/defaults.py, netsim/cli/usage.txt
=> netlab defaults: sysctl-like interface to netlab defaults

netsim/ansible/templates/initial/linux/ubuntu.j2
=> Ubuntu: Postpone disabling ipv6 on interfaces until after netplan has been applied

netsim/ansible/templates/bgp/cumulus_nvue.macro.j2
Fixes https://tests.netlab.tools/cumulus_nvue/libvirt/vrf/22-multi-vrf-bgp-ipv6.yml-initial.log
=> Cumulus NVUE: Filter duplicate network statements

netsim/augment/nodes.py
=> Add hint regarding gateway id conflict

netsim/cli/defaults.py
It was easiest to restructure the whole 'get the defaults' code and stop using the 'get topology defaults by reading empty package topo' that skipped directory and project defaults.
Fixes #2264
=> Fix: always consider directory and project defaults in 'netlab defaults'

docs/example/addr-custom-pools.txt, docs/example/selecting-vlan-mode.md, docs/example/vlan-addressing.md, docs/module/vlan.md, docs/tutorials.md
=> VLAN addressing tutorial

tests/integration/vrf/03-multi-vrf-loopback.yml, tests/integration/vrf/11-multi-vrf-ospf.yml, tests/integration/vrf/21-multi-vrf-ospfv3.yml, tests/integration/vrf/defaults-ipv6-only.yml
Triggered by #2274. Who knows what else will pop up
=> Use VRF loopbacks in VRF OSPFv2/v3 integration tests

docs/labs/clab.md
=> Document the dependencies between netlab and vrnetlab usernames/pwds

docs/caveats.md, docs/labs/clab.md, docs/platforms.md, netsim/ansible/tasks/readiness-check/fortinet.fortios.fortios-clab.yml, netsim/devices/fortios.yml
FortiOS: support running on containerlab ( + updated docs)
=> FortiOS: support running on containerlab

docs/dev/validation.md
=> Doc: update the list of data types + fix a typo

netsim/devices/cumulus_nvue.py
If the anycast IP is not provisioned, Cumulus keeps the VXLAN interface DOWN causing things to break
Fixes #2431
=> Cumulus NVUE: Add quirk to check for mlag.vtep plugin when VXLAN is used in combination with MLAG

docs/caveats.md, docs/labs/libvirt.md, docs/labs/openbsd.md, docs/labs/openbsd.txt, docs/module/routing.md, docs/platforms.md, netsim/ansible/tasks/deploy-config/openbsd.yml, netsim/ansible/tasks/readiness-check/openbsd-clab.yml, netsim/ansible/templates/initial/openbsd.j2, netsim/ansible/templates/routing/openbsd.j2, netsim/devices/openbsd.py, netsim/devices/openbsd.yml, netsim/install/libvirt/openbsd.txt, netsim/install/libvirt/openbsd.xml.j2, netsim/install/libvirt/openbsd/meta-data, netsim/install/libvirt/openbsd/user-data, netsim/templates/provider/libvirt/openbsd-domain.j2
Includes box building, configuration deployment, interface config, static routes, and documentation
=> Baseline libvirt OpenBSD implementation

docs/module/eigrp.md
=> Update EIGRP documentation

netsim/install/libvirt.sh
=> Create a vagrant pin file in apt preferences to stop potential upgrades

docs/plugins/bgp.policy.md, netsim/extra/bgp.policy/defaults.yml, netsim/extra/bgp.policy/dellos10.j2
Passes all tests in bgp.policy/60-aggregate.yml
=> Dell OS10: Implement BGP aggregation

netsim/modules/stp.yml
=> STP: Clarify documentation comment

docs/module/evpn.md, docs/module/vxlan.md
While #2477 waits for a resolution, the best we can do is document what needs to be done to get things to work.
=> Document undesired interactions between EVPN and VRF routing protocols

netsim/modules/lag.py
=> Lag: Refuse to work with bridge devices, things like IP allocation don't behave as expected

netsim/extra/bgp.policy/arubacx.j2
Fix #2523
(fall back to full session reset)
=> Aruba CX: Fix 2523 (soft out not working)

docs/caveats.md, netsim/ansible/templates/evpn/vjunos-switch.j2, netsim/ansible/templates/vxlan/vjunos-switch.j2, netsim/devices/vjunos-switch.py, netsim/devices/vjunos-switch.yml
(using a quirk for unique RD per routing instance)
=> vJunos-switch: support for explicit vlan-aware bundle

netsim/outputs/_graph.py, netsim/outputs/d2.py, netsim/outputs/graph.py
Also: refactor the 'parse format keywords' code in D2/GV BGP graphs
=> Fix: include VRF BGP sessions in the BGP graph

docs/caveats.md, docs/install.md, docs/labs/clab.md, docs/module/stp.md, netsim/devices/iosv.yml, netsim/devices/iosvl2.yml
DOC: Change all stale vrnetlab URLs to actual location
DOC: STP module. Fix footnote syntax for IOLL" and IOSVL2
Closes
https://github.com/ipspace/netlab/issues/2598
=> DOC: Change all stale vrnetlab URLs to actual location

netsim/utils/templates.py
The original code created a new Jinja2 environment for every rendered file because the search path might have changed. This patch uses a cache of Jinja2 environments indexed by search path(s), resulting in cached templates and thus faster rendering.
=> Performance: Cache Jinja2 environments by search paths

netsim/providers/clab.yml
=> Bump containerlab version to 0.69.3

netsim/cli/usage.txt
Simply add TC command and a description to cli/usage.txt. Closes #2669.
=> Add tc command description to usage.txt.

netsim/outputs/__init__.py, netsim/outputs/d2.py, netsim/outputs/graph.py, netsim/outputs/pickle.py, netsim/outputs/provider.py, netsim/outputs/report.py, netsim/outputs/yaml.py
=> Use shared select_output_file in output modules

netsim/defaults/hints.yml, netsim/modules/vlan.py, tests/errors/vlan-trunk-l3-attr.log, tests/errors/vlan-trunk-l3-attr.yml
=> Fix: Warn about L3 attributes used on VLAN trunks
